confluentinc/schema-registry

- bin/schema-registry-run-class
While trying to go through the Quickstart tutorial (http://confluent.io/docs/current/quickstart.html), I found that the kafka-avro-console-producer script was not finding the log4j.properties file in etc/schema-registry/log4j.properties
> Incorrect path to log4j.properties file for simple zip file layout

- avro-serializer/pom.xml
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDe.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroDecoder.java
- avro-serializer/src/test/avro/user.avsc
- avro-serializer/src/test/java/io/confluent/kafka/serializers/KafkaAvroSerializerTest.java
- Moved getByteBufferer into shared abstract class
- Added decoder to return specific Avro records
This allows us to work with Java kafka consumers using native compiled Avro objects.
This implements #144
> Added decoder to return a specific Avro record from bytes.

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStore.java
Current, if there's an error while the registry is trying to initialize, writing a Noop to Kafka, the error message is informative enough to know why the write failed.
If you include the nested exceptions, there should be more information to figure out the issue.
> Expose more information when registry fails to start

- client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java
Discovered in the course of looking at some poor Camus performance in https://groups.google.com/forum/#!topic/camus_etl/xyQMIGaibq0.
A call to `CachedSchemaRegistryClient#getVersion` will consult the `versionCache`, but on a miss and subsequent call to the remote registry, it won't then update the `versionCache` with the results of the call. In the case of the `AvroMessageDecoder` in Camus, this results in one schema registry call per message, which is very slow.
This PR updates the `versionCache` with the newly updated `schemaVersionMap` after a remote call, which has a major impact on Camus performance that uses the `AvroMessageDecoder`.
> Update the versionCache with a new schemaVersionMap for a subject

- avro-serializer/pom.xml
- avro-serializer/src/main/java/io/confluent/kafka/formatter/AvroMessageFormatter.java
- avro-serializer/src/main/java/io/confluent/kafka/formatter/AvroMessageReader.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDe.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDeConfig.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroDecoder.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroDeserializer.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroDeserializerConfig.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroEncoder.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroSerializer.java
- avro-serializer/src/test/java/io/confluent/kafka/serializers/KafkaAvroSerializerTest.java
Because some of the option parsing was getting messier between the two types of maps used to hold options (not to mention the significant redundancy across all the ser/deser classes), this also converts option parsing in the deserializers to use common-config's AbstractConfig class. The options are organized so we could also convert the serializers to use some of the same code, but I've left that change for a later patch.
@granders or @junrao should probably review this. One thing to keep an eye out for is whether I've missed any places I need to convert common-config exceptions to Kafka exceptions; since they're runtime exceptions we need to be careful about catching them everywhere they can possibly happen.
> Add implementation of new Deserializer interface.

- README.md
- docs/index.rst
- docs/intro.rst
> GH-177: Remove unneeded content-type headers for GET ops in quickstart and README

- pom.xml
Becomes useful e.g. when integration testing with the schema-registry (RestApp)
> Enable test code sharing

- docs/monitoring.rst
- pom.xml
Follows https://github.com/confluentinc/rest-utils/pull/21
> Update jersey, jackson and junit versions to match `rest-utils`

- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDeConfig.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroDeserializerConfig.java
- json-serializer/pom.xml
- json-serializer/src/main/java/io/confluent/kafka/serializers/KafkaJsonDecoderConfig.java
- json-serializer/src/main/java/io/confluent/kafka/serializers/KafkaJsonDeserializerConfig.java
- json-serializer/src/main/java/io/confluent/kafka/serializers/KafkaJsonSerializerConfig.java
As part of b42bde7d, we switched to using AbstractConfig instead of duplicating
a bunch of config parsing across different serializer/encoder
interfaces. However, it was using Kafka's AbstractConfig, which is not part of
the public interface where compatibility is maintained. This could cause issues
if the serializer is used with a newer version of Kafka where those classes have
changed (as they did recently after 0.8.2.1).
The drawback to this is that we have an extra dependency for
serializers. However, we can ensure compatibility with confluent-common and it
is a pretty tiny dependency.
> Switch serializer config classes to use AbstractConfig from confluent-common instead of from Kafka.

- docs/config.rst
- licenses/COPYRIGHT.jonathan-rodan.txt
Fixes a simple typo. Not a big change, but at least something.
> Fixes Typo in the docs. 'actsas' -> 'acts as'

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStore.java
- core/src/test/java/io/confluent/kafka/schemaregistry/ClusterTestHarness.java
@ewencp @fpj 
Quick review - just updating the args of `isZkSecurityEnabled` to match the change in signature in kafka trunk
> Fixed schema registry build against kafka trunk

- avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-converter/src/test/java/io/confluent/connect/avro/AvroConverterTest.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java
We were already including the version from the schema registry in the Avro
schema, but in a field that could potentially conflict with other systems and it
was not propagated to the Connect data. This ensures we use the Connect schema
version included by the source if it exists, then falls back on the schema
registry version.
> CC-44: Include version when deserializing Kafka Connect data.

- bin/kafka-avro-console-consumer
- bin/kafka-avro-console-producer
- config/connect-avro-distributed.properties
- config/connect-avro-standalone.properties
While testing these, I noticed the scripts for the Avro console
producer/consumer had fallen out of date with the packaging layout and never
seem to have supported development mode packaging. This also addresses both of
those issues.
> CC-53: Add worker configs for Avro Kafka Connect that integrates with schema registry.

- docs/deployment.rst
Changing an internal reference to fix a broken link to Zookeeper operations. This change is happening in parallel to a change in docs.git.
The parallel change being made is here: [PR-75 in docs](https://github.com/confluentinc/docs/pull/75).
> Fixing a broken link in the docs (pull request 2 of 2)

- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroDecoder.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroDeserializer.java
- avro-serializer/src/test/avro/extended_user.avsc
- avro-serializer/src/test/java/io/confluent/kafka/serializers/KafkaAvroSerializerTest.java
There are many scenarios where it's useful to be able to read a subset (projection) of an Avro message.  An example is when doing a stream-table join.  When reading messages from the stream, you need to extract only the primary-key fields from the message to do the lookup.
Confluent Platform should allow the user to optionally pass a schema to use for reading.
> Add support for Avro projections in decoders

- avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-converter/src/test/java/io/confluent/connect/avro/AvroDataTest.java
General and simplified fix for NullPointerException when optional fields are nested within another container type. Pull request also includes additional unit tests covering cases (not all of them) for nested optional array and string.
This is related to #272 and the patch in #273 which doesn't solve all cases. As described in issues and comments below the patch in #273 deals with optional nested arrays/maps/structs, but the NPE does in fact also occurs for e.g. optional nested strings.
References:
https://github.com/confluentinc/schema-registry/issues/267#issuecomment-170085908
https://github.com/confluentinc/schema-registry/pull/273/files?diff=unified#r49218338
> Unit tests and bugfix for NPE when using nested optional fields

- avro-converter/src/test/java/io/confluent/connect/avro/AvroDataTest.java
#276 fixed NPE when using nested optional fields. However it added unit tests only for optional Strings and Arrays. 
It also fixed issue #267, which was originally reported to fix NPE when using optional nested structs.
Just adding a test case for nested structs for completeness.
> Test cases for optional nested structs (issue #267)

- avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-converter/src/test/java/io/confluent/connect/avro/AvroDataTest.java
Connect optional values are converted to Avro unions of type {null, type}.
In fromConnectData(), avroSchema is used to get the fields of complex types (Struct, Array, Map) - however, if the complex type is optional the avroSchema is a union schema, resulting in NPE. 
Fix this by getting the schema of the underlying type from the Avro union.
> Fix fromConnectData for optional complex types

- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDe.java
- avro-serializer/src/test/java/io/confluent/kafka/serializers/KafkaAvroSerializerTest.java
This PR fixes the issue confluentinc/kafka-rest#118, where we are sending a `org.apache.avro.util.Utf8` object as a string to the `KafkaAvroSerializer`, and are getting an `IllegalArgumentException` error.
Check confluentinc/kafka-rest/pull/165 for more details.
> Allows any CharSequence implementation to be considered a string

- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDe.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDeConfig.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerializer.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroDecoder.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroDeserializer.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroEncoder.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroSerializer.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroSerializerConfig.java
- avro-serializer/src/test/java/io/confluent/kafka/serializers/KafkaAvroSerializerTest.java
Added test case for properties passed as Strings. Added check for MAX_SCHEMAS_PER_SUBJECT_CONFIG as String, then parse accordingly. This should resolve issue #284.
> Issue #284

- bin/schema-registry-run-class
- core/pom.xml
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStore.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreReaderThread.java
- core/src/test/java/io/confluent/kafka/schemaregistry/ClusterTestHarness.java
- core/src/test/java/io/confluent/kafka/schemaregistry/SSLClusterTestHarness.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreSSLAuthTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreSSLNoAuthTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/StoreUtils.java
- docs/config.rst
- docs/index.rst
- docs/security.rst
- pom.xml
This diff adds support for an SSL KafkaStore. The implementation is pretty straightforward, mostly involving forwarding config parameters to the Kafka clients. The tests were a little tricky, though.
There were a few implementation choices I made which I'm not sure are ideal:
* Some Kafka client configuration parameters have a default value of `null`. `ConfigDef` doesn't support optional parameters with a default value of `null`. My workaround is to make the default value in the schema registry `""` and convert that to `null` when I initialize the Kafka clients.
* I introduced two new test classes, one testing SSL with authentication, and the other testing SSL without authentication. I copy-pasted some code between these two, which feels bad. However, I couldn't figure out a better …
> KafkaStore SSL support.

- docs/config.rst
If you look at this page: http://docs.confluent.io/1.0/schema-registry/docs/config.html and this page: http://docs.confluent.io/1.0/schema-registry/docs/deployment.html#schemaregistry-mirroring there is an inconsistency between whether or not the port has high or low importance. I think that the port your process is running on is hugely important and so we should change the docs to agree on priority high.
> change the documentation on port to have a high priority and list it higher up in the docs

- core/src/test/java/io/confluent/kafka/schemaregistry/zookeeper/MasterElectorTest.java
`mvn test` was failing for a me and a colleague due to timeout errors. Bumping them up from 5000ms to 15000ms eliminated the failures. Requesting this change so that similar changes don't have to be made every time someone with a slower machine wants to run tests.
> Increase testing timeouts from 5000ms to 15000ms

- client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClient.java
The call to return all of the subjects for a schema registry instance was not implemented on the client. Added to interface, mock, & cache.
> Added get all subjects.

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStore.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreTest.java
- docs/config.rst
Addresses this issue: https://github.com/confluentinc/schema-registry/issues/335, where a Schema Registry operator may want to configure their own Kafka bootstrap servers instead of using what's stored in ZooKeeper.
> Introducing a new config: kafkastore.bootstrap.servers

- client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroCompatibilityChecker.java
- client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroCompatibilityLevel.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClient.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/avro/AvroCompatibilityTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTransitiveCompatibilityTest.java
This pull-request attempts to bring fully transitive schema compatibility checks to the **schema-registry**.
It has been [noted previously](https://github.com/granders/avro-experiment/blob/master/src/main/java/geoff/AvroThingy.java) that it is possible to generate a sequence of Avro schemas that are incrementally compatible yet the sequence does exhibit full transitive compatibility. For example, given the schema sequence `[A, B, C]`, it is quite possible that `B` is compatible with `A` and `C` is compatible with `B` yet `C` is not compatible with `A`. This situation arises with two Avro schema features: the toggling of `defaults` and the use of `aliases`. The breaking of transitive compatibility has been highlighted as one reason why [support for `aliases` in the …
> Option to apply fully transitive schema compatibility checking

- client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroCompatibilityLevel.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
This patch addresses issue #445 by simply modifying the error message returned to users who attempt to register incompatible schemas. The message has been generalized so that it is not misleading in the event that a schema is transitively incompatible with a schema other than the latest.
> Generalize schema incompatibility message.

- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDe.java
- avro-serializer/src/test/java/io/confluent/kafka/serializers/KafkaAvroSerializerTest.java
The KafkaAvroSerializer can serialize any type of message (primitives or Generic or SpecificRecord[1]) and deserialize them using GenericDatumReader. However, if we want to deserialize the messages into SpecificRecord then both key & value types of message must be SpecificRecord else we will get SerializationException[2], the problem is that the config `specific.avro.reader` is a read time property which will throw SerializationException if one of the message's key or value are not a subtype of SpecificRecord. 
We encounter this problem most commonly with keys of the messages which can be primitive type (mostly string/int) or avro type, we could use different serializer for primitives but it would mean changing the producer/consumer config for every topic which is not ideal, besides when …
> Handle primitive types when specific.avro.reader is true

- avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-converter/src/test/java/io/confluent/connect/avro/AvroDataTest.java
Logical type schema builders come pre-configured with the schema name and version. The generic code for setting the name and
version from an Avro schema would then cause exceptions because they check to see that the field has never been set
before. To handle this case properly, check whether the fields have been set and their values before trying to set them.
> Don't re-invoke SchemaBuilder.version() and SchemaBuilder.name() if the value has already been set.

- docs/config.rst
The documentation provides the `transitive_full` option to the `avro.compatibility.level` configuration option but the valid option is actually `full_transitive`.
Fatal error when using `transitive_full`:
```
INFO SchemaRegistryConfig values: 
...
avro.compatibility.level = transitive_full
...
(io.confluent.kafka.schemaregistry.rest.SchemaRegistryConfig)
ERROR Server configuration failed:  (io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain)
io.confluent.rest.RestConfigException: Unknown Avro compatibility level: transitive_full
at io.confluent.kafka.schemaregistry.rest.SchemaRegistryConfig.<init>(SchemaRegistryConfig.java:362)
at io.confluent.kafka.schemaregistry.rest.SchemaRegistryConfig.<init>(SchemaRegistryConfig.java:354)
at …
```
> Fix avro.compatibility.level full_transitive typo

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStore.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreTest.java
We don't want users to accidentally lose all schemas.
In addition to the test in the PR, I also made sure Quickstart didn't break.
> making sure schema registry doesn't start with uncompacted topic

- avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-converter/src/test/java/io/confluent/connect/avro/AvroDataTest.java
Addresses https://github.com/confluentinc/schema-registry/issues/480.
Adds "default: null" property to Avro schema for Kafka Connect schema's
that are marked as optional.
> Set default to null if schema is optional

- avro-serializer/src/main/java/io/confluent/kafka/formatter/AvroMessageFormatter.java
- avro-serializer/src/test/java/io/confluent/kafka/formatter/AvroMessageFormatterTest.java
Then AvroMessageFormatter passes byte[] to an Avro encoder, but Avro only likes ByteBuffer. 
So we need to ByteBuffer.wrap() instead.
A small unit test has been added.
> Wrap byte[] in ByteBuffer before passing to Avro's DatumWriter in AvroMessageFormatter

- core/src/test/java/io/confluent/kafka/schemaregistry/zookeeper/MasterElectorTest.java
There can be some latency in all the nodes picking up the master change from Zookeeper. It is ok for nodes to think there
isn't a master for some time, so allow for that in the validation code and sleep and retry a few times.
> Allow for some retries when validating that all nodes have the same master

- avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java
Use TO_AVRO_LOGICAL_CONVERTERS to convert default values that are Kafka connect logical data types to internal format which correspond to schema type. Logic copied from AvroData fromConnectData
> #556: Use TO_AVRO_LOGICAL_CONVERTERS to convert logical default values

- docs/api.rst
- docs/index.rst
- docs/intro.rst
- docs/schema-deletion-guidelines.rst
Documentation for SR delete API
> CLIENTS-286 CLIENTS-288

- config/connect-avro-distributed.properties
Updated the distributed worker configuration used in the examples to include the new properties used when Connect creates the internal storage topics. The complicating factor is that the examples should work when run with a single broker, but the default replication factor for the topics is 3, which requires at least three brokers. Therefore, like the AK example configuration, the replication factor is set to 1 for the three topics and comments are used to describe why that is done and what should be used for production.
This should be merged into 3.3.x, 3.4.x, and master.
> CLIENTS-488 Updated distributed worker config for internal topic creation

- avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java
This ensures that Connect schemas with variable properties don't get
cached and reused simply because they have the same name.
See issue #577
> #577 changed schemaMap to Map<Schema, org.apache.avro.Schema>

- docs/intro.rst
I think it makes more sense to title this page "Introduction". It's a sub-page under "Schema Registry" so I think it's a bit confusing calling it "Schema Registry".
@mageshn @gwenshap
> Schema Registry title -> Introduction

- config/schema-registry.properties
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStore.java
- core/src/test/java/io/confluent/kafka/schemaregistry/ClusterTestHarness.java
- core/src/test/java/io/confluent/kafka/schemaregistry/RestApp.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreSASLTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreSSLAuthTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/SchemaRegistryDedicatedZkTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/StoreUtils.java
- core/src/test/java/io/confluent/kafka/schemaregistry/zookeeper/MasterElectorTest.java
- docs/changelog.rst
- docs/config.rst
- docs/deployment.rst
Replace uses of ZK for getting cluster information and creating topics with the new Java AdminClient API. Refactor a few
other minor uses of ZK so they will not occur unless bootstrap servers are not specified. Add some additional guidance around
configuring the Zookeeper and Kafka bootstrap server settings in a cloud setting.
> CLIENTS-490: Do not require access to Kafka's Zookeeper

- core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/KafkaGroupMasterElector.java
- core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/SchemaRegistryCoordinator.java
- core/src/test/java/io/confluent/kafka/schemaregistry/masterelector/kafka/SchemaRegistryCoordinatorTest.java
These are internal classes, so compatibility is not guaranteed.
> AbstractCoordinator and ConsumerNetworkClient require a LogContext

- avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-converter/src/test/avro/MultiTypeUnionMessage.avsc
- avro-converter/src/test/java/io/confluent/connect/avro/AdditionalAvroDataTest.java
Pick the underlying avro schema from the union based on the name or the type. Also, handle the MapEntry as a special case where the underlying avro schema is an array.
> Handle NPE when there are  multiple non-null union types

- core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/KafkaGroupMasterElector.java
This is due to a change in Apache Kafka for tracking the version and commit id as Kafka Metrics.
> Pass Metrics instance in AppInfoParser call

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryRestApplication.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
There could be a scenario where SR node is deemed as master and fails before it can catch up on the offsets. When this happens we need to inform the coordinator that we are shutting down.
Failed ST that led to the fix : https://confluentinc.atlassian.net/browse/CLIENTS-676
> Shutdown the SchemaRegistry gracefully when there is an exception during startup

- core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/KafkaGroupMasterElector.java
- core/src/test/java/io/confluent/kafka/schemaregistry/masterelector/kafka/SchemaRegistryCoordinatorTest.java
This is due to an upstream change: https://github.com/apache/kafka/commit/7fe88e8bd9acedcb74a4b3e61440f61481b60711. Here is a link to the failing build: https://jenkins.confluent.io/job/test-cp-downstream-builds/1549/console.
> Add maxPollTimeout parameter to ConsumerNetworkClient constructor

- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
This is a rebase of the change in PR https://github.com/confluentinc/schema-registry/pull/418 . Some variables were renamed since the original PR which caused the merge conflict. 
I contacted the original patch author and we agreed that I'll fix the conflict and resend the patch in a new PR. I also left the original author as the git commit author since I only did minor tweaking. According to the original author they've been using this successfully since the original PR was issued.
> Support basic auth credentials embedded in the schema.registry.url

- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
- docs/api.rst
- docs/changelog.rst
- docs/monitoring.rst
PR for #629 & #381 
This PR is to create an endpoint to return the avro schema as a string literal for integration with Hive.  
I ran into an issue where the String being returned was fine with Hive, but the ObjectMapper used in the RestService#sendHttpRequest assumes every payload returned is a json object. The object mapper wasn't able to correctly parse the returned String. Because it couldn't be escaped the json parser interpreted the contents as being a json response, but was using the StringDeserializer, which couldn't handle it. I just wound up with these exceptions:
```
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@65bdd558; …
```
> issue#629: endpoint to return schema literal

- avro-converter/src/main/java/io/confluent/connect/avro/AvroConverter.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDe.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDeConfig.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroSerializer.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/subject/RecordNameStrategy.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/subject/SubjectNameStrategy.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/subject/TopicNameStrategy.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/subject/TopicRecordNameStrategy.java
- avro-serializer/src/test/java/io/confluent/kafka/serializers/KafkaAvroSerializerTest.java
In some situations, an application needs to store events of several different types in the same Kafka topic. In particular, when developing a data model in an Event Sourcing style, you might have several kinds of event that affect the state of an entity. For example, for a customer entity there may be `customerCreated`, `customerAddressChanged`, `customerEnquiryReceived`, `customerInvoicePaid`, etc. events, and the application may require that those events are always read in the same order. Thus, they need to go in the same Kafka partition (to maintain ordering).
The Avro schema registry currently assumes a 1:1 mapping between Kafka topics and Avro schemas, making it difficult to support scenarios like the one above. Users who want several event types in the same topic currently either …
> New (key|value).multi.type option for Avro serialization

- avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-converter/src/test/java/io/confluent/connect/avro/AvroDataTest.java
> #544: Add null check for schema doc while adding the property "connect.enum.doc" for schema conversion of enum types

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryRestApplication.java
When schemaRegistry.init() throws SchemaRegistryException, log the exception before onShutdown() is called.
> Log properly when Exception raised on SchemaRegistryRestApplication

- avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/GenericAvroSerde.java
- avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/SpecificAvroSerde.java
Currently the constructors for `GenericAvroSerde` and `SpecificAvroSerde` that take a `SchemaRegistryClient` argument are package-private. This means they're not readily available to use from unit tests for developers outside of Confluent.
I'm using the `KStreamTestDriver` to implement some property-based tests against our Avro based Kafka Streams topologies. This works great, but I had to add a helper method in the `io.confluent.kafka.streams.serdes.avro` package to use `MockSchemaRegistryClient`. This lets me run the tests without having to start a Schema Registry instance.
Once the internal Kafka test tools are more widely used, I would expect many more developers would wish to be able to use `MockSchemaRegistryClient` in their tests.
> Issue #704 - Make Serde constructors public

- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java
This PR fixes a bug in https://github.com/confluentinc/schema-registry/pull/680. Using a Strategy that derives the Subject name based off the value wouldn't have worked while using includeSchemaAndVersion which is the case for AvroConverter and hence all connectors.
> CC-1511 : Fix for subject strategy when used with new SubjectNameStrategy.

- core/src/test/java/io/confluent/kafka/schemaregistry/RestApp.java
`kafka-streams-examples` makes heavy use of `RestApp` in tests and it would be helpful to have the ability to adjust or specify additional configs.
> MINOR: method for additional configs before starting RestApp

- docs/connect.rst
- docs/serializer-formatter.rst
Added docs for Subject Name Strategy and Basic Auth in Serializers and also cleaned up the example in Serializers to use New Consumer & Deserializer
> Docs for Subject Name Strategy and Basic Auth

- bin/schema-registry-run-class
This fixes a bug where the GC log options were not used in non
daemon mode.
> Improve GC options

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStore.java
If we call "describeTopics" immediately after "createTopics" in admin client, the newly created topic does not show up. But, attempting to recreate the topic will throw a TopicExistsException. Currently, we swallow the exception. This PR changes this behavior to verify the configuration of this topic. 
> CC-1958: Verify configs if createTopic fails because topic already exists

- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
The latter is not available by default in Java 9 or later.
> Use java.util.Base64 instead of javax.xml.bind.DatatypeConverter

- maven-plugin/pom.xml
This fixes the following error which was causing the build to fail:
```
[INFO:2018-05-29 15:57:54,568]: [ERROR] Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:3.2:descriptor (default-descriptor) on project kafka-schema-registry-maven-plugin: Execution default-descriptor of goal org.apache.maven.plugins:maven-plugin-plugin:3.2:descriptor failed: 2925 -> [Help 1]
```
I reproduced this error locally and confirmed it was fixed by updating the maven-plugin-plugin version.
> Update maven-plugin-plugin to fix out of bounds error in build

- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java
Since we add metadata, we need schemas to cached by subject. The recent change took away the by subject cache. This will do that again when we need schema versions. This happens when multiple topics have the same schema in a connector.
> CC-2024 : Fix schema not found issue

- avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-converter/src/test/java/io/confluent/connect/avro/AdditionalAvroDataTest.java
- avro-converter/src/test/java/io/confluent/connect/avro/AvroDataTest.java
- checkstyle/suppressions.xml
Adds support for Cyclic Schemas. Uses the fact that SchemaBuilder also implements Schema. Creates a wrapper CyclicSchema so that we can manage the optionality for different types of cycles. Also, we don't want to change the optionality on actual Struct that we are referring to. Keeps track of cycles and detected cycles while doing toConnectSchema. We want to use the reference only when it's a true cycle.
> CC-2441 : Add Cyclic schema support

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreMessageHandler.java
Ability to tombstone old delete keys if the subject has the same schema registered again. This will help optimize on the storage when users typically do a delete & a register for health check purposes.
The notion of a delete is soft delete in SR today. The key that is stored in the storage has the delete flag. It also has the version.  When you register again with the same schema, while you might get the same id, the old keys still exist in the storage. The motivation of this PR is tombstone the old key so that we can optimize on storage.
> CC-2367 : Tombstone deleted schemakey if the same schema is registered again in the subject

- pom.xml
Not sure if we some changes were made to how we do checkstyle, but it looks like this repo has been looking in the wrong place for its checkstyle suppressions. Updating it so builds pass.
edit: this change broke the path https://github.com/confluentinc/rest-utils/pull/114/files
> CC-2674: Point to the right checkstyle suppression file

- core/src/main/java/io/confluent/kafka/schemaregistry/exceptions/IdGenerationException.java
- core/src/main/java/io/confluent/kafka/schemaregistry/id/IdGenerator.java
- core/src/main/java/io/confluent/kafka/schemaregistry/id/IncrementalIdGenerator.java
- core/src/main/java/io/confluent/kafka/schemaregistry/id/SchemaIdRange.java
- core/src/main/java/io/confluent/kafka/schemaregistry/id/ZookeeperIdGenerator.java
- core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/KafkaGroupMasterElector.java
- core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/zookeeper/ZookeeperMasterElector.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryRestApplication.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/InMemoryCache.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/InMemoryStore.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreMessageHandler.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/LookupCache.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/LookupStore.java
- core/src/test/java/io/confluent/kafka/schemaregistry/ClusterTestHarness.java
- core/src/test/java/io/confluent/kafka/schemaregistry/MasterElectorTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/masterelector/zookeeper/ZookeeperMasterElectorTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/SchemaRegistryKeysTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/StoreUtils.java
1. Moved all data structures used for various lookup under one new interface LookupStore
2. Moved Id generation to its own interface.
This PR is still WIP but wanted to gather some initial feedback on this refactoring.
> Refactor SR to pull lookup datastructure to its own interface and Id Generation to its own interface

- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
There is no implicit timeout on a httpconnection so if the network is disrupted the underlying socket will never close and remain open forever and cause the current thread to stall.
Make static, remove setters, increase timeouts
> RestClient: Add timeout to HttpConnection

- avro-converter/pom.xml
The description somehow got mangled and currently contains an unmatched `<a>` tag; this change fixes that.
> MINOR: Fix description for Avro Converter in kafka-connect-maven-plugin config

- avro-serializer/src/main/java/io/confluent/kafka/formatter/AvroMessageFormatter.java
- avro-serializer/src/test/java/io/confluent/kafka/formatter/AvroMessageFormatterTest.java
- avro-serializer/src/test/java/io/confluent/kafka/formatter/KafkaAvroFormatterTest.java
- checkstyle/suppressions.xml
A new `print.schema.ids=true` property can be used to print out the schema ID for the value’s schema, and the schema ID for the key iff the `print.key=true` is enabled. The `schema.id.separator` property can be used to change the delimiter used between the key/value and the schema ID; this defaults to the tab character (like the existing `key.separator`).
With `print.schema.ids=true`, the output might look similar to:
```
{"k":0} 1   {"f1":"value0"} 2
{"k":1} 1   {"f1":"value1"} 2
{"k":2} 1   {"f1":"value2"} 2
{"k":3} 1   {"f1":"value3"} 2
```
where `1` and `2` are the schema IDs for the keys and values, respectively.
> CC-2769: Ability to optionally include in output the schema ID for key and value

- avro-serializer/src/main/java/io/confluent/kafka/formatter/AvroMessageFormatter.java
Missed this findbugs error due to changes on older branches with less stringent findbugs rules being were pint merged onto branches with more stringent findbugs rules.
> CC-2769: Correct getBytes to not rely on default charset.

- core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/KafkaGroupMasterElector.java
KAFKA-6863 (https://github.com/apache/kafka/pull/4987) altered the `NetworkClient` constructor to require a `ClientDnsLookup` value. This change fixes the usage in Schema Registry causing compilation errors when built against Apache Kafka trunk.
> Adapts NetworkClient usage for KAFKA-6863.

- core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/KafkaGroupMasterElector.java
Added in KIP-235 and KIP-302 which were merged
shortly before the code freeze (i.e. late).
> Pass ClientDnsLookup to NetworkClient and parseAndValidateAddresses

- avro-converter/src/test/java/io/confluent/connect/avro/AvroConverterTest.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDe.java
- avro-serializer/src/test/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializerTest.java
AbstractKafkaAvroDeserializer copies the schema if the subject name strategy
implements the deprecated interface. All the available strategies implement
both the deprecated and new interfaces, and therefore the schema is copied
on every call to toConnectData, which is very expensive. This patch changes
the deprecation check to return true if the strategy does not implement the
new interface.
AbstractKafkaAvroDeserializer always sets the version property when used by
the converter. This resets the hash code inside the avro schema, which is
completely unnecessary in most cases where the property has already been set.
Computing the hash code for the schema can be expensive, so we want to avoid
doing so. To prevent this check whether the version is set before calling
addProp.
> Fix a couple of issues with avro converter performance

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreReaderThread.java
The `KafkaConsumer` constructor instantiates a `ConsumerConfig`, which will properly log at INFO level all of the config properties, so logging them again is unnecessary.
> CC-2156: Changed log message to avoid logging sensitive consumer configs

- client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClientTest.java
Found and fixed a couple of thread-safety issues with `CachedSchemaRegistryClient`.
While I was in there I also added a test to check for thread safety issues and moved away from the 'double lookup pattern' e.g.
```java
if (someMap.contains(key)) {
v = someMap.get(key);
} else {
... do something
}
```
Which can be simplified to a single look up:
```java
v = someMap.get(key);
if (v == null) {
... do something
}
```
> Make CachedSchemaRegistryClient thread-safe

- client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClientTest.java
Already reviewed here: https://github.com/confluentinc/schema-registry/pull/948
> Cherry pick change to make CachedSchemaRegistryClient thread-safe.

- avro-converter/pom.xml
The POM is especially useful for this project since its `<licenses>` element affects archive files generated for use in Confluent Hub. As a result, we should make sure that its licenses are accurate.
> Relicensing: Remove CCL from Avro Converter POM and use only Apache 2.0 license

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStore.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreMessageHandler.java
The tombstone executor would fail during startup if it finds any uncompacted/unprocessed records to be tombstoned since the store wouldn't have been initialized. The fix waits for the store to be initialized.
> CC-3616:wait in tombstone thread until the store is initialized

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryRestApplication.java
Add a Schema Registry config to specify the location of static resources. This is to allow a resource extension to provide a web interface if desired.
> CC-3635 - Add config to specify location of static resources

- avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-converter/src/test/java/io/confluent/connect/avro/AvroDataTest.java
Addresses a regression described in #968.
When reconstructing the Avro schema from a Connect schema, a default value for Connect’s INT16 (short) type did not get transformed into an integer value in the Avro schema (since Avro has no short). This is similar to what AvroData has done previously for INT8 (byte) default values.
A fairly in-depth unit test was added to check the default values for short and other Connect types. During this testing, it was discovered that any `ByteBuffer` default values on Connect schemas were also not handled correctly, since Avro expects `byte[]`. (The code worked properly if the Connect schema was constructed with a `byte[]` as the default value.) Thus, another small change was made to convert `ByteBuffer` instances into the corresponding `byte[]`, which …
> CC-3562: Corrected reconstruction of default value from short and bytes

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStore.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreMessageHandler.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreReaderThread.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/StoreUpdateHandler.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistryTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/StringMessageHandler.java
Here is a short summary of the new changes:
There are two means by which an instance of the Schema Registry (SR) will register new schemas.
1) Via the REST API.
2) Via consuming the _schemas topic, where new schemas are inserted by the master.
For 1), when the schema is new and we generate an ID for it (using either ZK or Kafka), we will now first check that the ID does not exist in our Map that is keyed by ID.
For 2), we now check if there is a different schema for the same ID, and if so, we will tombstone the schema so that the schema with the duplicate ID will eventually be removed during compaction.  If somehow check #1 failed (due to a race condition or multiple masters), then this check will still prevent the schema with the duplicate ID from being registered.
> CC-3732: Prevent SR from registering duplicate IDs

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreMessageHandler.java
Validating schema deletes should be fine, but it's best not to as we only really care about validating newly registered schemas.
> MINOR: do not try to validate schema deletes

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreMessageHandler.java
This check is not strictly necessary, although provides a defensive check should we allow re-registering schemas with the same id.
> MINOR: check that previous schema is not deleted

- avro-converter/src/main/java/io/confluent/connect/avro/AvroConverter.java
- avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-serde/src/test/java/io/confluent/kafka/streams/serdes/avro/AvroUtils.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/GenericContainerWithVersion.java
- avro-serializer/src/test/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializerTest.java
- checkstyle/suppressions.xml
- client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/tools/SchemaRegistryClientPerformance.java
There are 2 reasons why we currently use IdentityHashMap:
1. Performance
2. Avro schemas are used as keys, and we mutate them by adding a version property.  An IdentityHashMap allows for mutable keys.
Regarding #1 (performance), the real gain is by having the client use the same object reference with the CachedSchemaRegistryClient.  If a client does not use the same object reference, then a new Map entry is created, which can eventually lead to "Too many schema objects".  Our clients use the same object reference, but customers often do not.
If we replace the IdentityHashMap with HashMap, clients that use the same object reference will still be performant.  This is because the Avro schema class caches its hashcode, and its equals method will first check for reference equality.  
If we …
> CC-3741 - Remove use of IdentityHashMap

- avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-converter/src/test/java/io/confluent/connect/avro/AvroDataTest.java
Used the logical converters before attempting to morph the default literals used in Connect schemas into the primitive form needed for setting defaults on Avro schemas, and vice versa when morphing the Avro schema defaults to the logical literals needed by Connect schemas. Added to an existing test case to add logical type fields with defaults.
As part of this, changed the parameters for Decimal to only include the `connect.decimal.precision` schema property when it is not the default of 64. This makes it more consistent with repeated conversion between Avro and Connect when the property may not be set unless needed. The `Schema.equals(...)` will fail when if the property is not always set exactly the same; with this change, schemas are exactly equal more of the time.
Also, because of how …
> CC-3803: Corrected support for handling defaults of logical schema types

- checkstyle/suppressions.xml
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/RegisterSchemaRequest.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/RegisterSchemaRequestTest.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectsResource.java
This addresses a compatibility issue introduced by augmenting the SR register API.  This fix will ensure that 5.2+ clients can still interoperate with pre-5.2 SR servers.  The version and ID will only be sent in the REST request if they are not set to null.
> CC-3930: Only send version/id if not null

- avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-converter/src/test/java/io/confluent/connect/avro/AvroConverterTest.java
- avro-converter/src/test/java/io/confluent/connect/avro/AvroDataTest.java
This patch adds support for users of the schema api to explicitly set the
name for map schemas. The avro converter will then use this name for the
map entry type if it needs to serialize the map into a list of entry
records.
> Support explicit names for non-string map schemas.

- docs/api.rst
https://confluentinc.atlassian.net/browse/DOCS-900
Fixed GET response examples per Jira ticket
Fyi, per @rayokota `PUT` uses `compatibility` for both the request and response.
`GET` uses `compatibilityLevel` for the response.
TBD
> DOCS-900 - use compatibilityLevel for GET response examples

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/InMemoryCache.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreMessageHandler.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreReaderThread.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/LookupCache.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreTest.java
After tombstoning extraneous soft-deleted entries, remove said entries
from internal caches.  Also, added several defensive checks against null
entries when looking up schemas.
> CC-4015 : Clean up tombstones from internal caches

- docs/security.rst
- **Jira ticket:** https://confluentinc.atlassian.net/browse/DOCS-1094
- Added requirement for `DescribeConfigs` ACL on `_schema` topic (along with Read/Write access to the topic) to [Schema Registry docs](https://docs.confluent.io/current/schema-registry/docs/security.html#authorizing-access-to-the-schemas-topic)
@rajinisivaram
> DOCS-1094 - Schema Registry docs: Add DescribeConfigs ACL requirement

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/MasterElectorTest.java
Pass the id and version when a slave forward register requests to the master.  Otherwise an error results for register requests that go to the slave during schema migration.
> CC-4056:  Pass id/version when slave forwards register requests

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/InMemoryCache.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreTest.java
When a compaction occurs, a deleted schema will not first be registered. This means that when Schema Registry is restarted, the schema is never registered with the `schemaHashToGuid` cache. This causes an NPE, which then causes the Kafka store reader thread to stop.
> CC-4062: Fix NPE caused after _schemas topic is compacted

- core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/KafkaGroupMasterElector.java
- core/src/test/java/io/confluent/kafka/schemaregistry/masterelector/kafka/SchemaRegistryCoordinatorTest.java
Downstream builds are failing and preventing update of Confluent Kafka.
> MINOR: Update Metadata constructor to match changes in AK

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/InMemoryCache.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaIdAndSubjects.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiModeTest.java
This fixes the following scenario:
1. Register a schema
2. Delete all schemas
3. Set SR to import mode
4. Register the exact same schema as in step 1, but with a different ID.
> CC-4091: Enable reregistration of schema with different ID

- avro-converter/src/main/java/io/confluent/connect/avro/AvroConverter.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDe.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDeConfig.java
The changes here allow request headers for underlying schema registry clients to be configured for the Avro converter, serializer, and deserializer via a `request.header.` prefix.
For example, to specify an `Authorization` header with a value of `Bearer NjksNDIw`, you would use the following configuration:
```properties
request.header.Authorization=Bearer NjksNDIw
```
> MINOR: Add request headers for Avro converter and (de-)serializer

- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Config.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/ClearSubjectKey.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/ConfigKey.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/ConfigValue.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/DeleteSubjectKey.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/ModeKey.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/ModeValue.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/NoopKey.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaKey.java
SR was importing old Jackson 1 packages, which are ignored when using Jackson 2.  This fix imports the new Jackson 2 packages.  For backward compatibility, we retain the field name
"compatibilityLevel".
> CC-3954: Use only Jackson 2 for serialization

- client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java
The `MockSchemaRegistryClient.register(subject, schema)` method will currently incorrectly return `-1` if the schema is already registered, rather than the id at which its registered.
This PR makes the mock return the registered id.
> Do not return -1 from register call in Mock

- avro-converter/src/main/java/io/confluent/connect/avro/AvroConverter.java
Replaces several instances of incorrect string formatting where `String.format(...)` was used as an instance method instead of a static method.
> Fix exception string formatting in Avro converter

- docs/installation/index.rst
Removes CP installation from SR lefthand TOC. This fixes issue with multiple nested headings opening at once, when installation topics are selected.
> DOCS-1440 - Remove CP install from SR lefthand TOC

- core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/SchemaRegistryCoordinator.java
- core/src/test/java/io/confluent/kafka/schemaregistry/masterelector/kafka/SchemaRegistryCoordinatorTest.java
This patch updates SchemaRegistryCoordinator to consume this change made to the AbstractCoordinator interface in Apache Kafka: https://github.com/apache/kafka/commit/8406f3624d8f99b614eb7171b71fae8b0e663dcb
> Update SchemaRegistryCoordinator to use generated protocol classes

- docs/security.rst
Schema Registry inherits the ability to configure basic HTTP authentication from rest-utils, but the configs for this security option are not documented. It'd be nice to have them documented, especially since the KSQL docs mention the ability to configure basic HTTP auth between KSQL and Schema Registry, and what the configs look like for KSQL (see the end of the section [here](https://docs.confluent.io/5.0.0/ksql/docs/installation/server-config/security.html#configuring-ksql-for-secured-sr-long)), and users cannot actually configure this option without docs on the Schema Registry side as well. This PR adds those docs, heavily plagiarized from [the KSQL docs](https://docs.confluent.io/5.1.0/ksql/docs/installation/server-config/security.html#configuring-ksql-for-basic-http-authentication). …
> Add docs for configuring basic HTTP auth

- client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClientTest.java
We added support for generic HTTP headers to our Avro converter in https://github.com/confluentinc/schema-registry/pull/1059. However, the underlying `CachedSchemaRegistryClient` used by the converter only configures those headers if basic auth credentials are also provided.
> CC-4513: Fix HTTP header handling in CachedSchemaRegistryClient

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStore.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreMessageHandler.java
Currently, we tombstone deleted keys whenever we encounter a deleted schema object in the same subject. During startup, this could potentially lead to OOM errors as with each attempt we could end up adding the same tasks over and over again to the executor. Since tombstone is best effort, we could do it at the next event rather than queuing them during init.
> don't tombstone while kafka store is being initialized

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryRestApplication.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ConfigResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ModeResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/RequestHeaderBuilder.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectsResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RequestHeaderBuilderTest.java
This PR adds a new config, `schema.registry.headers.forward`.
When slave SR forwards request to master SR, all headers, defined in the config, will be forwarded along with headers, that are always being forwarded: `Content-Type`, `Accept`, `Authorization`.
> CC-4100: Forward whitelisted headers to master.

- core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/KafkaGroupMasterElector.java
Kafka PRs that necessitate these changes:
- https://github.com/apache/kafka/pull/6318 (changes type signature for `AppInfoParser. registerAppInfo(...)`)
- https://github.com/apache/kafka/pull/6402 (moves `ClientUtils.closeQuietly(...)` to `Utils.closeQuietly(...)`)
> MINOR: Incorporate upstream Kafka changes that affect KafkaGroupMasterElector

- core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/SchemaRegistryCoordinator.java
[This Kafka PR](https://github.com/apache/kafka/pull/6673) changed the constructors for `AbstractCoordinator`; those changes are brought into Schema Registry by this PR.
> MINOR: Fix compilation errors due to changes in KAFKA-8284 (#6673)

- core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/KafkaGroupMasterElector.java
AK changes can be found https://github.com/apache/kafka/commit/6ca899e56d451eef04e81b0f4d88bdb10f3cf4b3 and https://github.com/apache/kafka/pull/6402, which were backported to the AK 2.0 branch.
Similar to #1110 that was applied only to `master`, except this duplicates the `closeQuietly(…)` method to avoid these kinds of changes in the future.
> MINOR: Adjust to upstream changes in AK

- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDeConfig.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroDeserializerConfig.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroSerializerConfig.java
Class loading isolation breaks for connector and the framework by just moving configs to org.apache.kafka package in avro converter.
Reinstating io.confluent config classes only for the avro converter.
> Fix class loading issues for avro converter by reinstating io.confluent config classes

- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDeConfig.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/security/basicauth/BasicAuthCredentialProviderFactory.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/BearerAuthCredentialProvider.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/BearerAuthCredentialProviderFactory.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/StaticTokenCredentialProvider.java
- client/src/main/resources/META-INF/services/io.confluent.kafka.schemaregistry.client.security.bearerauth.BearerAuthCredentialProvider
- client/src/test/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClientTest.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/rest/RestServiceTest.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/BearerAuthCredentialProviderFactoryTest.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/StaticTokenCredentialProviderTest.java
[Jira](https://confluentinc.atlassian.net/browse/CPKAFKA-2963), [one-pager](https://confluentinc.atlassian.net/wiki/spaces/PM/pages/897679748/One+Pager+-+Authentication+in+Schema+Registry+client+and+projects+that+utilize+it)
These changes add a `BearerAuthCredentialProvider` interface that behaves similarly to the `BasicAuthCredentialProvider` interface. It is loaded using the `ServiceLoader` mechanism and can be used to provide bearer token credentials that are then prefaced with `Bearer ` and used for the `Authorization` header in requests made to Schema Registry.
This should be manually tested before merging.
> CPKAFKA-2963: Add BearerAuthCredentialProvider interface

- avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-converter/src/test/java/io/confluent/connect/avro/AvroDataTest.java
The root of logical type loss lies in the old way how `avro-converter` set logical type: it uses a prop named "logicalType", instead of setting directly. Even though apache avro can recognize such prop as the logical type, apache parquet cannot. 
To fix it, I add code to set logical type directly, while keep the old code for back compatibility
> CC-4775: logical type preservation for hdfs connector when output format is parquet

- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDe.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDeConfig.java
- client/src/main/java/io/confluent/kafka/schemaregistry/testutil/MockSchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClientTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/testutil/MockSchemaRegistryTest.java
Removes the obligation to run an actual instance of Schema Registry for tests that use the avro serdes.
Adds an _alternate_ config option `mock.schema.registry.scope` that can be used _instead of_ `schema.registry.url` for testing.
> Add config for mock registry in avro serdes

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/InMemoryCache.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaIdAndSubjects.java
A minor change to use thread-safe data structures to prevent race conditions.
> MINOR: Use thread-safe data structures

- client/src/main/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/BearerAuthCredentialProviderFactory.java
Currently we are maintaining single instance of BasicAuthCredentialProvider per type. This is error-prone, if we have multiple SR clients with multiple users in same jvm.
> CPKAFKA-3239: Create new BasicAuthCredentialProvider for every getBasicicAuthCredentialProvider call

- README.md
- client/pom.xml
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Config.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaString.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/ConfigUpdateRequest.java
- core/generated/swagger-ui/schema-registry-api-spec.yaml
- core/pom.xml
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/CompatibilityResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ConfigResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/RootResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SchemasResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectsResource.java
The strategy is to autogenerate on `mvn compile` which will force our spec to be tied to the actual code. This has been manually tested with a generated go sdk locally and it works.
One open question is how we will keep public documentation up to date. This may involve manually copying the spec to the docs repo, and generating docs from there. This will have similar problem as connector configs: Updates will need to go into the product repo then copied into docs repo
> CC-5036: Use swagger-maven-plugin to generate API spec

- client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java
The implementation of reset is copied from CachedSchemaRegistryClient.
> MINOR: Add missing reset method to mock client

- client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
This is a simple change to move most of the  functionality in `CachedSchemaRegistryClient.configureRestService` into a new method`RestService.configure`. This will make it easier for RestService to be shared by other client
implementations.
> MINOR: refactor configuration of RestService

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreMessageHandler.java
Currently tombstones are causing an NPE in KafkaStoreMessageHandler
> MINOR: fix NPE by ignoring tombstones

- avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java
Currently forceOptional is default as false in toConnectSchema and there's no way to change it. To add more flexibility and minimize exposure of private methods, we add a protected method for configuring the value of forceOptional
> Add protected method for configuring forceOptional 

- core/pom.xml
- core/src/main/java/io/confluent/kafka/schemaregistry/id/ZookeeperIdGenerator.java
- core/src/main/java/io/confluent/kafka/schemaregistry/utils/ZkData.java
- core/src/main/java/io/confluent/kafka/schemaregistry/utils/ZkUtils.java
- core/src/test/java/io/confluent/kafka/schemaregistry/ClusterTestHarness.java
- core/src/test/java/io/confluent/kafka/schemaregistry/masterelector/zookeeper/ZookeeperMasterElectorTest.java
Also:
* Removed the dependency on `common.utils.zookeeper` classes as
it was confusing to use both that and the `ZkUtils` class in this project.
* Added explicit compile Maven dependency on `zookeeper` and `zkclient`
since we refer to them directly in this project.
> Fix createParentPath issue where it was actually creating the child path

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/exceptions/InvalidCompatibilityException.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/exceptions/RestInvalidCompatibilityException.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/exceptions/RestInvalidSchemaException.java
Currently, the invalid compatibility message is not consistent with the API - namely the omission of the three transitive states. (https://docs.confluent.io/current/schema-registry/docs/config.html#avro-compatibility-level). This changeset aims to bridge that gap.
> Invalid compatibility message update to include three transitive states

- core/src/test/java/io/confluent/kafka/schemaregistry/ClusterTestHarness.java
- core/src/test/java/io/confluent/kafka/schemaregistry/RestApp.java
This change gives us more flexibility to set `schemaRegistryPort` outside of `setUp`
> MINOR: Change int to Integer for schemaRegistryPort

- client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
- core/generated/swagger-ui/schema-registry-api-spec.yaml
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SchemasResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaIdAndSubjects.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
Issue: currently there is no direct API available that tells us all the subjects a given schema id is associated with
> API to retrieve all subjects associated with a schema id

- avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/ConfigurationUtils.java
- avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/ReflectionAvroDeserializer.java
- avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/ReflectionAvroSerde.java
- avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/ReflectionAvroSerializer.java
- avro-serde/src/test/java/io/confluent/kafka/example/Widget.java
- avro-serde/src/test/java/io/confluent/kafka/streams/serdes/avro/ReflectionAvroSerdeTest.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDe.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDeConfig.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerializer.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AvroSchemaUtils.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroDeserializer.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroSerializer.java
- avro-serializer/src/test/java/io/confluent/kafka/example/ExtendedWidget.java
- avro-serializer/src/test/java/io/confluent/kafka/example/Widget.java
- avro-serializer/src/test/java/io/confluent/kafka/serializers/KafkaAvroSerializerTest.java
- checkstyle/suppressions.xml
This pull request attempts to address #385, to enable the use of Avro without requiring IDL/JSON/etc the associated code-generation build complexity and multi-project coupling.
Serialization is pretty straightforward, so I've added a configurable boolean flag to `AbstractKafkaAvroSerDe`, and added a boolean parameter to `AvroSchemaUtils.getSchema`.
Deserialization is as bit harder, so I've done some cleanup and refactoring of the existing `AbstractKafkaAvroDeserializer` codebase in order to support the use of reflection.  Current limitations (which require some review and discussion):
* A concrete class (i.e. the class to instantiate and populate with avro record fields) must be supplied to the `ReflectionAvroDeserializer` constructor (and therefore also to the constructor of …
> Support reflection-based avro serialization

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/CompatibilityResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectsResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
Previous method was iterating over each key in linear time to build a set. This one asks the cache directly.
I'm not confident this is acceptable, since I'm not too familiar with our cache invalidation strategy, and I'm not sure this method is allowed to rely on the cache. If it is disallowed, then I'll comment the code to make it clear to the next reader why current strategy is used.
> Use constant time lookup to check subject exists

- core/generated/swagger-ui/schema-registry-api-spec.yaml
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ConfigResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
This adds a `defaultToGlobal` flag for the config API, to default to the global compatibility if the compatibility at the subject level is not set.
> MMA-5160 - Add defaultToGlobal flag for config API

- avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/ReflectionAvroDeserializer.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroDeserializer.java
This is to ensure backward compatibility with existing code.
> MINOR: remove type param on avro deserializer

- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/ServerClusterId.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/rest/ServerClusterIdTest.java
- core/generated/swagger-ui/schema-registry-api-spec.yaml
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryRestApplication.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ServerMetadataResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
This new path `/v1/metadata/id` is added to have a consistent API between other CP components and returns the following information:
```json
{
"id": "",
"scope": {
"kafka-cluster": "_nOhOtWLSkGVXcA6Pc4x3w",
"schema-registry-cluster": "schema-registry"
}
}
```
> Add /v1/metadata/id endpoint to display SR cluster information

- avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-converter/src/test/java/io/confluent/connect/avro/AdditionalAvroDataTest.java
- avro-converter/src/test/java/io/confluent/connect/avro/AvroConverterTest.java
- avro-converter/src/test/java/io/confluent/connect/avro/AvroDataTest.java
- avro-serializer/src/test/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializerTest.java
- avro-serializer/src/test/java/io/confluent/kafka/serializers/KafkaAvroSerializerTest.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/rest/RestServiceTest.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/security/basicauth/SaslBasicAuthCredentialProviderTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/avro/AvroCompatibilityTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RequestHeaderBuilderTest.java
Upgrade to Avro 1.9.1
The main change is that Avro 1.9.x removes use of `codehaus.jackson` in favor of `fasterxml.jackson`.  In addition, the JSON properties of an Avro schema are no longer exposed as instances of `JsonNode` but are instead exposed as typed objects via `ObjectMapper` unmarshalling.
Also, the following Avro fixes caused a couple of unit tests to change:
https://issues.apache.org/jira/browse/AVRO-2143
> DG-42: Upgrade to Avro 1.9.1; fixes #1122

- core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/ClientConfig.java
- core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/KafkaGroupMasterElector.java
Add a config param to allow DNS lookup policy to be configurable.
> DG-128: Allow DNS lookup policy to be configurable

- client/src/main/java/io/confluent/kafka/schemaregistry/client/security/SslFactory.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiSslTest.java
This uses the same default of "TLS" as the rest of the platform.
I verified that without specifying `schema.registry.ssl.protocol`, an NPE results.  I also added a unit test that shows that with the fix, the code works with just the four properties:
schema.registry.ssl.truststore.location
schema.registry.ssl.truststore.password
schema.registry.ssl.keystore.location
schema.registry.ssl.keystore.password
> DG-134: Fix NPE when schema.registry.ssl.protocol not specified

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStore.java
If registering a schema times out, the next registration needs to read to the end of the topic in case the previous registration succeeded.   This is a regression caused by refactoring some code to support per-subject locks.
> DG-148 - Ensure end of topic is read during register

- core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/KafkaGroupMasterElector.java
The signature of the `Metadata.bootstrap(...)` method was recently changed in AK (see [this AK PR](https://github.com/apache/kafka/pull/7682/files#diff-62bba39339405475f71241a182ef9819R212)) on the AK `trunk` branch to remove the 2nd parameter, so the `KafkaGroupMasterElector` needs to change accordingly.
> MINOR: Change KafkaGroupMasterElector to accommodate recent AK Metadata change

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStore.java
As part of refactoring SR, critical regions are not using the same lock.
> DG-149 : Move master lock to KafkaStore

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
Thee wrong timeout unit caused the function getKafkaClusterId quick timeout without waiting for response from broker. It works fine after update timeout unit from microseconds to milliseconds. 
curl  http://localhost:8082/v1/metadata/id
{"scope":{"path":[],"clusters":{"kafka-cluster":"TejPGgMuQy-vIIzAYBA7PA","schema-registry-cluster":"schema-registry"}},"id":""}
> Fixed wrong Timeout unit. Shoukld be MS.

- core/generated/swagger-ui/schema-registry-api-spec.yaml
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/VersionId.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/exceptions/Errors.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/exceptions/RestInvalidVersionException.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/CompatibilityResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ConfigResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ModeResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SchemasResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectsResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
This error message isn't very informative. 
> `io.confluent.rest.exceptions.RestNotFoundException: Schema not found`
Would be more useful to see during serde interaction or other HTTP requests 
1. which schema ID is trying to be found
2. which subject it is trying to be found from
3. which version for that subject.
> Pass up subject & schema/version id errors from where they occur.

- avro-serializer/src/main/java/io/confluent/kafka/formatter/AvroMessageReader.java
Enhance kafka-avro-console-producer with support for String (non-Avro) key serializer #935
> Add key.serializer property to kafka-avro-console-producer (#935)

- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java
Hi,
please consider this PR to be merged upstream. My use case is for Kotlin classes generated from AVRO schemas. Because SpecificDatumReader is very Java specific, it was easier to implement a KotlinDatumReader on top of GenericDatumReader. However to be able to use it with Kafka I need to be able to override getDatumReader(), which is currently a private method. Hence this pull request.
> Make AbstractKafkaAvroDeserializer.getDatumReader() protected

- core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/KafkaGroupMasterElector.java
Updated code as per changes in https://github.com/apache/kafka/pull/7867
> MINOR: Propagate LogContext to channel builder in KafkaGroupMasterElector

- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Schema.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaString.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaTypeConverter.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/RegisterSchemaRequest.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/RegisterSchemaRequestTest.java
This is for backward compatibility of CachedSchemaRegistryClient with older versions of Schema Registry.
> DG-160:  Omit schemaType if specified as AVRO

- avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/ReflectionAvroDeserializer.java
- avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/ReflectionAvroSerde.java
- avro-serde/src/test/java/io/confluent/kafka/streams/serdes/avro/ReflectionAvroSerdeGenericTest.java
- avro-serde/src/test/java/io/confluent/kafka/streams/serdes/avro/ReflectionAvroSerdeSpecificTest.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java
The patch adds dynamic resolution of the Avro schema when Reflection API is used.
It solves one of the limitations of the initial implementation of the feature. The change allows to use the Reflection API deserialization in the following scenarios:
1. ReflectionAvroSerde is defined globally for KStreams
2. the source topic contains messages of various types (as per TopicRecordNameStrategy)
> Reflection serde

- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
- client/src/main/java/io/confluent/kafka/schemaregistry/testutil/MockSchemaRegistry.java
Pass the schema provider to the MockSchemaRegistryClient when using mocks.
> MINOR: pass provider to MockSchemaRegistryClient

- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreTest.java
The problem is that `SSL_ENDPOINT_IDENTIFICATION_ALGORITHM` only applies to server-side. During SSL handshake, the REST client also performs a hostname verification and if the hostnames do not match, the connection fails. I fix this problem by adding an always-true HostnameVerifier when we set up SSL if `SSL_ENDPOINT_IDENTIFICATION_ALGORITHM` is null or empty. Fixes #1247 
Merge into 5.3.x first
> Adds always-true hostname verifier if ssl.endpoint.identification.algorithm is set to null or empty string

- client/src/main/java/io/confluent/kafka/schemaregistry/client/security/basicauth/BasicAuthCredentialProviderFactory.java
Addresses https://github.com/confluentinc/schema-registry/issues/1197
[Jira](https://confluentinc.atlassian.net/browse/CC-7692)
This applies the same fix from https://github.com/confluentinc/schema-registry/pull/1154 but on the `BasicAuthCredentialProviderFactory` instead of the `BearerAuthCredentialProviderFactory`.
> CC-7692 / ISSUE-1197: Fix configuration of basic auth credentials provider

- avro-serializer/src/main/java/io/confluent/kafka/formatter/AvroMessageReader.java
Enables non-avro 8-byte Long and 4-byte Int types for keys using corresponding serializers.
Addresses:
https://github.com/confluentinc/schema-registry/issues/1134
https://issues.apache.org/jira/browse/KAFKA-2526
To enable use cli options like:
--property key.serializer=org.apache.kafka.common.serialization.LongSerializer
-------------------------------------------------------------------------------------------------------
If you find this PR useful, consider supporting it with a $9/mo sponsorship at:
https://github.com/sponsors/rudi-cilibrasi
> Fixes #1134: Add non-AVRO Int and Long key support

- core/generated/swagger-ui/schema-registry-api-spec.yaml
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/exceptions/Errors.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/exceptions/RestIncompatibleSchemaException.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/CompatibilityResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiCompatibilityTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiModeTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTransitiveCompatibilityTest.java
Clean up some references to Avro since we support other schema types.
> MINOR: cleanup references to Avro in errors

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/InMemoryCache.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/LookupCache.java
'schemaValue' can be null in invocations to LookupCache.schemaTombstoned, causing a NPE and taking down the SR. This PR addresses this scenario.
> Handle null schemaValues during schemaTombstoned

- core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/KafkaGroupMasterElector.java
Recent merge of AK -> CCS 5.4 updates the api to not take timestamp.
This change updates the code to do same. The same code is present in
master, so this follows same pattern.
> Update Metadata::bootstrap signature

- checkstyle/suppressions.xml
- client/src/main/java/io/confluent/kafka/schemaregistry/ParsedSchema.java
- core/generated/swagger-ui/schema-registry-api-spec.yaml
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SchemasResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- pom.xml
- protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufData.java
- protobuf-converter/src/test/java/io/confluent/connect/protobuf/ProtobufDataTest.java
- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java
- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/diff/Context.java
- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/diff/FieldSchemaDiff.java
- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/diff/SchemaDiff.java
- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/dynamic/DynamicSchema.java
- protobuf-provider/src/test/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaTest.java
- protobuf-provider/src/test/java/io/confluent/kafka/schemaregistry/protobuf/diff/ResourceLoader.java
- protobuf-provider/src/test/java/io/confluent/kafka/schemaregistry/protobuf/diff/SchemaDiffTest.java
- protobuf-provider/src/test/resources/io/confluent/kafka/schemaregistry/protobuf/diff/NestedTestProto.proto
- protobuf-serializer/src/test/java/io/confluent/kafka/serializers/protobuf/test/NestedTestProto.java
- protobuf-serializer/src/test/proto/NestedTestProto.proto
- Generate map entry messages as nested messages
- Ensure map_entry option is preserved
- Fix compatibility check for generated map entry message
- Support reading base64-encoded FileDescriptorProto
- Expand NestedTestProto example with more Protobuf features
- Add unit tests for empty messages for ProtobufConverter
- Upgrade square wire to 3.0.3
- Add support for /schemas/ids/{id}?format=serialized for Protobuf
> Fixes for map handling in Protobuf plugin

- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
- core/generated/swagger-ui/schema-registry-api-spec.yaml
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SchemasResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
This is to help clients to know which schema types are supported by a particular instance of SR.
> Add API to retrieve supported schema types

- avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/PrimitiveAvroSerde.java
- avro-serde/src/test/java/io/confluent/kafka/streams/serdes/avro/PrimitiveAvroSerdeTest.java
This PR adds support for Avro Serde for primitive Avro values. While it's possible to create the serde (https://stackoverflow.com/questions/51955921/serde-class-for-avro-primitive-type/54667002#54667002), I think it would be a better user experience to provide this out of the box.
This is a port of #1325 for the `5.5.x` branch
> MINOR: Add support for primitive Avro Serde

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/JsonErrorHandler.java
There was a minor API renaming in recent versions of Jetty.
> API update for Jetty 9.4.26.v20200117

- client/src/main/java/io/confluent/kafka/schemaregistry/AbstractSchemaProvider.java
- client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchemaProvider.java
- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchemaProvider.java
- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaProvider.java
The SR may not be able to resolve all references passed to it during a register operation. This PR catches these cases and gracefully fails the op.
> Fix NPE cases in AbstractSchemaProvider.resolveReferences

- avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/PrimitiveAvroSerde.java
From the discussion on this PR #1325, I think it's a good idea to make the java doc more clear.
> MINOR: Improve java doc for types supported.

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java
This fixes a compile error that was created when [KIP-515 (Enable ZK client to use the new TLS supported authentication)](https://cwiki.apache.org/confluence/display/KAFKA/KIP-515%3A+Enable+ZK+client+to+use+the+new+TLS+supported+authentication) changed the name of a method that was not part of the public Kafka clients API.
This PR does not address the fact that Schema Registry will be unable to connect to a TLS-enabled ZooKeeper instance -- that will have to be fixed separately.
> Fix compile error due to KIP-515 (ZK TLS)

- protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufData.java
- protobuf-converter/src/test/java/io/confluent/connect/protobuf/ProtobufDataTest.java
When enum values are converted from Connect back to Protobuf,
they are converted to int32 to maintain binary compatibility.
> Convert Protobuf enum values to String

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java
Before if both ZK and AK are specified in the properties file, we would use ZK for master election.  This is to use AK instead (since ZK master election is being deprecated).
> Use AK for master election if possible

- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
This is to accommodate an upgrade to Jackson 2.10.2
> MINOR: fix error handling with empty err stream

- client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchemaUtils.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaString.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/CompatibilityCheckResponse.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/ConfigUpdateRequest.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/ModeGetResponse.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/ModeUpdateRequest.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/RegisterSchemaRequest.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/RegisterSchemaResponse.java
- client/src/main/java/io/confluent/kafka/schemaregistry/utils/JacksonMapper.java
- core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/SchemaRegistryProtocol.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaRegistryIdentity.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/serialization/SchemaRegistrySerializer.java
- json-schema-serializer/src/main/java/io/confluent/kafka/formatter/json/JsonSchemaMessageFormatter.java
- json-schema-serializer/src/main/java/io/confluent/kafka/formatter/json/JsonSchemaMessageReader.java
- json-serializer/src/main/java/io/confluent/kafka/serializers/KafkaJsonDeserializer.java
- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaUtils.java
- schema-serializer/src/main/java/io/confluent/kafka/formatter/SchemaMessageReader.java
Creating ObjectMapper is expensive - a static singleton (which
is thread-safe) should be used if possible
> Performance: Use singleton ObjectMapper

- schema-serializer/src/main/java/io/confluent/kafka/formatter/SchemaMessageReader.java
This PR allows us to ingest more complex schemas with the SchemaMessageReader; schema strings no longer need to be specified directly, but can be read from file input instead.
> Add schema file input capability to the message reader

- protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufData.java
- protobuf-converter/src/test/java/io/confluent/connect/protobuf/ProtobufDataTest.java
The way `ProtobufData` currently resolves Protobuf enums passes in the enum name and index instead of the enum type and index, which causes it to always resolve to `null` and therefore return the default value. This change passes in the correct enum name instead.
The tests were using the default value, so they weren't catching it.
**NOTE:** I'm not sure how we're supposed to be resolving the scope here. This PR always assumes that the scope is the same as the resolving state, which might not be right.
> fix: enum always resolves to default value

- avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-converter/src/test/java/io/confluent/connect/avro/AvroDataTest.java
fixes: https://github.com/confluentinc/schema-registry/issues/1376
**Changes already reviewed under https://github.com/confluentinc/schema-registry/pull/1377, this is just changing the base to 5.4.x, as requested**
If an Avro schema has a `connect.default` property on a `long` field, e.g.
```json
{
"name": "date_created",
"type": [
{
"type": "long",
"connect.version": 1,
"connect.default": 0,
"connect.name": "io.debezium.time.Timestamp"
},
"null"
],
"default": 0
}
```
Them `AvroData.toConnectSchema` throws:
```
org.apache.kafka.connect.errors.DataException: Invalid type for INT64: class java.lang.Integer
```
This bug was introduced in the upgrade to Avro 1.9.
The cause is that the call to get the value of `connect.default` was switched from `schema.getJsonProp`, which returned a IntNode, …
> fix: `connect.default` on long avro field

- avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-converter/src/test/java/io/confluent/connect/avro/AvroDataTest.java
[Jira](https://confluentinc.atlassian.net/browse/CC-7027)
The changes to the Avro converter logic in https://github.com/confluentinc/schema-registry/pull/1124 cause issues with upstream producers, such as the JDBC connector, that publish data with a scale larger than its precision. Although this technically violates the Avro spec for the logical decimal type (which states that the scale must be between zero and the precision for the schema, inclusive), in practice this hasn't caused issues and has flown under the radar as values for those kinds of schemas have been correctly serialized and deserialized by the Avro converter.
In order to provide a fix for users of the Avro converter that may be affected by this change, I'd like to propose that we fall back on the legacy schema conversion …
> CC-7027: Revert to legacy serialization of Decimal logical type on incompatible scale/precision

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/CompatibilityResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectsResource.java
Logs basic request information during POST and DELETE actions for a smoother support story.
> DG-24: Add more detailed logs during POST and DELETE ops

- config/connect-avro-distributed.properties
This line:
`schema-registry/connect-avro-distributed.properties:status.storage.topic=connect-statuses`
has been renamed as:
`schema-registry/connect-avro-distributed.properties:status.storage.topic=connect-status`
For consistency with the rest of the platform
Customers who are already using the existing config as-is will want to change it back to the old value.
> MINOR: rename connect-statuses in sample config

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaValue.java
Schemas generated with SR 5.5 include a schemaType field, which prevents
SR 5.4 from reading them.  The fix is the same as with the REST APIs,
which is to store the Avro schema without a schemaType field (Protobuf
and JSON Schema will still have this field).  This will allow users to
downgrade from 5.5 to 5.4 and read any Avro schemas generated with 5.5
(of course Protobuf/JSON Schema schemas generated with 5.5 will still
not be able to be read by 5.4).
> DG-321 Omit schemaType field when storing Avro schemas

- schema-serializer/src/main/java/io/confluent/kafka/formatter/SchemaMessageReader.java
If schema validation is enabled via property parse.key, the serializer object will be used before being initialized, causing a NPE:
`java.lang.NullPointerException
at io.confluent.kafka.formatter.SchemaMessageReader.needsKeySchema(SchemaMessageReader.java:189)
at io.confluent.kafka.formatter.SchemaMessageReader.init(SchemaMessageReader.java:118)
at kafka.tools.ConsoleProducer$.main(ConsoleProducer.scala:43)
at kafka.tools.ConsoleProducer.main(ConsoleProducer.scala)`
Moving the order of initialization fixes this.
> DG-323: Fix SchemaMessageReader NPE if parse.key is enabled

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaValue.java
This is a follow up PR to avoid NPE in the equals/hashCode methods.
Currently the equals/hashCode methods are not being used in normal
control flow but may be used in future tests.
> DG-321 Fix NPE in equals method

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
During IMPORT mode, the SchemaKey version may get out of sync with the SchemaValue version in the case that old schemas are no longer available.
> DG-349 Ensure schema key version matches schema value

- client/src/main/java/io/confluent/kafka/schemaregistry/AbstractSchemaProvider.java
- json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java
- json-schema-converter/src/test/java/io/confluent/connect/json/AdditionalJsonSchemaDataTest.java
- json-schema-provider/src/test/resources/diff-schema-examples.json
Previously we were checking if a JSON Schema is a NullSchema by checking against a singleton NullSchema.INSTANCE.  This fails if the NullSchema has additional properties.  This fix checks for a NullSchema using `instanceof`.
> DG-351 Handle Null JSON Schema with properties

- protobuf-converter/pom.xml
This unnecessary dependency is causing slf4j warnings to be emitted to stdout.
> DG-352 Remove unnecessary slf4j dependency

- avro-converter/src/main/java/io/confluent/connect/avro/AvroConverter.java
- avro-serializer/src/main/java/io/confluent/kafka/formatter/AvroMessageReader.java
- checkstyle/suppressions.xml
- json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaConverter.java
- json-schema-serializer/src/main/java/io/confluent/kafka/formatter/json/JsonSchemaMessageReader.java
- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/SchemaRegistryMojo.java
- protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufConverter.java
- protobuf-serializer/src/main/java/io/confluent/kafka/formatter/protobuf/ProtobufMessageReader.java
- schema-serializer/src/main/java/io/confluent/kafka/formatter/SchemaMessageReader.java
This also fixes an issue where request headers were not always
getting passed to the SR client from the converter config.
> DG-358 Ensure schema provider is set in SR clients

- client/src/main/java/io/confluent/kafka/schemaregistry/AbstractSchemaProvider.java
This will also prevent infinite loops in the case of
cyclic references (which most formats reject).
> DG-308 Check the cache of refs before retrieval

- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java
- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchemaUtils.java
- json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/JsonSchemaTest.java
- json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaDeserializer.java
This method is mainly used by the REST Proxy and tests.
The return value is passed to KafkaJsonSchemaSerializer.
By wrapping the schema and payload in an envelope, the
serializer will use the schema from the envelope rather
than trying to generate one based on the JsonNode (which
will be incorrect).
> DG-399 Use envelope in JsonSchemaUtils.toObject

- avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-converter/src/test/java/io/confluent/connect/avro/AvroDataTest.java
Initializes the AvroConverter cycleReferences map in cases where the connect cache is being hit. Without this, repetitive calls to the converter can yield different results.
> Fix cyclic schema references

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java
As it helps to triage the incompatibility.
The incompatible schema is relevant but not enough information to triage the problem as it can be that we are register a right and compatible schema but in the wrong subject 
Closes #1435
> feat: adds subjectName in the exception for incompatible schema 

- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Schema.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaValue.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/SchemaValuesTest.java
The DefaultValue annotation does not properly work while deserializing Schema and SchemaValue objects from JSON. This simple PR addresses the problem.
> Fix null schema type

- README.md
https://confluentinc.atlassian.net/browse/DOCS-1660
See comment thread on the above DOCS Jira for more context. I'll pull this section out of the Docs after it gets added to the README when this PR is merged.
- moved description of "how to build" Schema Registry out of the docs ([here](https://docs.confluent.io/current/schema-registry/develop/development.html)) into the README, similar to how it's done for [KSQL](https://github.com/confluentinc/ksql/blob/master/CONTRIBUTING.md) (on `master` branch)
- added a TOC to the README
**Please review this version, which includes my changes**: [README.md](https://github.com/confluentinc/schema-registry/blob/e9fed95c3273bad6efb7a4f383600b601ddc8b0b/README.md)
> DOCS-1660 Move how to build schema registry into README, out of docs

- core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/SchemaRegistryProtocol.java
- core/src/test/java/io/confluent/kafka/schemaregistry/masterelector/kafka/SchemaRegistryProtocolTest.java
In order to allow for future expansion of the Kafka master election protocol messages, we need to discard unknown properties while deserializing SchemaRegistryProtocol.Assignment JSON objects. Without this, adding a new field in a newer SR version would cause old SR instances to crash.
> Allow unknown properties while deserializing SchemaRegistryProtocol.Assignment

- avro-converter/src/main/java/io/confluent/connect/avro/AvroConverter.java
- avro-data/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-serializer/src/main/java/io/confluent/kafka/formatter/AvroMessageReader.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerializer.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroSerializer.java
- checkstyle/suppressions.xml
During serialization, pass an existing Avro schema instead
of regenerating it from the payload.  This is more efficient,
and also fixes a bug in unions where the schema generated
from the payload no longer reflects the original union.
> DG-436 Pass existing Avro schema instead of regenerating

- avro-serializer/src/main/java/io/confluent/kafka/formatter/AvroMessageReader.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerializer.java
- avro-serializer/src/test/java/io/confluent/kafka/formatter/KafkaAvroFormatterTest.java
- json-schema-serializer/src/main/java/io/confluent/kafka/formatter/json/JsonSchemaMessageReader.java
- json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaSerializer.java
- json-schema-serializer/src/test/java/io/confluent/kafka/formatter/json/KafkaJsonSchemaFormatterTest.java
- protobuf-serializer/src/main/java/io/confluent/kafka/formatter/protobuf/ProtobufMessageReader.java
- protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/AbstractKafkaProtobufSerializer.java
- protobuf-serializer/src/test/java/io/confluent/kafka/formatter/protobuf/KafkaProtobufFormatterTest.java
- schema-serializer/src/main/java/io/confluent/kafka/formatter/SchemaMessageReader.java
- schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
- schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDeConfig.java
This helps to address issues where the object's schema
might have slightly different metadata than the latest
schema that is registered
> Add ability to use latest version during serialization

- pom.xml
- protobuf-provider/src/test/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaTest.java
Upgrade the wire library to get a fix so that defaults are omitted for proto 3.
> DG-527 Omit defaults for proto 3 schemas (fixed in wire)

- core/src/main/java/io/confluent/kafka/schemaregistry/leaderelector/kafka/SchemaRegistryCoordinator.java
- core/src/main/java/io/confluent/kafka/schemaregistry/leaderelector/kafka/SchemaRegistryProtocol.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaRegistryIdentity.java
- core/src/test/java/io/confluent/kafka/schemaregistry/LeaderElectorTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/leaderelector/kafka/SchemaRegistryCoordinatorTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/metrics/NodeCountMetricTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/utils/TestUtils.java
As of right now, we cannot compute the number of nodes in an SR cluster because the nodes do not fully know about each other. This PR adds this information to the SchemaRegistryProtocol, used when Kafka election is enabled on the SR.
> Add node information to SchemaRegistryProtocol

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreMessageHandler.java
Tombstoned metrics should not be accounted for using this metric, remove them for now.
> Fix NPE during tombstone metric update

- core/src/main/java/io/confluent/kafka/schemaregistry/metrics/MetricsContainer.java
The Confluent Telemetry Reporter should only be added to the Metric reporter list if it is explicitly enabled via config option "confluent.telemetry.enabled". This lowers resource usage and avoids error messages on non-telemetry deployments.
> Only add TelemetryReporter if explicitly enabled in config

- core/src/test/java/io/confluent/kafka/schemaregistry/metrics/MetricsTest.java
Recent changes in the Kafka client libraries resulted in many instances where our metrics were not getting exposed under their proper paths. This integration test helps us catch these issues faster.
> Add metric name test

- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerializer.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/SchemaPair.java
- avro-serializer/src/test/java/io/confluent/kafka/serializers/KafkaAvroSerializerTest.java
This is a PR fixing issue #1515 by caching the avro `DatumReader` and `DatumWriter` instances created when using instances of the `AbstractKafkaAvroDeserializer` and `AbstractKafkaAvroDeserializer` classes. Although the issue was only scoped to poor performance when serializing/deserializing `SpecificRecord` instances this PR applies the same caching logic when working with `GenericRecord` since JMH tests show improvements on deserialization there as well.
I have run benchmarks with the `io.confluent.schemaregistry.benchmark.SerdeBenchmark` JMH benchmark, which at the moment only benchmarks generic records. I have benchmarked using a single as well as 40 threads on my machine by running:
```bash
java -jar benchmark/target/benchmarks.jar -bm thrpt -tu s -f 1 -t 1 -wi 10 -i 10 -w 1 -r 1 -p …
```
> #1515 - Cache Avro DatumReader and DatumWriter instances to increase performance

- json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java
- json-schema-converter/src/test/java/io/confluent/connect/json/JsonSchemaDataTest.java
Add lenient processing for numbers in oneof.  
This allows all integral types to be convertible to each other in a oneof, as well as all floating numeric types.
> DG-607 Add lenient processing for numbers in oneof

- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/diff/SchemaDiff.java
- json-schema-provider/src/test/resources/diff-schema-examples.json
Allow changes to id during json schema compat checks.
The initial implementation did not allow such changes, which is overly strict.
> DG-628 Allow changes to id during json schema compat checks

- core/pom.xml
- package-schema-registry/pom.xml
- Confluent repackaged version fixes CVE-2019-17571
- `common/pom.xml` excludes default log4j as a transitive dependency, and the repackaged version must be explicitly added.
Ref: https://github.com/confluentinc/common/pull/270
> SEC-1034: log4j migration to confluent repackaged version

- client/pom.xml
- core/pom.xml
swagger-core brings an outdated version of snakeyaml as a transitive dependency.
> ST-3988: update swagger-core to 1.6.2

- bin/schema-registry-run-class
Add `share/java/confluent-telemetry` to SR's classpath.
This is where we'll install the confluent-metrics jar (as part of packaging) and we need this jar for telemetry to work.
> METRICS-1988: add confluent-telemetry directory to schema-registry-run-class

- schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDeConfig.java
This was accidentally removed during refactoring
for schema provider support.
> DG-774 restore ssl client configs

- client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClientConfig.java
KIP-519 / KAFKA-8890 for 2.6 added an additional
SSL config of Type.CLASS,
which fails when SR clients pass a default of "" when dynamically 
defining SSL configs in the client config.
Instead, use the passed in defaults.
Note:  using a default of null for Type.STRING only works for 6.0
due to changes to the underlying ConfigDef class.
> DG-767 Use passed in defaults for client ssl configs

- json-schema-provider/pom.xml
- pom.xml
- protobuf-converter/pom.xml
- protobuf-provider/pom.xml
Upgrade kotlin-stdlib to 1.4.x due to CVE https://nvd.nist.gov/vuln/detail/CVE-2020-15824
> DG-789 Fix for CVE-2020-15824

- core/pom.xml
- package-schema-registry/pom.xml
This pull request cherry-picks a commit from `master` to add explicit `io.confluent:confluent-log4j` dependency, because we blacklist the (vulnerable) tranistive dependency `log4j:log4j` of `org.slf4j:slf4j-log4j12` explicitly in `common`. `io.confluent:confluent-log4j` is a drop-in replacement of `log4j:log4j` with a fix for the vulnerability.
> SEC-1307: Backport "log4j replacement with confluent repackaged version"

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ConfigResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/CloseableIterator.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/InMemoryCache.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStore.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreMessageHandler.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreReaderThread.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/LookupCache.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/MD5.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaRegistry.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/Store.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/serialization/SchemaRegistrySerializer.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/serialization/Serializer.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/SchemaRegistryKeysTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/StoreUtils.java
- findbugs/findbugs-exclude.xml
Some API cleanup to enable future extensibility
- Ensure LookupCache APIs throw StoreException
- Use CloseableIterator
- Pass serializer to InMemoryCache constructor
- Use thread-safe structures
- Minor optimization for updating subject config
> MINOR: API cleanup

- protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufData.java
- protobuf-converter/src/test/java/io/confluent/connect/protobuf/ProtobufConverterTest.java
Cache ProtobufSchema using name in Converter.
This fixes https://github.com/confluentinc/schema-registry/issues/1584
> DG-800 Cache ProtobufSchema using name in Converter

- client/src/main/java/io/confluent/kafka/schemaregistry/client/security/SslFactory.java
- client/src/main/java/io/confluent/kafka/schemaregistry/tools/SchemaRegistryClientPerformance.java
Fix License for SslFactory.java in the Client library. 
Related issue: https://github.com/confluentinc/schema-registry/issues/1479
> Correct License in Client library

- avro-serializer/src/test/java/io/confluent/kafka/serializers/KafkaAvroSerializerTest.java
- client/src/main/java/io/confluent/kafka/schemaregistry/CompatibilityChecker.java
- client/src/main/java/io/confluent/kafka/schemaregistry/ParsedSchema.java
- client/src/main/java/io/confluent/kafka/schemaregistry/SchemaValidationStrategy.java
- client/src/main/java/io/confluent/kafka/schemaregistry/SchemaValidator.java
- client/src/main/java/io/confluent/kafka/schemaregistry/SchemaValidatorBuilder.java
- client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/CompatibilityCheckResponse.java
- core/generated/swagger-ui/schema-registry-api-spec.yaml
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/CompatibilityResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/avro/AvroCompatibilityTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java
- json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/TestSchemaValidation.java
- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java
- protobuf-provider/src/test/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaTest.java
- schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
- add testCompatibilityVerbose for client and server, update related class methods to return List<String> instead of boolean
Related issue: https://github.com/confluentinc/schema-registry/issues/1551
> Add failing compatibility reason in rest response 

- avro-serializer/pom.xml
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerializer.java
- avro-serializer/src/test/java/io/confluent/kafka/formatter/KafkaAvroFormatterTest.java
- avro-serializer/src/test/resources/log4j.properties
- client/src/main/java/io/confluent/kafka/schemaregistry/testutil/MockSchemaRegistry.java
- pom.xml
- schema-serializer/src/main/java/io/confluent/kafka/formatter/SchemaMessageFormatter.java
- schema-serializer/src/main/java/io/confluent/kafka/formatter/SchemaMessageReader.java
- schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
- schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDeConfig.java
- Fixes #898 SchemaMessageReader (used by classes like
AvroMessageFormatter) no longer hard-codes the subject name format.
Instead, it leverages AbstractKafkaSchemaSerDeConfig's existing logic to
use the configuration properties to determine the subject name strategy
for the value and, if needed, the key. This allows use of the
"kafka-avro-console-producer" tool with  non-default subject name
strategies.
- Added unit test to exercise the logic from AvroMessageReader#init()
which was previously not covered.
- Spread MockSchemaRegistry functionality so it's not just in
AbstractKafkaSchemaSerDe, but can be used in other classes such as
SchemaMessageFormatter for more testability.
- Improved error message when schema not found to include the subject
name that was used.
- Fixed "Unsupported …
> Avro Console producer should support subject name strategy option

- pom.xml
- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/diff/FieldSchemaDiff.java
- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/diff/SchemaDiff.java
- protobuf-provider/src/test/resources/diff-schema-examples.json
Treat removing Protobuf message types as incompatible, since old records may rely on the message that is being removed.
> DG-935 Treat removing Protobuf message types as incompatible

- Jenkinsfile
- avro-converter/pom.xml
- avro-data/pom.xml
- avro-serde/pom.xml
- avro-serializer/pom.xml
- benchmark/pom.xml
- client-console-scripts/pom.xml
- client/pom.xml
- core/pom.xml
- debian/Makefile
- json-schema-converter/pom.xml
- json-schema-provider/pom.xml
- json-schema-serde/pom.xml
- json-schema-serializer/pom.xml
- json-serializer/pom.xml
- maven-plugin/pom.xml
- package-kafka-serde-tools/pom.xml
- package-schema-registry/pom.xml
- pom.xml
- protobuf-converter/pom.xml
- protobuf-provider/pom.xml
- protobuf-serde/pom.xml
- protobuf-serializer/pom.xml
- schema-registry-console-scripts/pom.xml
- schema-serializer/pom.xml
Setting the jenkins config to use nano versioning. No longer need to define upstream repos as we now define downstream repos which will be automated in the future. Removed all of the snapshot versions and replaced with nano versions. Updated all of the dependency versions.
These changes will be merged during phase two of the nano versioning roll out.
> ST-3461: Nano versioning

- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java
- protobuf-provider/src/test/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaTest.java
- protobuf-provider/src/test/resources/io/confluent/kafka/schemaregistry/protobuf/diff/SameMessageName.proto
- protobuf-provider/src/test/resources/io/confluent/kafka/schemaregistry/protobuf/diff/TestProto.proto
- protobuf-provider/src/test/resources/io/confluent/kafka/schemaregistry/protobuf/diff/TestProto2.proto
- protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/AbstractKafkaProtobufDeserializer.java
Handle duplicate message names during deserialization, by using the fully qualified name of the message
> DG-951 Handle duplicate message names during deserialization

- pom.xml
This property was used in repository/url definition.  This causes a problem with resolution of the parent project/pom, since
property-evaluation occurs in Maven after the parent project is resolved.
Same change for `kafka-connect-jdbc`: https://github.com/confluentinc/kafka-connect-jdbc/pull/942
To test, run this isolating Maven build before on `6.0.0-post` branch (fails) then for PR branch (passes):
```
docker run -it --rm --name isolated-build -v "$(pwd):/usr/src/mymaven" -w /usr/src/mymaven maven:3-jdk-8 mvn clean install
```
> Removed property ${confluent.maven.repo}

- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/DownloadSchemaRegistryMojo.java
- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/SchemaRegistryMojo.java
- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/UploadSchemaRegistryMojo.java
Closes #1689
Sets both configuration and CLI option to skip the plugin execution both by Maven config:
```
<configuration>
<skip>true|false</skip>
</configuration>
```
and CLI Option:
`mvn -Dkafka-schema-registry.skip`
> Skip plugin execution by configuration/CLI

- client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClient.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClientTest.java
Hello! I work with Riot Games and we have a use case where we need to poll the schema registry for all the latest schemas.  I found the /schemas route in the API would support this but the functionality didn't exist in the SchemaRegistryClient (or CachedSchemaRegistryClient).
I believe this is the lightest change I could make to surface this functionality.
I went with a functional/streams style where it made sense but if that doesn't fit I'm happy to back out to an imperative style.
> Add getSchemas functionality to the SchemaRegistryClient.

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStore.java
Adds the `kafkastore.topic.skip.validation` option (defaulting to `false` to
preserve current behaviour). This options controls whether
schema-registry performs validation and auto-creation of the schema
topics on boot.
Enabling this option is required in environments where clients do not
have the `DescribeConfigs` or where topic auto creation is not
supported.
For example, this is required in order to run the schema-registry with
Heroku's managed Apache Kafka service (See [Kafka on Heroku ACLs]).
[Kafka on Heroku ACLs]:
https://devcenter.heroku.com/articles/kafka-on-heroku#understanding-acls
Signed-off-by: Christian Gregg <christian@bissy.io>
> Add kafkastore.topic.skip.validation configurations option

- Jenkinsfile
With new nanoVersioning, the build has to download thousands of pom files and causing downstream validation to timeout. Increase the timeout for downstream validation to pass.
> Increase timeout to 3 hrs

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
As mentioned in the ticket, currently in IMPORT mode, user can import compatible but different schema to the same id, and saw a fake success message because the schema is actually not overwrote.  
```
[2021-01-20 14:48:44,145] INFO Registering new schema: subject Kafka-key, version 1, id 100002, type null (io.confluent.kafka.schemaregistry.rest.resources.SubjectVersionsResource:250)
[2021-01-20 14:48:44,146] INFO Wait to catch up until the offset at 4 (io.confluent.kafka.schemaregistry.storage.KafkaStore:305)
[2021-01-20 14:48:44,191] INFO Wait to catch up until the offset at 5 (io.confluent.kafka.schemaregistry.storage.KafkaStore:305)
[2021-01-20 14:48:44,192] ERROR Found a schema with duplicate ID 100002.  This schema will not be registered since a schema already exists with this ID. …
```
> DG-424: prevent import different schema with same id

- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/TestCompatibilitySchemaRegistryMojo.java
Add the verbose option (default is `true`) to SR maven plugin test-compatibility goal, so the error log in compatibility checks will contains incompatible error details. 
An example error log message looks like the following
```
[error] Schema /var/folders/40/0fn6cc292_j051l5849vsgm00000gp/T/TestCompatibilitySchemaRegistryMojoTest5683166487534292171tmp/TestSubject000-Key.avsc is not compatible with subject(TestSubject000-Key) with error [Unable to read schema: 
"string"
using schema:
"int"]
```
> DG-1162: Add verbose option to SR maven plugin test-compatibility goal

- avro-serializer/src/test/java/io/confluent/kafka/serializers/AvroSchemaTest.java
- client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java
Use `SchemaCompatibility` instead of `SchemaValidator` as the latter is less accurate
Fixes #253, fixes #391, fixes #453, fixes #601, fixes #880, fixes #1142
> Fix Avro compat check

- avro-data/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-data/src/test/java/io/confluent/connect/avro/AvroDataTest.java
This PR is largely an update of https://github.com/confluentinc/schema-registry/pull/797 to get it up to date. 
Addresses https://github.com/confluentinc/schema-registry/issues/776.
> Update to avro-data to support fixed type fields inside of a union

- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
- core/generated/swagger-ui/schema-registry-api-spec.yaml
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ConfigResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ModeResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
Done manual test, will update system tests later. 
Example usage:
```
% curl -X GET http://localhost:8081/config
{"compatibilityLevel":"BACKWARD"}%  
% curl -X PUT -H "Content-Type: application/vnd.schemaregistry.v1+json" --data '{"compatibility": "FORWARD"}' http://localhost:8081/config/Kafka-key 
{"compatibility":"FORWARD"}%                                                                                                                                                                  
% curl -X GET http://localhost:8081/config/Kafka-key                                                                                                
{"compatibilityLevel":"FORWARD"}% …
```
> DGS-1328 Add DELETE API for subject config and subject mode

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStore.java
I'm not sure what the policy is for backporting is, but it would be useful to have this feature on the `5.4.x` release series.
Related: #1733
> Backport #1733 to 5.4.x

- core/src/test/java/io/confluent/kafka/schemaregistry/ClusterTestHarness.java
Pass bootstrap servers to RestApp for ClusterTestHarness tests, since ZooKeeper is deprecated and will be removed in the future.
> MINOR: pass bootstrap servers to RestApp

- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/diff/SchemaDiff.java
- json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/diff/SchemaDiffTest.java
- json-schema-provider/src/test/resources/diff-schema-examples.json
Empty schema is backward compatible with everything, according to the spec.
> DGS-1364 Fix compatibility for JSON empty schema

- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java
- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java
The verbose parameter on the schema registry compatibility API returned bad error messages because of a mistake when using String.format.
This should fix the issue.
> Fix String.format in compatibility errorMessages

- pom.xml
This makes sure subprojects use the same version of Guava. 5.5.x has been fixed. This will be applied to [5.0.x to 5.4.x].
> UIF-302: Add Guava declaration in dependency.

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
Add a server-side cache to cache the parsed version of input schema strings.  All existing tests of schema registration and schema lookup go through this cache.
> DGS-1469 Add server-side schema cache

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/ClearSubjectValue.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/ConfigValue.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/DeleteSubjectValue.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreMessageHandler.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/ModeValue.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaRegistryValue.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaValue.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/SchemaValuesTest.java
The offset and timestamp can be used to help with migrating schemas from one SR to another.
Added a unit test.
> DGS-1513 Store offset and timestamp with cached values

- README.md
I found this problem while building the Schema Registry package.
Schema Registry is built in `package-schema-registry/target`, not `package` anymore. Plus, Serde tools is built in `package-kafka-serde-tools/target`.
> Fix documentation on the built package path

- core/pom.xml
Upgrade the io.netty_netty-codec to `4.1.62.Final`, which is specified in https://github.com/confluentinc/rest-utils/blob/6.2.x/pom.xml#L60
> DGS-1557: Upgrade io.netty_netty-codec

- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaUtils.java
- protobuf-provider/src/test/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaTest.java
Ensure enums are emitted after message types in order to maintain a consistent ordering.
Adds a unit test
> DGS-1631 Ensure enums are emitted after message types

- avro-data/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-data/src/main/java/io/confluent/connect/avro/AvroDataConfig.java
- avro-data/src/test/java/io/confluent/connect/avro/AvroDataTest.java
- protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufData.java
- protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufDataConfig.java
- protobuf-converter/src/test/java/io/confluent/connect/protobuf/ProtobufDataTest.java
Add converter flag to enable scrubbing invalid names, for both Avro and Protobuf converters.
Add unit tests.
Fixes #1861
> DGS-1657 Add converter flag to enable scrubbing invalid names

- core/generated/swagger-ui/schema-registry-api-spec.yaml
- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/RegisterSchemaRegistryMojo.java
- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/TestCompatibilitySchemaRegistryMojo.java
- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/UploadSchemaRegistryMojo.java
- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/ValidateSchemaRegistryMojo.java
- maven-plugin/src/test/java/io/confluent/kafka/schemaregistry/maven/RegisterSchemaRegistryMojoTest.java
We allow URL encoded names in XML tags that represent subject names.  However, since `%` is not allowed, we replace it with `_x`.  There is also a new flag to not attempt a URL decoding.
Fixes #1876
> DGS-1664 Allow URL encoded subject names in maven plugin

- maven-plugin/pom.xml
- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/RegisterSchemaRegistryMojo.java
- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/TestCompatibilitySchemaRegistryMojo.java
Backport of https://github.com/confluentinc/schema-registry/pull/1517
Conflicts: Use `com.google.common.base`
maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/RegisterSchemaRegistryMojo.java
maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/TestCompatibilitySchemaRegistryMojo.java
> Upgrade maven-plugin dependencies to 3.6 in 5.4.x (#1517)

- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/diff/CombinedSchemaDiff.java
- json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/JsonSchemaTest.java
The fix is to use a JsonSchema wrapper around the raw schema, which does not cause recursive calls on the referenced schema.
Fixes #1549, fixes #1866
> DGS-49 Fix StackOverFlowException with cyclic JSON Schema

- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/SchemaRegistryMojo.java
The new added `configs` parameter can be used to specify any valid config for the `CachedSchemaRegistryClient`.
**Example usage**
To set up SSL, one can specify the keystore/truststore location by adding the following configuration to the maven plugin
```
<configuration>
<configs>
<schema.registry.ssl.keystore.location>path-to-keystore.jks</schema.registry.ssl.keystore.location>
<schema.registry.ssl.keystore.password>password</schema.registry.ssl.keystore.password>
<schema.registry.ssl.truststore.location>path-to-truststore.jks</schema.registry.ssl.truststore.location> 
<schema.registry.ssl.truststore.password>password</schema.registry.ssl.truststore.password>
</configs>
</configuration>
```
**Testing**
Done manual test
> DGS-1653: Add configs properties for SR Maven Plugin

- client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java
See github issue here: #1643
JIRA ticket: https://confluentinc.atlassian.net/browse/DGS-1734
Fixing deleteSchemaVersion in MockSchemaRegistryClient in order to mimic correct deletion behavior.
> DGS-1734: MockSchemaRegistryClient need to perform a correct deleteSchemaVersion

- client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java
removing redundant check, and delete from schemaCache.
> small fix in deleteSchemaVersion for MockSchemaRegistryClient

- client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java
Addressing the issue mentioned here: #1910
JIRA ticket here: https://confluentinc.atlassian.net/browse/DGS-1737
When two message types within one proto file are registered with MockSchemaRegistryClient, since the client only compares schema strings, the second register will be considered existing in the registry, while it is not (with different descriptors and names). So we're wrapping the ParsedSchema so that when we decide whether the schema exists in the registry, we compare both schema string and the name (in the example of https://github.com/khaelys/spring-kafka-protobuf-issue, the two schemas could be differentiated with name Message1 and Message2).
We're not adding name comparison to ProtobufSchema.equals() because many existing tests still require only comparing schema strings …
> DGS-1737: MockSchemaRegistryClient doesn't generate new schema id with protobuf

- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchemaUtils.java
- json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/KafkaJsonSchemaSerializer.java
- json-schema-serializer/src/test/java/io/confluent/kafka/serializers/json/KafkaJsonSchemaSerializerTest.java
This is to avoid having to use @SchemaInject to change
the types for date/datetime types.
> DGS-1820 Pass ObjectMapper to JSON Schema generator

- protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufData.java
- protobuf-converter/src/test/java/io/confluent/connect/protobuf/ProtobufDataTest.java
The previous PR to scrub names only handled scrubbing names during schema conversion.  This PR handles scrubbing names during data conversion as well.
> DGS-1825 Fix DataException when scrubbing invalid names

- client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java
Use the double-checked locking pattern with ConcurrentHashMap to reduce synchronization blocks.
> DGS-1869 Reduce synchronization in CachedSchemaRegistryClient

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
PR - DGS-1879 Fix
https://confluentinc.atlassian.net/browse/DGS-1879
Changed hardcoded timeout parameter DESCRIBE_CLUSTER_TIMEOUT_MS that defaults to 10000 to initTimeout that takes the value of kafkastore.init.timeout.ms
> DGS-1879 changed timeout parameter

- json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaConverter.java
- protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufConverter.java
- InvalidConfigurationException error message in ProtobufConverter and JsonSchemaConverter said "Failed to access Avro data"
- Corrected it to "Failed to access Protobuf data" and  "Failed to access JSON Schema data" respectively.
> Corrected Typo in ProtobufConverter and JsonSchemaConverter

- pom.xml
`protobuf.version` is now defined in the `common` repo
> Use protobuf.version from common

- avro-data/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-data/src/test/java/io/confluent/connect/avro/AvroDataTest.java
To ensure names for fixed types are properly scrubbed, we compare the result of `unionMemberFieldName(AvroSchema, bool)` with `unionMemberFieldName(ConnectSchema, bool)` instead of `ConnectSchema.name()`.
Also includes a minor renaming and some minor fixes.
> DGS-2018 Ensure fixed names in Avro union are scrubbed

- avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-converter/src/test/avro/ArrayOfRecordsWithDefault.avsc
- avro-converter/src/test/java/io/confluent/connect/avro/AdditionalAvroDataTest.java
I found this issue when testing the sink connector with an avro schema that has an array as one of its fields with default value.
This array field contains a list of RECORD type, I discovered that when setting default value for array item, it was passing the ARRAY as schema type for each array item. This will cause the next recursive call to fail at creating array item as RECORD type using Struct.
The fix is simple, just use valueSchema() instead.
In our company we are still using 5.1.4 release version of this lib, it'd be great to release the fix if this PR is approved.
I've added an issue with more details: https://github.com/confluentinc/schema-registry/issues/2037
> Fix default value for array of records

- client/pom.xml
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/UriBuilder.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/rest/UriBuilderTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
- schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
* Fixes #1930: removing dependencies on jersey-common and jakarta.ws.rs from schema-registry-client.
* Adding simplfied UriBuiler as replacement, with support for basic urlencoding for query
parameters (based on java.net.UrlEncode) and path segments (RFC 3986)
* removing reference to Respone.Family class from javax.ws.rs in module
schema-serializer
Co-authored-by: Robert Yokota <rayokota@gmail.com>
> Fixes #1930: support Jakarta EE 9 by eliminating dependencies on jersey ey-common and jakarta.ws.rs in schema-registry-client. (#1933)

- client/src/main/java/io/confluent/kafka/schemaregistry/annotations/Schema.java
- client/src/main/java/io/confluent/kafka/schemaregistry/annotations/SchemaReference.java
- client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchemaProvider.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaReference.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/ServerClusterId.java
- client/src/main/java/io/confluent/kafka/schemaregistry/utils/BoundedConcurrentHashMap.java
- client/src/main/java/io/confluent/kafka/schemaregistry/utils/EnumRecommender.java
- client/src/main/java/io/confluent/kafka/schemaregistry/utils/JacksonMapper.java
- client/src/main/java/io/confluent/kafka/schemaregistry/utils/QualifiedSubject.java
This is a follow up from https://github.com/confluentinc/schema-registry/issues/2073
> Turn ccl into apache2 for all schema registry client files

- core/pom.xml
This is backport the same change applied to 6.2.x and later of SR.
> Backport Netty version Override change.

- json-schema-serde/src/main/java/io/confluent/kafka/streams/serdes/json/KafkaJsonSchemaSerde.java
- json-schema-serde/src/test/java/io/confluent/kafka/streams/serdes/json/KafkaJsonSchemaSerdeTest.java
- protobuf-serde/src/main/java/io/confluent/kafka/streams/serdes/protobuf/KafkaProtobufSerde.java
Hello,
I recently faced the following issue: 
In order to write a Kafka Streams test with topologytestdriver, I needed to create a ` KafkaJsonSchemaSerde`. 
The "real" production code uses: ` new KafkaJsonSchemaSerde(MyRecord.class)`.
For testing purposes, I need to mock the schemaRegistryClient, there's a constructor for that.
Unfortunately, there's no constructor with 2 parameters: the client, and the class.
This PR addresses this, adding another constructor "for testing only"
Some notes: 
- you can witness the "bug" (kindof) users can face by reverting the change in ` KafkaJsonSchemaSerde`  and running the `shouldLetTheAbilityToDeserializeToASpecificClass` test. The record will be deserialized as an empty map.
- In case people would face the same issue, and/or the issue would not be …
> Allow passing a specific class when creating a KafkaJsonSchemaSerde with a client (in tests)

- pom.xml
- protobuf-converter/pom.xml
- protobuf-provider/pom.xml
- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaUtils.java
- protobuf-provider/src/test/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaTest.java
This PR updates the wire-schema and wire-schema runtime to 4.0.0 to improve the way options with enums are handled by the schema registry when the format is protobuf. Previously they were handled as strings instead of the original type definition. See these PRs for reference:
* https://github.com/square/wire/pull/2019
* https://github.com/square/wire/pull/2148
> feat: Update wire-schema version to 4.0.0

- client/pom.xml
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/UriBuilder.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/rest/UriBuilderTest.java
- schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
We're running into 2.33 and 2.34 jerseey incompatibilities with dropwizard, and saw that jersey-common was removed from schema-regsitry just recently. This is just a cherry-pick of that into 5.5.x branch
https://github.com/confluentinc/schema-registry/pull/2039
> Backport PR2039 to 5.5.x branch

- core/pom.xml
Excludes the log4j2 dependency pulled in by confluent-log4j.
> Exclude log4j2 dependency

- core/src/test/java/io/confluent/kafka/schemaregistry/ClusterTestHarness.java
https://github.com/apache/kafka/pull/11503 renamed `KafkaConfig.advertisedListeners` to `effectiveAdvertisedListeners`.  This patch fixes the resulting compile error in this downstream project.
> Fix compile error from KAFKA-13456 fix: effectiveAdvertisedListeners

- client/src/main/java/io/confluent/kafka/schemaregistry/client/security/SslFactory.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/security/SslFactoryTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiSslTest.java
Resolves #2063
This PR updates the underlying SSL mechanism used by the Schema Registry client so that it too can accept certificates for mTLS authentication in PEM format.
The code provided in this PR is a direct application of the [PEM handling code](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/security/ssl/DefaultSslEngineFactory.java) used in the [Apache Kafka project](https://github.com/apache/kafka) for the purposes of authentication with brokers.
Configuration of mTLS is achieved by passing the following configuration to the `KafkaAvroDeserializer` and `KafkaAvroSerializer`:
```
schema.registry.url=https://...
schema.registry.ssl.truststore.certificates=<Java escaped PEM certs>
schema.registry.ssl.truststore.type=PEM …
```
> Configure Schema Registry Client [m]TLS using PEM

- client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClient.java
Added methods to SchemaRegistryClient Interface to get subjects, versions and metadata for soft deleted schemas as well.
> DGS-2750 Add API to SchemaRegistryClient interface to get deleted subjects and schemas 

- client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
- core/generated/swagger-ui/schema-registry-api-spec.yaml
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ConfigResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
* Added the API Endpoint to delete the global config and revert back to default.
* Added the support for the this new endpoint in RestService.
> DGS-2871 Add API to delete Global-level compatibility setting

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiCompatibilityTest.java
While trying to register an incompatible schema, currently the response doesn't show the reason(s) of incompatibility.
**Example :** 
```
Sample response with current implementation : 
{
"error_code": 409,
"message": "Schema being registered is incompatible with an earlier schema for subject \"test-topic-2-value\""
}
```
```
Sample response with proposed change : 
{
"error_code": 409,
"message": "Schema being registered is incompatible with an earlier schema for subject \"test-topic-2-value\", details: [Incompatibility{type:TYPE_MISMATCH, location:/fields/2/type, message:reader type: DOUBLE not compatible with writer type: STRING, reader:\"double\", writer:\"string\"}]"
}
```
> DGS-2951 Make Register Api's incompatibility error message verbose

- client/src/main/java/io/confluent/kafka/schemaregistry/client/security/SslFactory.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/security/SslFactoryTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiSslTest.java
(This is a cherry pick of https://github.com/confluentinc/schema-registry/pull/2062 to 7.1.x.)
* PEM implementation
* logging
* No password
* Test
* Minor changes to config checks, fixing tests and checkstyle
* Remove apache commons dependency
Co-authored-by: Elliot West <ewest@expediagroup.com>
Co-authored-by: Paul McDermott <pmcdermott@expediagroup.com>
> DGS-3040 Configure Schema Registry Client [m]TLS using PEM (#2062) [skip secret scan] 

- avro-data/src/main/java/io/confluent/connect/avro/AvroData.java
Only cache top-level schemas in the global cache when converting from the Connect Schema in AvroData.
This is to prevent subschemas with the default schema name prefix from getting cached, which may result in `Can't redefine: io.confluent.connect.avro.ConnectDefault`.  Also, some caching of subschemas already occurs using the FromConnectContext.
> DGS-3061 Only cache top-level schemas in AvroData

- core/src/main/java/io/confluent/kafka/schemaregistry/leaderelector/kafka/SchemaRegistryCoordinator.java
Ref: https://github.com/apache/kafka/pull/11688
Todo:
Have a follow-up PR to remove the old method once the AK -> CCS sync is done.
> DGS-3087: Accommodate upstream change in AbstractCoordinator

- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/DownloadSchemaRegistryMojo.java
- maven-plugin/src/test/java/io/confluent/kafka/schemaregistry/maven/DownloadSchemaRegistryMojoTest.java
Objective : To download a specific version associated with a subjectPattern.
To run:
```
mvn io.confluent:kafka-schema-registry-maven-plugin:7.2.0-0:download
```
Parameters to be passed while using this goal :
- schemaRegistryUrls
Type : List<String>
Required = true
- outputDirectory
Type : File
Required = true
- versions
Type : List<String>
Required = true
- subjectPatterns
Type : List<String>
Required = true
> Downloading specific version of schemas capability added

- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/MojoUtils.java
- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/SchemaRegistryMojo.java
- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/SchemaUtils.java
- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/TestLocalCompatibilityMojo.java
- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/UploadSchemaRegistryMojo.java
- maven-plugin/src/test/java/io/confluent/kafka/schemaregistry/maven/TestLocalCompatibilityMojoTest.java
Adding a new goal test-local-compatibility for schema registry maven plugin. 
This goal is used to read schemas from the local file system and test them for compatibility. Both the schema to test and previous schemas are to be provided locally.
To run the plugin:
```
mvn -X io.confluent:kafka-schema-registry-maven-plugin:7.2.0-0:test-local-compatibility
```
Parameters
```java
schemaPath
Type: File
Required: true
```
```java
previousSchemaPaths
Type: File[]
Required: true
```
```java
compatibilityLevel
Type: ENUM
Required: false
default: BACKWARD
```
```java
schemaType
Type: String (one of AVRO (default), JSON, PROTOBUF)
Required: false
default: AVRO
```
> Adding new goal test-local-compatibility for schema registry maven plugin

- core/src/test/java/io/confluent/kafka/schemaregistry/ClusterTestHarness.java
`TestUtils.getBrokerListStrFromServers` is removed in https://github.com/apache/kafka/pull/11790, use `TestUtils.bootstrapServers` instead.
> Minor: Fix ClusterTestHarness due to upstream changes

- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java
- json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/JsonSchemaTest.java
Solves https://confluentinc.atlassian.net/browse/RCCA-6039
> DGS-3133: Compare canonical string instead of jsonNode when comparing JsonSchema

- client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java
- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java
- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java
Only cache record types when checking for cycles.
Ensure hashCode accounts for differing meta (docs/aliases).
Cache hashCode result.
> DGS-3066 Perf optimizations for AvroSchema

- client/pom.xml
- core/pom.xml
- pom.xml
Problem:
swagger-core pulls in vulnerable snakeyaml 1.26.
Solution:
Consolidate swagger versioning and set version of snakeyaml at the first non-vulnerable version (1.27):
```bash
mvn dependency:tree | grep snakeyaml
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.27:compile
[INFO] |  |  |  \- org.yaml:snakeyaml:jar:1.27:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.27:compile
[INFO] |  |  |  \- org.yaml:snakeyaml:jar:1.27:compile
[INFO] |  |  |  \- org.yaml:snakeyaml:jar:1.27:compile
[INFO] |  |  |  \- org.yaml:snakeyaml:jar:1.27:compile
[INFO] |  |  |  |  \- org.yaml:snakeyaml:jar:1.27:compile
[INFO] |  |  |  \- org.yaml:snakeyaml:jar:1.27:compile
```
> CVE: Fix swagger pulling in vulnerable snakeyaml 1.26

- schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
Fix a bug introduced in https://github.com/confluentinc/schema-registry/pull/1933 that maps server error to InvalidConfigurationException.
Address https://github.com/confluentinc/schema-registry/pull/2235
> Minor: Maps 4xx error to InvalidConfigurationException

- Jenkinsfile
Remove the line so that PR will build with JDK11.
> DGS-3535: Remove enforcement of building with JDK8

- json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java
Fixes https://github.com/confluentinc/schema-registry/issues/2249.  Cache the `JsonSchema` rather than the lower level `Schema` to avoid constructor calls to `JsonSchema`.
> DGS-3548 Optimize cache for JSON Schema converter

- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/jackson/Jackson.java
This PR maintains the pre-2.13 behavior for the UnknownSerializer.  It can be changed if and when mbknor-jackson-jsonSchema ever changes it's behavior w.r.t Jackson 2.13
> Fix upgrade to Jackson 2.13

- json-schema-provider/pom.xml
- protobuf-converter/pom.xml
* Bumping version for `kotlin-scripting-compiler-embeddable` to 1.6 in `json-schema-provider`
* Bumping version for `kotlin-stdlib-common` to 1.6 in `protobuf-converter`
Jira Link -> https://confluentinc.atlassian.net/browse/MMA-11803
> MMA-11803: Update kotlin-scripting-compiler-embeddable & kotlin-stdlib-common to Kotlin version 1.6

- client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClientTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiModeTest.java
In some cases, equivalent schemas may have been registered with SR.  This may be due to fixes in the semantics of schema comparison.  Rather than having the CachedSchemaRegistryClient reject such schemas, allow them to be passed through to SR during IMPORT mode.
> DGS-3672 Allow CachedSchemaRegistryClient to register same schema

- pom.xml
This is needed to enforce gson version. Otherewise, it inherits from com.google.protobuf:protobuf-java-util which is 2.8.6.
> APPSEC-1156: Patch Gson to be 2.9.0

- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaRegistryServerVersion.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ServerMetadataResource.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
Adding new `v1/metadata/version` endpoint to expose SR version and commitID.
> DGS-3141 - adding new v1/metadata/version endpoint

- avro-data/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-data/src/main/java/io/confluent/connect/avro/AvroDataConfig.java
- avro-data/src/test/java/io/confluent/connect/avro/AvroDataTest.java
- json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java
- json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaDataConfig.java
- json-schema-converter/src/test/java/io/confluent/connect/json/JsonSchemaDataTest.java
- protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufData.java
- protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufDataConfig.java
- protobuf-converter/src/test/java/io/confluent/connect/protobuf/ProtobufDataTest.java
- schema-converter/src/main/java/io/confluent/connect/schema/AbstractDataConfig.java
Adds a new converter config property `ignore.default.for.nullables` which defaults to `false`.  Fixes #2314 .
> DGS-4134 Add config to ignore default for nullable fields

- protobuf-serializer/src/main/java/io/confluent/kafka/formatter/protobuf/ProtobufMessageReader.java
- protobuf-serializer/src/test/java/io/confluent/kafka/formatter/protobuf/KafkaProtobufFormatterTest.java
- schema-serializer/src/main/java/io/confluent/kafka/formatter/SchemaMessageReader.java
Adds two configs for Protobuf console producer `key.schema.full.name` and `value.schema.full.name`, to be used when the Protobuf schema contains more than one message type.
> DGS-1648 Allow Protobuf msg fullname to be passed for console producer

- core/src/main/java/io/confluent/kafka/schemaregistry/leaderelector/kafka/SchemaRegistryCoordinator.java
- core/src/main/java/io/confluent/kafka/schemaregistry/metrics/MetricsContainer.java
- core/src/main/java/io/confluent/kafka/schemaregistry/metrics/SchemaRegistryMetric.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/filters/RestCallMetricFilter.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreMessageHandler.java
- core/src/test/java/io/confluent/kafka/schemaregistry/metrics/CustomSchemaProviderMetricTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/metrics/MetricsTest.java
There are limitations in `SchemaRegistryMetric` at the moment:
- It maintains a counter but the implementation is not protected against race conditions. Among concurrent calls, the last caller of `sensor.record` overwrites the value, which is not necessarily the latest value of the counter
- It doesn't support other stat types like count, avg, max, etc.
This PR enables `SchemaRegistryMetric` to take a stat type and no longer maintains the internal state (to be deprecated).
> DGS-4303: Support different stat types in SchemaRegistryMetric

- core/src/main/java/io/confluent/kafka/schemaregistry/leaderelector/kafka/SchemaRegistryCoordinator.java
With the upgrade to 7.4.0, there is a change in function `onJoinPrepare` and causing a build failure. Hence, adding new parameter `timer' in the parameters. 
Error:
```java
registry_master/core/src/main/java/io/confluent/kafka/schemaregistry/leaderelector/kafka/SchemaRegistryCoordinator.java:[46,7] io.confluent.kafka.schemaregistry.leaderelector.kafka.SchemaRegistryCoordinator is not abstract and does not override abstract method onJoinPrepare(org.apache.kafka.common.utils.Timer,int,java.lang.String) in org.apache.kafka.clients.consumer.internals.AbstractCoordinator
**06:16:15**  [ERROR] /home/jenkins/workspace/fluentinc_schema-registry_master/core/src/main/java/io/confluent/kafka/schemaregistry/leaderelector/kafka/SchemaRegistryCoordinator.java:[214,3] method does not override or …
```
> Adding timer in onJoinPrepare

- core/src/main/java/io/confluent/kafka/schemaregistry/metrics/SchemaRegistryMetric.java
Follow up on https://github.com/confluentinc/schema-registry/pull/2350 to clean up deprecated methods.
> Remove deprecated methods in SchemaRegistryMetric

- client/pom.xml
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/rest/RestServiceTest.java
- pom.xml
1. Migrate PowerMock to Mockito in RestServiceTest so the project can be built with JDK 17 on PR builders.
2. Added the JDK option of surefire plugin so that EasyMock can be used with JDK 17
ref: https://github.com/confluentinc/secret-registry/pull/70
> Migrate PowerMock to Mockito in RestServiceTest

- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaUtils.java
Backport a change from 7.3.x.
During normalization, only emit syntax if using Protobuf v3
> MINOR backport syntax normalization to 7.0.x

- core/generated/swagger-ui/schema-registry-api-spec.yaml
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/CompatibilityResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ConfigResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ContextsResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ModeResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SchemasResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ServerMetadataResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectsResource.java
Adds operation tags to the HTTP endpoint resources, allowing us to group similar APIs together in the generated documentation (similar to the Data Catalog docs: https://docs.confluent.io/cloud/current/api.html#tag/Entity-(v1)).
> Add OpenAPI operation tags

- json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java
Remove static from JsonSchemaData.toConnectData.  This will allow us to rely on configs in JsonSchemaData in the future.
JsonSchemaData is really an internal helper class and shouldn't be used directly.  It is used by JsonSchemaConverter.toConnectData, which is the primary public API.  If anyone is relying on JsonSchemaData.toConnectData, they will need to replace the static call with `new JsonSchemaData().toConnectData`
> DGS-5243 Remove static from JsonSchemaData.toConnectData

- avro-serializer/src/test/java/io/confluent/kafka/serializers/KafkaAvroSerializerTest.java
- client/src/main/java/io/confluent/kafka/schemaregistry/AbstractSchemaProvider.java
Cycles can be created when passing -1 (latest) for the version of a schema reference.
> DGS-5253 Handle cycles when resolving references

- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/SetCompatibilityMojo.java
We use maven execution in our pipeline as follows:
```
<execution>
<id>register-schema</id>
<phase>install</phase>
<goals>
<goal>register</goal>
<goal>set-compatibility</goal>
</goals>
<configuration>
<skip>${schema.registry.skip.registration}</skip>
</configuration>
</execution>
```
When _schema.registry.skip.registration_ is _true,_ register goal is skipped but set-compatibility still executes. We want to be able to skip it as well.
> Skip set-compatibility goal if skip flag is set

- pom.xml
Not needed after https://github.com/confluentinc/common/pull/485.
> APIF-3122: Unpin Protobuf version.

- core/src/test/java/io/confluent/kafka/schemaregistry/ClusterTestHarness.java
- core/src/test/java/io/confluent/kafka/schemaregistry/SASLClusterTestHarness.java
- core/src/test/java/io/confluent/kafka/schemaregistry/SSLClusterTestHarness.java
- core/src/test/java/io/confluent/kafka/schemaregistry/leaderelector/kafka/SchemaRegistryCoordinatorTest.java
KAFKA-14334 changed a kafka.utils.TestUtils method [by adding a default argument](https://github.com/confluentinc/kafka/commit/dbf5826cd545820652ed6d136727aa80a03f4f54#diff-b8f9f9d1b191457cbdb332a3429f0ad65b50fa4cef5af8562abcfd1f177a2cfeR216-R218) (Scala). Unfortunately this is a breaking change for Java downstream dependencies.
> Fix build breakage caused by KAFKA-14334

- README.md
- pom.xml
During the Q4 2022 CVE review I have realized that schema-registry versions 5.4 - 6.2 import the snakeyaml dependency. This update is to resolve multiple CVEs: CVE-2022-38749, CVE-2022-38750, CVE-2022-38751, CVE-2022-25857
> Update the Snakeyaml dependency to adress multiple CVEs

- client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Config.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/ConfigUpdateRequest.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ConfigResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/ConfigValue.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/InMemoryCache.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/LookupCache.java
Adds the following to the Config entity:
- compatibilityGroup: will be used to group schemas for compatibility checks
- initial/finalMetadata: will be used to override metadata in schemas
- initial/finalRuleSet: will be used to override ruleSets in schemas
> DGS-5514 Enhance config APIs with additional parameters

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/DelegatingIterator.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/InMemoryCache.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiContextTest.java
This supports a subjectPrefix such as `:*:mytopic`, which will correspond to `mytopic` in all contexts
> DGS-5400 Support subjectPrefix containing wildcard context and subject

- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Metadata.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/RuleSet.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/rest/entities/MergeEntitiesTest.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/CompatibilityResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/InMemoryCache.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiCompatibilityTest.java
When registering a schema, the metadata/rules are initially set to the initialMetadata/RuleSet, then the passed in metadata/rules are merged on top of the initial values, then the finalMetadata/RuleSet are merged on top of the value from the previous step.
The compatibilityGroup designates a metadata key whose value is used to group schemas.  For example, if the compatibiltyGroup is `application.version`, then only the schemas with the same metadata value for `application.version` will be checked for compatibility.  This allows you to skip the compatibility check when changing the `application.version`, such as for a major version bump.
> DGS-5514 Implementation for new config parameters

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStore.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfigTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistryTest.java
The PR includes the following changes -
- Support external and internal listeners in SR config. The listener to be used for internal traffic can be specified using the new config `inter.instance.listener.name`. 
- Support specifying separate certs for internal and external listeners.
`schema-registry.properties` can now include named listeners and separate certs for each. For example, `listener.name.internal` specifies the SSL configs to be used for the internal listener.
```
listeners=internal://localhost:1000,external://mydomain.com:2000
listener.protocol.map=internal:https,external:https
listener.name.internal.ssl.key.password=${file:/mnt/sslcerts/jksPassword.txt:jksPassword}
listener.name.internal.ssl.keystore.location=/opt/confluentinc/etc/internal/keystore.jks …
```
> DGS-3254: Support for separate internal and external certs

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryMain.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryRestApplication.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/RestApp.java
Currently leader election is initiated before all resources have been set up. In a multi-node setup, once leader election is completed other pods will start to forward requests to new leader even if the new leader is busy setting up the resources.
This PR moves leader election to be after resources and listeners have been prepared, so when the new node steps up as leader, it is ready to accept and process requests already.
> Initiate leader election after resources have been set up

- avro-serializer/src/test/java/io/confluent/kafka/serializers/KafkaAvroSerializerTest.java
- client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java
- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java
- protobuf-provider/src/test/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaTest.java
Support returning Avro schemas with all references resolved.
This will help non-Java clients to more easily resolve references for Avro.
This only applies to Avro since Protobuf and JSON Schema do not support transforming the schema text by replacing references inline, whereas Avro does.
> DGS-5897 Support return Avro schemas with all refs resolved

- client-encryption-aws/src/main/java/io/confluent/kafka/schemaregistry/encryption/aws/AwsKmsClient.java
- client-encryption-aws/src/test/java/io/confluent/kafka/schemaregistry/encryption/aws/FakeAwsKms.java
- client-encryption-gcp/src/main/java/io/confluent/kafka/schemaregistry/encryption/gcp/GcpKmsClient.java
- client-encryption-gcp/src/test/java/io/confluent/kafka/schemaregistry/encryption/gcp/FakeCloudKms.java
These classes will be removed after Google releases a version of Tink greater than 1.7.0.  For now, ensure correct copyrights
> Fix copyrights

- client/src/main/java/io/confluent/kafka/schemaregistry/SchemaValidatorBuilder.java
Fix to truncate schemas larger than 10K in the API response and log.
> DGS-3076: Skip logging large schemas during schema incompatibility check

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
As reported in the ticket -
> Sometimes the listeners config is set to INTERNAL://0.0.0.0:9999 where the hostname part will not be resolved to the correct host if the follower node tries to talk to leader node. 
This PR reverts back to the original behavior of using the HOST_NAME config for inter instance communication. The scheme, port and ssl config will continue to be picked based on the `inter.instance.listener.name` config, if it is set.
> DGS-6065: Use HOST_NAME config for host even if inter.instance.listener.name is set

- client/pom.xml
This is to make sure all client consumers use the version of snakeyaml from client instead of jackson databind dep.
> DGS-6075 : Add explicit definition of snakeyaml.

- client/src/main/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/oauth/OauthCredentialProvider.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/oauth/OauthCredentialProviderTest.java
This PR makes the Identity pool and logical cluster id as optional to make the open-source experience better.
> DGS-5624  SR Oauth client config : Make Identity pool and logical cluster id as optional

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiContextTest.java
DGS-5400 added ability to pass a subjectPrefix with a wildcard context, but it only returned subjects that had an explicit context.  This fix will cause subjects from the default context to also be returned.
> DGS-6192 Include default ctx when using subjectPrefix w/wildcard ctx

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ConfigResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ModeResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectsResource.java
What
------
1. Changing log.info to log.debug for log statements with redundant information.
Why
--------
1. We are reducing the number of logs by removing redundant logs. For eg,
Requests parameters that can be obtained from the HTTP Log will be moved to debug statement.
For eg, log statement for HTTP Request
```
154.217.101.184 - - [17/Feb/2023:00:01:30 +0000] 
"DELETE /subjects/test-subject?permanent=true HTTP/2.0" 
3200 3 "-" "Go-http-client/2.0" 9 
```
Log statement by resource file: 
```
Deleting subject test-subject
```
The second statement isn’t lending any new information and hence we’ll change to log.debug. 
References
------------
1. Ticket - https://confluentinc.atlassian.net/browse/DGS-5341
> [DGS-6267] - Changing logs to debug in SR

- checkstyle/suppressions.xml
- client-encryption/src/main/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutor.java
- client-encryption/src/test/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutorTest.java
- client/src/main/java/io/confluent/kafka/schemaregistry/rules/FieldRuleExecutor.java
- client/src/main/java/io/confluent/kafka/schemaregistry/rules/RuleContext.java
- findbugs/findbugs-exclude.xml
- schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
Handle field level encryption rules that apply to the same tags.  On encryption the later rules with the same tags should override the earlier ones, whereas on decryption, the earlier rules should override the later ones.
> DGS-6319 Handle field encryption rules that apply to the same tags

- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java
- json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaDeserializer.java
- json-schema-serializer/src/test/java/io/confluent/kafka/serializers/json/KafkaJsonSchemaSerializerTest.java
When using a javaType with a oneOf, look for the javaType on the subschemas instead of the root oneOf.
> DGS-6331 Handle javaType for oneOfs during JSON deserialization

- avro-data/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-data/src/test/java/io/confluent/connect/avro/AvroDataTest.java
This is a continuation of DGS-1595 to ignore invalid defaults in the Avro Converter.
> DGS-6613 Ignore invalid Avro defaults in Avro Converter

- client/src/main/java/io/confluent/kafka/schemaregistry/utils/QualifiedSubject.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/InMemoryCache.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreMessageHandler.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/LookupCache.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiContextTest.java
We ensure the subject name is matched when calling `getSchemaById`.
For calls to `getSchemaById` that don't care about the subject name matching (but only the context), we pass a qualified context with no subject name.
This is a fix to https://github.com/confluentinc/schema-registry/pull/2443
> DGS-6701 Fix getSchemaById to match subject if passed

- pom.xml
Remove SnakeYaml from the dependencyManagement to pull the latest version defined in common. See: https://github.com/confluentinc/common/pull/514
> DGS-6698: Remove SnakeYaml from the dependencyManagement

- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerializer.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroDeserializer.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroSerializer.java
- client/src/main/java/io/confluent/kafka/schemaregistry/rules/DlqAction.java
- client/src/main/java/io/confluent/kafka/schemaregistry/rules/RuleBase.java
- json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaDeserializer.java
- json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaSerializer.java
- json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/KafkaJsonSchemaDeserializer.java
- json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/KafkaJsonSchemaSerializer.java
- protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/AbstractKafkaProtobufDeserializer.java
- protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/AbstractKafkaProtobufSerializer.java
- protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/KafkaProtobufDeserializer.java
- protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/KafkaProtobufSerializer.java
- schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
- schema-serializer/src/main/java/io/confluent/kafka/serializers/WrapperKeyDeserializer.java
- schema-serializer/src/main/java/io/confluent/kafka/serializers/WrapperKeyDeserializerConfig.java
- schema-serializer/src/main/java/io/confluent/kafka/serializers/WrapperKeySerializer.java
- schema-serializer/src/main/java/io/confluent/kafka/serializers/WrapperKeySerializerConfig.java
- Simplify capture of key by removing preOp
- Make rule executors/actions AutoCloseable
- Ensure rule executors/actions are closed, including producer in DlqAction
- Set default configs for producer in DlqAction
- Also add some Wrapper serdes to be used for keys that can capture the key value.
> Enhancements to DlqAction

- client-encryption/src/main/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutor.java
- client/src/main/java/io/confluent/kafka/schemaregistry/rules/FieldRuleExecutor.java
- schema-rules/src/main/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutor.java
- schema-rules/src/main/java/io/confluent/kafka/schemaregistry/rules/cel/CelFieldExecutor.java
- schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutorTest.java
This refactors the handling of duplicate tags for field rule executors so that the CEL_FIELD rule handles
duplicate tags consistently with CSFLE.
> Refactor duplicate tag handling for field rule executors

- avro-data/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-data/src/test/java/io/confluent/connect/avro/AvroDataTest.java
Previous fixes ignored invalid defaults for sink connectors.  This is corresponding behavior for source connectors.
> DGS-6929 Ignore invalid Avro defaults for source connectors

- pom.xml
Update msal4j used in serde to bring in updated json-smart dependency to address security hygiene cleanup of: CVE-2023-1370
commit / branch needs renaming after engineering ticket gets created from https://confluentinc.atlassian.net/browse/CVE-356
> DGS-xxxx: update Msal4j dependency to bring in latest json-smart

- client-encryption/src/test/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutorTest.java
- schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutorTest.java
- schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
Allow rule actions to differ per rule.  Makes handling of both rule executors and rule actions consistent.
> Allow rule actions to differ per rule

- client/src/main/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/StaticTokenCredentialProvider.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/oauth/SaslOauthCredentialProvider.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/StaticTokenCredentialProviderTest.java
Adding lsrc-id and pool-id values in static_token. Also making lsrc-id and pool-id optional in sasl_oauthbearer_inherit.
> Static token provider: adding optional lsrc-id and pool-id

- checkstyle/suppressions.xml
- client/src/main/java/io/confluent/kafka/schemaregistry/CompatibilityChecker.java
- client/src/main/java/io/confluent/kafka/schemaregistry/ParsedSchema.java
- client/src/main/java/io/confluent/kafka/schemaregistry/ParsedSchemaHolder.java
- client/src/main/java/io/confluent/kafka/schemaregistry/SchemaValidator.java
- client/src/main/java/io/confluent/kafka/schemaregistry/SchemaValidatorBuilder.java
- client/src/main/java/io/confluent/kafka/schemaregistry/SimpleParsedSchemaHolder.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/client/LocalSchemaRegistryClient.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/CompatibilityResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SchemasResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/LazyParsedSchemaHolder.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaRegistry.java
- json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/TestSchemaValidation.java
- protobuf-provider/src/test/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaTest.java
Various memory optimizations:
- For compatibility checks, use `List<ParsedSchemaHolder>` instead of `List<ParsedSchema>`.  This is to allow the schema to be parsed lazily.
- For retrieval methods, use `List<SchemaKey>` instead of `List<Schema>` or `List<SchemaValue>`, since keys use less memory
- For the `/schemas` endpoint, add config params for `schema.search.default.limit` and `schema.search.max.limit` to limit number of schemas retrieved in memory
> DGS-7103 Optimize instantiation of lists of schemas

- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
Propagate error messages even if not JSON.  In the past, we would show the JSON parsing error, but discard the original error message.
> DGS-7367 Propagate error messages even if not JSON

- client/src/main/java/io/confluent/kafka/schemaregistry/AbstractSchemaProvider.java
- client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchemaProvider.java
- client/src/main/java/io/confluent/kafka/schemaregistry/utils/QualifiedSubject.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/InMemoryCache.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/utils/TestUtils.java
- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchemaProvider.java
- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaProvider.java
Fix for registering references in non-default context.  We ensure the reference is qualified with the correct context.
Much of this PR is backported from 7.4.x.  The main change is a new call to qualify referenced subjects with the context of their parent schema.
> DGS-7412 Fix for registering references in non-default context

- checkstyle/suppressions.xml
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
Omit the compat check during IMPORT mode.  This avoids situations where Avro throws an AvroRuntimeException, which halts import.
> DGS-7422 Optimization: omit compat check during IMPORT

- client/src/main/java/io/confluent/kafka/schemaregistry/rules/DlqAction.java
- schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutorTest.java
Add auto.flush config for DlqAction
> DGS-7430 Add auto.flush config for DlqAction

- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java
- protobuf-provider/src/test/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaTest.java
The object returned from getMeta can be either a List of key-value pairs of a Map.  Previously the Map case was not handled.
> DGS-7432 Fix ClassCastException when getting params option

- client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClientConfig.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/BearerAuthCredentialProvider.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/CustomBearerAuthCredentialProvider.java
- client/src/main/resources/META-INF/services/io.confluent.kafka.schemaregistry.client.security.bearerauth.BearerAuthCredentialProvider
- client/src/test/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/BearerAuthCredentialProviderFactoryTest.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/CustomBearerAuthCredentialProviderTest.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/Resources/MyFileTokenProvider.java
- schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDeConfig.java
Introducing CustomBearerAuthCredentialProvider to make SR client extensible for custom token provider implementation. 
Users can implement their own concrete Implementation of the BearerAuthCredentialProvider Interface and plug into sr using this provider.
The user would have to give the following configs. 
```
bearer.auth.credentials.source=CUSTOM
bearer.auth.custom.token.provider.class=<Fully Qualified class name of custom Implementation>
bearer.auth.logical.cluster=<lsrc-xxxxx> #optional, needed for Confluent cloud SR
bearer.auth.identity.pool.id=<pood Id> #optional, needed for Confluent cloud SR
```
> DGS-7289 Adding CustomBearerAuthCredentialProvider

- client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClientConfig.java
Cache schemas in client when getting by subject/version.  This will help certain scenarios when retrieving migration rules.
> DGS-7457 Cache schemas in client when getting by subject/version

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/filters/AliasFilter.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/ConfigValue.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiCompatibilityTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/filters/AliasFilterTest.java
Fix some regressions due to changes for DGS-7208 and DGS-7474. Ensure ConfigValue.normalize can be null
Preserve ending slash or lack thereof in AliasFilter
> DGS-7208 DGS-7474 Fix some regressions

- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerializer.java
- checkstyle/suppressions.xml
- client/src/main/java/io/confluent/kafka/schemaregistry/SimpleParsedSchemaHolder.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Config.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Schema.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/RegisterSchemaRequest.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/RegisterSchemaResponse.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClientTest.java
- core/generated/swagger-ui/schema-registry-api-spec.yaml
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/client/LocalSchemaRegistryClient.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiCompatibilityTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiMetadataEncoderTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/json/RestApiTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/protobuf/RestApiTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/utils/TestUtils.java
- json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaSerializer.java
- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/RegisterSchemaRegistryMojo.java
- protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/AbstractKafkaProtobufSerializer.java
- protobuf-serializer/src/test/java/io/confluent/kafka/schemaregistry/protobuf/rest/RestApiSerializerTest.java
- protobuf-types/src/main/java/io/confluent/protobuf/type/Decimal.java
- schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
This augments `RegisterSchemaResponse` with additional info, such as the schema.  If the schema has changed on the server, it is included in the response.
> DGS-7564 When registering, return schema if changed on server

- json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaDeserializer.java
- json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaSerializer.java
The creation of `ObjectMapper`s can be very expensive, can we have them `static` instead?
This profiling came from a Kafka REST instance with Avro messages produce load:
> Use static ObjectMappers

- avro-serializer/src/test/java/io/confluent/kafka/serializers/AvroSchemaTest.java
- client/src/main/java/io/confluent/kafka/schemaregistry/ParsedSchema.java
- client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java
- client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchemaUtils.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaEntity.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaTags.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/TagSchemaRequest.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/TagSchemaRequestTest.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/RuleSetHandler.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiRegisterSchemaTagsTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/protobuf/RestApiTest.java
- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java
- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchemaUtils.java
- json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/JsonSchemaTest.java
- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java
- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaUtils.java
- protobuf-provider/src/test/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaTest.java
- Implement `POST /subjects/{subject}/versions/{version}/tags`, which will register a new schema version with the given tags embedded into the schema string
- some bug fixes in the modifySchemaTags
- made improvement Protobuf SchemaEntity Path 
-  make oneOf fieldName optional
- make the leading dot optional
> DGS-7772: Impl POST /subjects/{subject}/versions/{version}/tags

- bin/schema-registry-stop-service
when instance exists, the script will exit because the $? is 0
> Fix stop service script logic

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistryTest.java
https://confluentinc.atlassian.net/browse/DGS-7797
Customers using a stretched or active-passive deployment of SR clusters need a way to specify port information for inter instance communication between DCs. We're introducing a new config `host.port` specifically for such cases where the inter instance communication happens on external network and cannot use the internal 8081 port. For eg. one common deployment we see is the usage of Openshift Routes where the port is 443.
> DGS-7797: Added host.port to augment host.name

- avro-serializer/src/main/java/io/confluent/kafka/formatter/AvroMessageFormatter.java
- avro-serializer/src/main/java/io/confluent/kafka/formatter/AvroMessageReader.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroDeserializer.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroSerializer.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/BearerAuthCredentialProvider.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryRestApplication.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaRegistry.java
- core/src/main/java/io/confluent/kafka/schemaregistry/tools/SchemaRegistryClientPerformance.java
- core/src/main/java/io/confluent/kafka/schemaregistry/tools/SchemaRegistryPerformance.java
- core/src/test/java/io/confluent/kafka/schemaregistry/RestApp.java
- json-schema-serializer/src/main/java/io/confluent/kafka/formatter/json/JsonSchemaMessageFormatter.java
- json-schema-serializer/src/main/java/io/confluent/kafka/formatter/json/JsonSchemaMessageReader.java
- json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/KafkaJsonSchemaDeserializer.java
- json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/KafkaJsonSchemaSerializer.java
- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/DownloadSchemaRegistryMojo.java
- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/SchemaRegistryMojo.java
- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/UploadSchemaRegistryMojo.java
- protobuf-serializer/src/main/java/io/confluent/kafka/formatter/protobuf/ProtobufMessageFormatter.java
- protobuf-serializer/src/main/java/io/confluent/kafka/formatter/protobuf/ProtobufMessageReader.java
- protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/KafkaProtobufDeserializer.java
- protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/KafkaProtobufSerializer.java
- schema-serializer/src/main/java/io/confluent/kafka/formatter/SchemaMessageDeserializer.java
- schema-serializer/src/main/java/io/confluent/kafka/formatter/SchemaMessageFormatter.java
- schema-serializer/src/main/java/io/confluent/kafka/formatter/SchemaMessageReader.java
- schema-serializer/src/main/java/io/confluent/kafka/formatter/SchemaMessageSerializer.java
- schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
This is a partial fix for the memory leak caused by `MdsBearerAuthProvider`. 
This change does not include the Converters which requires a KIP.
> DGS-7861: make BearerAuthCredentialProvider extend Closeable

- client-encryption/src/main/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutor.java
- dek-registry-client/src/main/java/io/confluent/dekregistry/client/MockDekRegistryClient.java
- dek-registry-client/src/main/java/io/confluent/dekregistry/client/rest/entities/Dek.java
- dek-registry-client/src/main/java/io/confluent/dekregistry/client/rest/entities/Kek.java
- dek-registry/generated/swagger-ui/dek-registry-api-spec.yaml
- dek-registry/src/main/java/io/confluent/dekregistry/storage/DataEncryptionKey.java
- dek-registry/src/main/java/io/confluent/dekregistry/storage/DataEncryptionKeyId.java
- dek-registry/src/main/java/io/confluent/dekregistry/storage/DekRegistry.java
- dek-registry/src/main/java/io/confluent/dekregistry/storage/EncryptionKey.java
- dek-registry/src/main/java/io/confluent/dekregistry/storage/KeyEncryptionKey.java
- dek-registry/src/test/java/io/confluent/dekregistry/web/rest/RestApiTest.java
Add timestamps for kek/dek
Add a version for dek for possible future use during dek rotation
> DGS-7826 DGS-7828 DGS-7830 Add kek/dek timestamp, dek version

- json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaSerializer.java
- json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/KafkaJsonSchemaSerializerConfig.java
- json-schema-serializer/src/test/java/io/confluent/kafka/serializers/json/KafkaJsonSchemaSerializerTest.java
Add a config to allow properties to be omitted during serialization.  Fixes #2732
> DGS-8112 Allow properties to be omitted during serialization

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/filters/ContextFilter.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/filters/ContextFilterTest.java
Simliar to deks, ensure that kek names are prefixed by context by the ContextFilter
> Ensure kek name is prefixed with context

- client/src/main/java/io/confluent/kafka/schemaregistry/ParsedSchema.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Config.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/ConfigUpdateRequest.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/ConfigValue.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java
- json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/JsonSchemaTest.java
- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/ValidateSchemaRegistryMojo.java
- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/derive/schema/DeriveAvroSchema.java
- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/derive/schema/DeriveJsonSchema.java
- maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/derive/schema/DeriveProtobufSchema.java
- maven-plugin/src/test/java/io/confluent/kafka/schemaregistry/maven/derive/schema/DeriveAvroSchemaTest.java
- maven-plugin/src/test/java/io/confluent/kafka/schemaregistry/maven/derive/schema/DeriveJsonSchemaTest.java
- maven-plugin/src/test/java/io/confluent/kafka/schemaregistry/maven/derive/schema/DeriveProtoBufSchemaTest.java
- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java
https://confluentinc.atlassian.net/browse/DGS-7866
Added a new config property to validate fields in Json schema. If `validateFields` is `true` or `null`, we will disallow property names starting with `$`. To allow properties beginning with `$`, users can explicitly set `validateFields` to `false`
> DGS-7866: Disallow properties starting with $ by default in JsonSchema

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiRegisterSchemaTagsTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/protobuf/RestApiTest.java
When using the new tags API, always set the `confluent:version` metadata property even if not passed
> DGS-8323 Always populate version metadata prop for tags API

- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
For verbose compatibility test value of `IsCompatible` is ignored which may produce incorrect results
Issue #2278
> Checking "isCompatible" for all compatibility test responses

- client-encryption/src/main/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutor.java
- client-encryption/src/test/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutorTest.java
- client/src/main/java/io/confluent/kafka/schemaregistry/ParsedSchema.java
- client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java
- client/src/main/java/io/confluent/kafka/schemaregistry/rules/DlqAction.java
- client/src/main/java/io/confluent/kafka/schemaregistry/rules/FieldRuleExecutor.java
- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java
- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java
- schema-rules/src/main/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutor.java
- schema-rules/src/main/java/io/confluent/kafka/schemaregistry/rules/cel/CelFieldExecutor.java
- schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutorTest.java
Add config to preserve source fields during field transforms.  Otherwise with Avro and JSON Schema, the source message may be mutated.
> DGS-8708 Add rule config to preserve source fields

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
The previous code was just calling `getMode()` rather than `getModeInScope()`.  This led to erroneous messages that the mode was not currently in IMPORT mode.
> DGS-8088 Get the mode in scope rather that just for the subject

- client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClientTest.java
When using the KafkaAvroSerializer to publish a new message, if a subject has not been registered yet, the `getIdFromRegistry` call fails with a `404` and a error code `40401` for unknown subject.
The expected behaviour is (I believe) that this failure would be added in the missingSchemaCache.
However, since the error code returned is a `40403`, for unknown schema and not a `40401`, this is not added to the cache and subsequent attempts result in repeated calls to the schema registry.
> Cache missing subjects (and not just missing schemas)

- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java
- client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchemaUtils.java
- schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/jsonata/JsonataExecutorIntegrationTest.java
- schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/jsonata/JsonataExecutorTest.java
If the user specified `avro.use.logical.type.converters=true`, it was only being used by Generic Avro types, and not by Reflect/Specific Avro types.
Fixes https://github.com/confluentinc/schema-registry/issues/2803
> DGS-8901 Ensure logical type config is applied to Reflect/Specific Avro data types

- checkstyle/suppressions.xml
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
Otherwise if the ruleset is modified on a follower node, by the time it gets to the leader, both the ruleSet and rulesToMerge/rulesToRemove may be populated.
> For tags API, only modify ruleset on leader node

- checkstyle/suppressions.xml
- dek-registry/src/main/java/io/confluent/dekregistry/storage/DataEncryptionKey.java
- dek-registry/src/main/java/io/confluent/dekregistry/storage/DekRegistry.java
- dek-registry/src/main/java/io/confluent/dekregistry/storage/KeyEncryptionKey.java
- dek-registry/src/test/java/io/confluent/dekregistry/web/rest/RestApiTest.java
If a kek/dek is created with the exact same args as the original that was deleted, allow it to be undeleted.  This will be used when copying kek/deks during schema linking.
> Allow create kek/dek to act like undelete

- avro-converter/pom.xml
The avro-converter project depends on avro-serializer which depends on guava. For some reason, marking it as a test dependency omits it as a transitive compile dependency.
This fixes issue #2804
> fix packaging of kafka-connect-avro-converter

- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java
This PR improves performance for deeply nested protos with a lot of repeating imports by caching `toDynamicSchema` calls.
For example, if every proto is using a timestamp proto (`google/protobuf/timestamp.proto`) it means that we would be creating a `DynamicSchema` every time we see the `google/protobuf/timestamp.proto` import.
The problem is amplified if a repeated dependency also has nested dependencies.
Adding caching has drastically improved performance of `toDynamicSchema` calls in our org.
> Cache ProtobufSchema.toDynamicSchema calls

- config/schema-registry.properties
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryRestApplication.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryExtensionTest.java
Added a new config `pre.init.resource.extension.class` to ensure that the FIPS resource extension can be injected before Kafka Schema Registry is initialized.
[DGS-9006](https://confluentinc.atlassian.net/browse/DGS-9006)
[DGS-9006]: https://confluentinc.atlassian.net/browse/DGS-9006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DGS-9006: Load FIPS extension before KafkaSchemaRegistry is initialized

- pom.xml
- schema-rules/pom.xml
- schema-rules/src/main/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutor.java
- schema-rules/src/main/java/io/confluent/kafka/schemaregistry/rules/cel/builtin/BuiltinDeclarations.java
- schema-rules/src/main/java/io/confluent/kafka/schemaregistry/rules/cel/builtin/BuiltinLibrary.java
- schema-rules/src/main/java/io/confluent/kafka/schemaregistry/rules/cel/builtin/BuiltinOverload.java
- schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutorTest.java
- schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/cel/builtin/BuiltinLibraryTest.java
Add builtin CEL validation functions
- isEmail
- isHostname
- isIpv4
- isIpv6
- isUri
- isUriRef
- isUuid
These can be used in CEL expressions such as `message.emailField.isEmail()`
> DGS-9031 Add builtin CEL validation functions

- .semaphore/project.yml
- .semaphore/semaphore.yml
- Jenkinsfile
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiSchemaTooLargeTest.java
- service.yml
This PR enables Semaphore in this repo. Few differences between this PR and the existing PR in this repo.
- Semaphore build time limit is set to a 2 hour limit instead of the default 1 hour since the longest builds seem to take around 1 hour 15 minutes.
- Set Semaphore Java version to 11, since building using Java17 fails due to Java version error
- This PR is against 7.0.x which is the earliest branch that the testSchemaTooLarge() is present. Another PR will be created against 6.1.x which does not include the fixing test change.
> DGS 9048: Migrate Repo to Semaphore

- avro-serializer/src/main/java/io/confluent/kafka/formatter/AvroMessageFormatter.java
- json-schema-serializer/src/main/java/io/confluent/kafka/formatter/json/JsonSchemaMessageFormatter.java
- protobuf-serializer/src/main/java/io/confluent/kafka/formatter/protobuf/ProtobufMessageFormatter.java
- schema-serializer/src/main/java/io/confluent/kafka/formatter/SchemaMessageDeserializer.java
- schema-serializer/src/main/java/io/confluent/kafka/formatter/SchemaMessageFormatter.java
In the console consumers, ensure isKey flag is passed when reusing deserializers.
> DGS-9387 Ensure isKey flag is passed when reusing deserializers

- pom.xml
The outdated swagger brings several outdated dependencies. Updating swagger core helps clean up public component
(io.confluent:kafka-schema-registry-client)
> update swagger core

- client/src/main/java/io/confluent/kafka/schemaregistry/rules/DlqAction.java
- schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
Better exception handling in DlqAction.  When DlqAction cannot create a producer, it throws a KafkaException
> DGS-9457 Better exception handling in DlqAction

- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/diff/CombinedSchemaDiff.java
- json-schema-provider/src/test/resources/diff-combined-schema-examples.json
- json-schema-provider/src/test/resources/diff-schema-examples.json
More lenient handling of JSON Schema singleton combined types.  Allows the following schema evolutions to be backward compatible:
- Changing a singleton allOf/anyOf to a oneOf (with possibly more subschemas in the oneOf)
- Changing a singleton anyOf/oneOf to a singleton allOf
> DGS-9520 Better handling of JSON Schema singleton combined types

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryRestApplication.java
In order to enable FIPS in SR, the `enable.fips` config must be set to `true` AND the `init.resource.extension.class` config must contain `io.confluent.kafka.schemaregistry.security.SchemaRegistryFipsResourceExtension`.
If `enable.fips=true` but the FIPS resource extension class is not provided, throw an error.
[Doc comment](https://confluentinc.atlassian.net/wiki/spaces/DG/pages/3167981097/Implementing+FIPS+Compliance+in+Self-Managed+SR?focusedCommentId=3277922874)
> Handle bug where `enable.fips` config is true but FIPS resource extension class is not configured

- avro-data/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-data/src/test/java/io/confluent/connect/avro/AvroDataTest.java
- protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufData.java
- protobuf-converter/src/test/java/io/confluent/connect/protobuf/ProtobufDataTest.java
When scrubbing names, avoid regular expressions at all cost.  Also avoid URL encoding (or really, any memory allocation) when it is not necessary.  This makes a huge difference processing large numbers of records.  Fixes #2929.
> Improve the performance of invalid name scrubbing

- client/src/main/java/io/confluent/kafka/schemaregistry/ParsedSchema.java
fixes: https://github.com/confluentinc/schema-registry/issues/2944
Obviously, there is nothing we can do to "fix" the 7.5.3 release. That's always going to have this breaking change. But it would be nice if this change could be merged and added to 7.5.4 and later minor versions in the pipeline.
Side note, it would probably be useful if the meaning of the new `strict` parameter was included in the javadocs of the `validate(boolean strict)` method.
> Fix breaking change to ParsedSchema.validate method

- client/src/main/java/io/confluent/kafka/schemaregistry/ParsedSchema.java
fixes: https://github.com/confluentinc/schema-registry/issues/2944
Side note, it would probably be useful if the meaning of the new `strict` parameter was included in the javadocs of the `validate(boolean strict)` meethod.
> Fix breaking change ti ParsedSchema.validate method (cherry-pick)

- pom.xml
org.apache.commons:commons-compress:1.22.0, which is brought in by Avro, has known vulnerabilities: https://security.snyk.io/package/maven/org.apache.commons:commons-compress/1.22
> Update commons-compress to 1.25.0

- pom.xml
- protobuf-converter/pom.xml
- protobuf-provider/pom.xml
- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java
wire version 3.6.0 using the older okio version which has CVE.
JIRA: https://confluentinc.atlassian.net/browse/DGS-8893 
Upgrade the wire schema version to 4.9.7 and kotlin to 1.19 because the wire schema >=4.9.0 is not compatible with kotlin 1.16.
> upgrade wire-schema to 4.9.7 from 6.2.x

- pom.xml
Please update azure-identity to match the version used in ce-kafka  to fix CVE-2023-34062
> KSECURITY-2211: update azure-identity to match the version used in ce-kafka

- client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClientConfig.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/oauth/OauthCredentialProvider.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/oauth/OauthCredentialProviderTest.java
Adding client ssl configurations if they are available. 
We need this support the CP use case where we may have IDP with self signed certificates. 
JIRA - https://confluentinc.atlassian.net/browse/CPSEC-75
> Add SSL configurations to OAuth client

- json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java
- json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaDataConfig.java
- json-schema-converter/src/test/java/io/confluent/connect/json/JsonSchemaDataTest.java
- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java
Add a JSON Schema converter config "ignore.modern.dialects" to retain the previous behavior, before support for Draft 2020-12 was added.
> DGS-10203 Add JSON Schema converter config to ignore modern dialects

- json-schema-converter/src/test/java/io/confluent/connect/json/JsonSchemaDataTest.java
- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/schema/SchemaTranslator.java
- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/schema/SchemaUtils.java
- json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/JsonSchemaTest.java
Better handling of multitype JSON schemas (where a type is specified as an array of subtypes) in the context of compatibility checks and Connect converters.
> DGS-10206 Fix handling of multitype JSON schemas for 2020-12

- schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
In case `latest.compatibilty.strict=true` and the schema is not backward compatible, the PR logs the error messages from the call of `isBackwardCompatible()` as well as the two schema versions.
> #3025 log error message with more details in case latest.compatibilty.strict=true and latestVersion is not backward compatible

- json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java
allOfToConnectSchema doesn't have a case for when the combinedSchema is just a plain stringSchema and causes an error to be thrown
> fix: invalid behaviour for stringSchema in allOfToConnectSchema

- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchemaUtils.java
- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/schema/SchemaTranslator.java
- json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/JsonSchemaTest.java
- pom.xml
The JSON Schema 2020-12 library that we use, json-skema, recently added better support for $defs (see [json-sKema: //github taking subschemas defined under $defs into account while resolving dynamic references](https://github.com/erosb/json-sKema/commit/c8c1352e48a45f750e715b590a375a9ff22abe32) ).
> DGS-10369 Add support for $defs for JSON Schema 2020-12

- core/pom.xml
Build is failing because of the change in https://github.com/confluentinc/rest-utils/pull/472.
> Fix build breakage caused by dependency change

- json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java
- json-schema-converter/src/test/java/io/confluent/connect/json/JsonSchemaDataTest.java
Currently when presented with a schema like this:
```json
{
"oneOf": [
{ 
"type": "object", 
"properties": {
"message": {
"type": "object",
"properties": {
"A": {"type": "string"}
}
}
}
},
{ 
"type": "object", 
"properties": {
"message": {
"type": "object",
"properties": {
"B": {"type": "integer"}
}
}
}
}
]
}
```
JsonSchemaConverter will always assume that the first schema is the correct one. Regardless if the message received is:
```json
{
"message": {
"A": "sample string"
}
}
```
or
```json
{
"message": {
"B": 27
}
}
```
And in the second case this will cause an error as field "A" will be in the chosen schema but not present inside the record.
> fix: nested schemas were not considered in matching the correct Json Union schema

- avro-serializer/src/test/java/io/confluent/kafka/serializers/AvroSchemaTest.java
- client/src/main/java/io/confluent/kafka/schemaregistry/ParsedSchema.java
- client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Schema.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaEntity.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaString.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaTags.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SchemasResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiRegisterSchemaTagsTest.java
- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java
- json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/JsonSchemaTest.java
- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java
- protobuf-provider/src/test/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaTest.java
Add a query param, findTags, when retrieving a schema, that will extract schema entities with the given set of tags.  This functionality will be used by the Cloud UI to display the tags in a tree view.
> DGS-10391 Add query param to extract schema entities with given tags

- client/src/main/java/io/confluent/kafka/schemaregistry/utils/QualifiedSubject.java
- client/src/test/java/io/confluent/kafka/schemaregistry/utils/QualifiedSubjectTest.java
`__EMPTY` subject name should be reserved for subjects with empty name. This is for resource-level RBAC
> DGS-10608: Don't allow subjects named __EMPTY

- schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutorTest.java
- schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
The config `rule.executors._default_.onFailure` and `rule.executors._default_.onSuccess` can be set via props
> DGS-10135 Allow rule onFailure/onSuccess to be overridden via props

- debian/Makefile
We are using different directory structure in SemaphoreCI and this leads to failure when building deb because of the check that is present in Makefile. This check is being removed as part of this PR.
> CPBR-1311: Removing /tmp/confluent as the DSTDIR check in Makefile

- pom.xml
The jackson version was recently reverted from `2.16.2` to `2.14.2` to fix kafka build issues by this PR in common repo: https://github.com/confluentinc/common/pull/598. This broke the build in schema-registry in all branches starting at 6.2.x. 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project kafka-json-schema-provider: Compilation failure: Compilation failure:
[ERROR] /Users/srimangaddam/schema-registry/json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/jackson/Jackson.java:[27,42] cannot find symbol
[ERROR]   symbol:   class CacheProvider
[ERROR]   location: package com.fasterxml.jackson.databind.cfg
[ERROR] /Users/srimangaddam/schema-registry/json-schema-provider/src/main/java/io/confluen …
```
> Upgrade jackson package to fix build

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
This is a bugfix for Data Catalog.
The register schema message should go _after_ the tombstones so that Data Catalog can correctly delete the sr_* entities before creating new sr_* entities.
Background: In Atlas, for a unique `qualifiedName` there can be multiple entities in the DELETED state, and one entity in the ACTIVE state. Entities cannot be transitions from DELETED to ACTIVE. This change will make Data Catalog delete the entities before creating new ones.
> DGS-10892: Produce register schema message after tombstones

- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/jackson/Jackson.java
- pom.xml
Reverting Jackson to 2.14.2 (reverting this PR to 6.2.x: https://github.com/confluentinc/schema-registry/pull/3105) and removing the associated changes made to support Jackson 2.16.2(https://github.com/confluentinc/schema-registry/pull/3099/files).
Build is passing on 6.0.x and 6.1.x without this revert (both of those branches are already on Jackson 2.14.2).
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for kafka-schema-registry-parent 6.0.16-SNAPSHOT:
[INFO]
[INFO] kafka-schema-registry-parent ....................... SUCCESS [  1.808 s]
[INFO] kafka-schema-registry-client ....................... SUCCESS [  7.389 s]
[INFO] kafka-json-schema-provider ......................... SUCCESS [  5.032 s]
[INFO] kafka-protobuf-provider …
```
> Revert jackson to 2.14.2

- bin/kafka-avro-console-consumer
- bin/kafka-json-schema-console-consumer
- bin/kafka-protobuf-console-consumer
`ce-kafka` has updated class name https://github.com/confluentinc/ce-kafka/commit/3e055624105874782de99b5c19e10089f9581ec1, need to update it here 
(commit in kafka 7.8.x I assume only needed in master)
causing test failure https://confluent.slack.com/archives/CM6PEBEGM/p1715573662303919
> Fix classname for ConsoleConsumer 

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreMessageHandler.java
What
----
Fix handleDeleteSubject to pass right oldSchemaValue. If right oldValue is not passed it would affect how schema soft delete updates the schema count
References
----------
https://confluentinc.atlassian.net/browse/DGS-10707
> DGS-10707 Fix handleDeleteSubject to pass right oldSchemaValue

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
Call the `kafkaStore` on healthy checks so we can detect any issues with the storage. 
Testing:
- There are integration tests in our Confluent Cloud repos that depend on the `healthy()` method
- We will monitor for performance concerns when deploying to pre-prod environments
> DGS-12288: Call kafkaStore on healthy checks

- json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaDeserializer.java
- json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaSerializer.java
Reverting this change to fix https://github.com/confluentinc/schema-registry/issues/3145
We will possibly need a different change to optimize ObjectMapper creation performance.
> Revert "do not reinstantiate objectmapper as it's expensive (#2686)

- core/src/main/java/io/confluent/kafka/schemaregistry/leaderelector/kafka/KafkaGroupLeaderElector.java
- core/src/main/java/io/confluent/kafka/schemaregistry/metrics/MetricsContainer.java
- [SystemTime is changed visibility](https://github.com/apache/kafka/commit/133f2b0f311ba1fd5a999f477bad38370c1772ca), we should use public interface Time instead
- [NetworkClient public constructor also changed](https://github.com/confluentinc/kafka/commit/dd755b7ea95b3f9c277d9778d6624ab05407cac6), so make change accordingly
> Fix SystemTime that change visibility and compilation issue of KafkaGroupLeaderElector

- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/ExtendedSchema.java
- client/src/main/java/io/confluent/kafka/schemaregistry/utils/QualifiedSubject.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/filters/AliasFilter.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/InMemoryCache.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
Ensure aliases are properly qualified.  If an alias does not specify a context, it should use the context of the corresponding subject.  This is similar to how references behave.
> DGS-11418 Ensure aliases are properly qualified

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStore.java
What
----
Cache checkpoint for cacheInitialized before reader thread starts. Checkpoint could be updated once the reader thread starts. This could result in a race condition where schemas after the checkpoint during startup would be double counted.
References
----------
https://confluentinc.atlassian.net/browse/DGS-10707
> DGS-10707 Cache checkpoint for cacheInitialized before reader thread starts

- core/src/test/java/io/confluent/kafka/schemaregistry/ClusterTestHarness.java
This recent PR seems to have broke schema-registry CP build for 7.8.x: https://github.com/confluentinc/kafka/commit/9be27e715a209a892941bf35e66859d9c39c28c4#diff-cbe6a8b71b05ed22cf09d97591225b588e9fca6caaf95d3b34a43262cfd23aa6L796 by renaming effectiveAdvertisedListeners to effectiveAdvertisedBrokerListeners.
This PR uses the renamed version of the method to fix CP build 7.8.x as per this Slack: https://confluent.slack.com/archives/C07AUS8GRFS/p1719572874287549?thread_ts=1719568628.758559&cid=C07AUS8GRFS
> Fix CP Build on 7.8.0 by switching effectiveAdvertisedListeners to effectiveAdvertisedBrokerListeners

- avro-data/src/main/java/io/confluent/connect/avro/AvroData.java
- avro-data/src/main/java/io/confluent/connect/avro/AvroDataConfig.java
- avro-data/src/test/java/io/confluent/connect/avro/AvroDataTest.java
- json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java
- json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaDataConfig.java
- json-schema-converter/src/test/java/io/confluent/connect/json/JsonSchemaDataTest.java
Flatten singleton unions in the Avro and JSON converters.  This is consistent with how a union of a type and null is flattened to an optional type.
Set `flatten.singleton.unions=false` to keep the old behavior.
> DGS-4287 Flatten singleton unions in Avro/JSON converters

- client-encryption/src/main/java/io/confluent/kafka/schemaregistry/encryption/local/LocalKmsClient.java
- client-encryption/src/main/java/io/confluent/kafka/schemaregistry/encryption/local/LocalKmsDriver.java
- client-encryption/src/test/java/io/confluent/kafka/schemaregistry/encryption/local/LocalFieldEncryptionProperties.java
- dek-registry/src/test/java/io/confluent/dekregistry/testutil/TestKmsClient.java
Remove use of PrimitiveSet as it is removed from Tink 1.13.0.  The OLD_SECRETS property was not documented and should not be used.
> Clean up LocalKmsClient/TestKmsClient

- pom.xml
We can't upgrade to tink 1.14.0 yet as it requires protobuf-java 3.27 and common is on 3.25.1
> Upgrade tink to 1.13.0

- avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/GenericAvroSerde.java
- avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/PrimitiveAvroSerde.java
- avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/ReflectionAvroSerde.java
- avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/SpecificAvroSerde.java
- client-encryption-hcvault/src/main/java/io/confluent/kafka/schemaregistry/encryption/hcvault/HcVaultKmsClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/utils/BoundedConcurrentHashMap.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaIdAndSubjects.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/serialization/Serializer.java
- dek-registry-client/src/main/java/io/confluent/dekregistry/client/MockDekRegistryClientFactory.java
**What**
Annotations are changed to prevent errors. Examples include using the \<code\> tag, removing self-closing tags like \<p/\>, not using \<p\>\</p\> to contain block-level elements.
**Links**
[Ticket](https://confluentinc.atlassian.net/browse/DGS-8554)
**Testing:**
Ran ```mvn javadoc:javadoc```, manually inspected pages to check formatting.
> [DGS-8554] Fix javadoc annotations to have no errors

- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/ExtendedSchema.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiCompatibilityTest.java
When qualifying an alias with the parent context, don't use the subjectPrefix because it may be the context wildcard (:*:).  Instead use the subject obtained from the config as the parent context.
> DGS-11418 Fix alias search when using context wildcard

- client/src/main/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/oauth/OauthCredentialProvider.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/oauth/SaslOauthCredentialProvider.java
Fix compile err https://semaphore.ci.confluent.io/jobs/344348e5-e616-44b0-9be6-30dc40e503a4
New parameter was added to this func in kafka-client 7.8.0, setting to false to maintain behavior (see code)
https://github.com/confluentinc/kafka/commit/cfc7bb90ae40669d6eb284ae1987ce93b14990f4
```
public static final String SASL_OAUTHBEARER_HEADER_URLENCODE_DOC = "The (optional) setting to enable the OAuth client to URL-encode the client_id and client_secret in the authorization header"
+ " in accordance with RFC6749, see <a href=\"https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1\">here</a> for more details. The default value is set to 'false' for backward compatibility";
```
> Add missing parameter to HttpAccessTokenRetriever

- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
Our schema registry is behind a load balancer that, occasionally returns a "504 Gateway timeout".
The schema registry client does handle this error correctly, however the error message is misleading.
```
Unrecognized token 'Gateway': was expecting (JSON String, Number (or 'NaN'/'+INF'/'-INF'), Array, Object or token 'null', 'true' or 'false')
at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 9]; error code: 50005
at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:314)
at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:384)
at io.confluent.kafka.schemaregistry.client.rest.RestService.getVersion(RestService.java:911)
at …
```
> Less ambiguous error message when unable to parse body from schema registry

- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
- schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
Convert 429 to a retriable exception. Also convert some other status codes to retriable exceptions
Fixes https://github.com/confluentinc/schema-registry/issues/902 and https://github.com/confluentinc/schema-registry/issues/1635
Also, this PR removes some dead code which was never getting called, as the error code is of the form 40400
```
if (e.getErrorCode() / 100 == 4 /* Client Error */) {
return new InvalidConfigurationException(e.getMessage());
}
```
> DGS-15318 Convert 429 to a retriable exception (#8)

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ConfigResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ModeResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SchemasResource.java
We want to track latency for all SR APIs, this PR adds performance metrics annotation for APIs that don't have them right now. Recreated the approved PR from here: https://github.com/confluentinc/schema-registry/pull/3223 but added the missing imports
> Add performance metric to all SR APIs

- json-schema-converter/src/test/java/io/confluent/connect/json/JsonSchemaDataTest.java
- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/diff/SchemaDiff.java
- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/schema/CombinedSchemaExt.java
- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/schema/SchemaTranslator.java
- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/schema/SchemaUtils.java
Synthetic anyOf's can generate an exception when calling toString(). Instead of using the built-in synthetic flag, use an explicit generated flag.
> DGS-16209 Fix error using synthetic anyOf (#25)

- client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java
- core/src/test/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClientTest.java
* DGS-16357 Include default ctx in mock getContexts()
* Use distinct
* Fix checkstyle
> DGS-16357 Include default ctx in mock getContexts() (#33)

- .semaphore/semaphore.yml
This PR adds cp jar build task invocation for PR builds to make sure downstream components don't break with the PR changes.
> CPBR-1680: adding cp jar build CI gating block (#38)

- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java
- json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/JsonSchemaTest.java
* Scrub refs in arrays when searching for inline tags
* Minor refactor
> DGS-17561 Scrub refs in arrays when searching for inline tags (#59)

- schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
Handle 401 and 403 errors appropriately. Customer had a hard time triaging the error due to this. The following was the update from the customer:
```
Root cause:
Existing Schema Registry Key was deleted on our side (likely when converting from local user accounts to SSO, still TBD). 
This caused our applications to start failing with an inscrutable exception. 
org.apache.kafka.common.errors.InvalidConfigurationException: Unauthorized; error code: 401
This would have bene much quicker to diagnose except the real exception which points directly at a Schema Registry issue was obfuscated by confluent's code.
[This code](https://github.com/confluentinc/schema-registry/blob/master/client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java#L574) throws an …
```
> DGS-16412: Handle 401/403 errors appropriately

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/protobuf/RestApiTest.java
When looking up a schema, if the schema being passed does not have a confluent:version metadata property, we will now still match it to another schema that is identical except for having such a property. This facilitates use cases such as schema [auto-registration](https://confluentinc.atlassian.net/browse/AUTO-registration), which do not pass the confluent:version metadata property.
> DGS-18795 Allow SR to ignore confluent:version when matching schemas

- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerializer.java
- json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaDeserializer.java
- json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaSerializer.java
- protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/AbstractKafkaProtobufDeserializer.java
- protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/AbstractKafkaProtobufSerializer.java
- schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
Minor optimization to reduce schema ID lookups.  The ID is now cached from the first request to avoid having to do a second request.
> DGS-18880 Minor optimization to reduce schema ID lookups

- avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroDecoder.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreReaderThread.java
- core/src/test/java/io/confluent/kafka/schemaregistry/SASLClusterTestHarness.java
- core/src/test/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClientTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClientTest.java
- json-serializer/src/main/java/io/confluent/kafka/serializers/KafkaJsonDecoder.java
- schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutorIntegrationTest.java
- schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/jsonata/JsonataExecutorIntegrationTest.java
Decoder class is moved to new package in
https://github.com/confluentinc/kafka/commit/4d04eb83ea2cf67484d81e30603e976f63616428
`Consumer.poll(long timeoutMs)` is also deprecated in https://github.com/apache/kafka/commit/284a3db28aa5f76844f1b1e696d36d88b161c090
This fixes the issues accordingly.
> Fix issues relating deprecated interfaces in upstream kafka

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/protobuf/RestApiTest.java
When registering a schema, -1 can be passed for the version to ensure it is the latest.  However, if the latest schema is equivalent to the schema being registered, a new version should not be created.
> DGS-18928 Don't create a new version if latest is equivalent

- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchemaComparator.java
- json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/JsonSchemaTest.java
Handle doubly nested CombinedSchema when getting tags.  A doubly nested CombinedSchema is a oneOf/allOf/anyOf directly nested under another oneOf/allOf/anyOf.   When comparing the elements of a CombinedSchema, derived classes were not being taken into account (such as CombinedSchemaExt, which extends CombinedSchema).
> DGS-18979 Handle doubly nested CombinedSchema when getting tags

- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/SpecificationVersion.java
- json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/JsonSchemaTest.java
Allow empty fragment (#) in $schema prop for JSON Schema, e.g.
http://json-schema.org/draft-07/schema# 
vs
http://json-schema.org/draft-07/schema
> DGS-18989 Allow empty fragment (#) in $schema prop for JSON Schema

- client/src/main/java/io/confluent/kafka/schemaregistry/AbstractSchemaProvider.java
- client/src/main/java/io/confluent/kafka/schemaregistry/ParsedSchema.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Metadata.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- protobuf-serializer/src/test/java/io/confluent/kafka/serializers/protobuf/KafkaProtobufSerializerTest.java
Handle refs with version of -1 when looking up schemas.  A ref with version of -1 will be replaced by the latest version during lookup.
Also refactored some code by adding it to ParsedSchema and Metadata
> DGS-18992 Handle refs with version of -1 when looking up schemas

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
Return 404 instead of 429 if schema lookup fails when searching through contexts
> DGS-19081 Return 404 instead of 429 if schema lookup fails

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/client/RetryExecutor.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/client/RetryExecutorTest.java
More robust retries in RetryExecutor, which is used by the schema exporters.  This will allow for retries when a 500 is returned due to failing to forward to the leader
> DGS-19038 More robust retries in RetryExecutor

- pom.xml
JSONata 2.4.6+ requires JDK 11
> Downgrade JSONata to 2.4.5

- pom.xml
Bouncycastle version is defined here:
https://github.com/confluentinc/common/blob/d3201e65b8d83a6ae6eeb6280fe2724c8518cf8c/pom.xml#L108
we should remove this to avoid duplicating the dependency updates.
> remove pin of bouncycastle to favor version defined in common

- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchemaUtils.java
- json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/JsonSchemaTest.java
- json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaSerializer.java
- json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/KafkaJsonSchemaSerializer.java
- json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/KafkaJsonSchemaSerializerConfig.java
Add new config `json.schema.scan.packages` to specify a list of packages to scan when deriving JSON schemas from objects.
> Add config to specify packages to scan when deriving JSON Schema

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStore.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreReaderThread.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreReaderThreadTest.java
New config allows user to configure whether or not they want a strict timeout when waiting for the kafka reader to reach the last offset during SR initialization and leader setting. 
Strict timeout means that an exception will be thrown if the Kafka reader does not reach the latest offset within the timeout.
The config to enable this is `kafkastore.init.reader.timeout.strict` and is defaulted to true, which is the existing behavior.
No action needs to be taken to maintain old behavior after this change.
> DGS-19032 fix: Config for not throwing timeout exception when waiting for Kafka reader on init

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStore.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreReaderThread.java
- core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreReaderThreadTest.java
- Reverted this change: https://github.com/confluentinc/schema-registry/commit/ea7bacbbd13eb2b65bef3976485cc1004aa563c0
- Added config for skipping waiting for the kafka reader on store init and leader election
> DGS-19032: Added config for not waiting for kafka reader on store init and leader election

- service.yml
- Enables semaphore jobs to run on branches starting with `cc-sc-v0`
> DGS-19049: Enable semaphore pipeline on SC release branch

- client/src/main/java/io/confluent/kafka/schemaregistry/AbstractSchemaProvider.java
- client/src/main/java/io/confluent/kafka/schemaregistry/ParsedSchema.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/protobuf/RestApiTest.java
What
----
Enhance lookup match to be more lenient w.r.t. confluent:version.
Previously we allowed a match if the schema being passed for lookup did not have a confluent:version.  We would return an existing schema that matches that has a confluent:version.
Now we also allow a match if the schema being passed has a confluent:version.  In this case it will match an existing schema that does not have confluent:version, but has a version that is the same as confluent:version
Checklist
- This is an improvement to the API behavior which is more lenient w.r.t. matches
- No
- Yes
- No
References
----------
JIRA: https://confluentinc.atlassian.net/browse/DGS-19323
Test & Review
------------
> DGS-19323 Enhance lookup match to be more lenient wrt confluent:version

- avro-converter/src/test/java/io/confluent/connect/avro/AvroConverterTest.java
- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java
- client/src/main/java/io/confluent/kafka/schemaregistry/AbstractSchemaProvider.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Metadata.java
- json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaDeserializer.java
- protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/AbstractKafkaProtobufDeserializer.java
What
----
This is a continuation of https://github.com/confluentinc/schema-registry/pull/3458 to add a small optimization to avoid making calls to SR if confluent:version is available.
Also, this fixes an NPE when using the MockSchemaRegistryClient, by using `!schemaVer.equals(prev.version())`, since `prev.version()` may be null during tests.
Checklist
- no
- no
- yes
- no
References
----------
JIRA: https://confluentinc.atlassian.net/browse/DGS-19323
Test & Review
------------
> DGS-19323 Optimization to use confluent:version if available

- core/src/test/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClientTest.java
- schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
- schema-serializer/src/main/java/io/confluent/kafka/serializers/WrapperKeyDeserializer.java
- schema-serializer/src/main/java/io/confluent/kafka/serializers/WrapperKeySerializer.java
- schema-serializer/src/main/java/io/confluent/kafka/serializers/migration/CompositeDeserializer.java
- schema-serializer/src/main/java/io/confluent/kafka/serializers/migration/CompositeDeserializerConfig.java
What
----
Add a utility class to help with use cases involving migrating from using a deserializer w/o SR to one with SR.
The composite deserializer takes two configs, the old non-SR deserializer, and a Confluent one (Avro, Protobuf, JSON Schema).  The composite deserializer first tries to determine if the payload corresponds to a schema (using similar logic to the schema validation broker plugin), then calls the appropriate deserializer.
Checklist
- Yes, adds a new utility class.
-  No
- Yes
- No
References
----------
JIRA:
Test & Review
------------
> DGS-19289 Add composite deserializer for migration use cases

- json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java
- json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/JsonSchemaTest.java
What
----
Fix to ensure json-skema validator is used for draft 2019-09 and 2020-12.  The skemaObj is populated when `rawSchema()` is called, so we call it before checking the value of `skemaObj`
Checklist
- No
- No
- Yes
- No
References
----------
JIRA:
Test & Review
------------
> DGS-19267 Ensure json-skema validator is called if possible

- pom.xml
What
----
JaCoCo coverage reporting does not work when the `surefire` and `failsafe` plugins are enabled because they overwrite the `argLine` variable used by JaCoCo. The solution is to append instead of overwrite in those plugins.
Ref: https://stackoverflow.com/a/23605812
Checklist
- **No code change**
References
----------
JIRA:
Test & Review
------------
> Prevent overwriting argLine execution variable

- .semaphore/semaphore.yml
This PR add cp-jar-build block for CP 7.9.x branch. For all future branches, cp-jar-build block will be added in semaphore.yml by cc-service-bot
Checklist
References
----------
JIRA:
Test & Review
------------
> CPBR-2063: adding cp-jar-build block for 79x

- avro-serializer/src/test/java/io/confluent/kafka/serializers/AvroSchemaTest.java
- client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
> Fix pint merge 7.3.x to 7.4.x

- core/src/test/java/io/confluent/kafka/schemaregistry/ClusterTestHarness.java
What
----
Add display name generator to ensure Kraft is used in integration tests, since the underlying QuorumTestHarness keys off of the display name.
Checklist
References
----------
JIRA:
Test & Review
------------
> Add display name generator to ensure Kraft is used in integration tests

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiCompatibilityTest.java
What
----
When registering a schema, a lookup is performed to see if an existing schema matches.  In certain cases, this lookup logic would succeed while a lookup by schema (when not registering) would fail.  This was the case with a persisted schema with an empty ruleSet, when the lookup is using a schema with a null ruleSet. This PR ensures the logic of the two different types of lookups (one during registration and one not) match.
Checklist
- Yes
References
----------
JIRA:
Test & Review
------------
> DGS-19699 Ensure lookup by schema logic matches logic during register

- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
- Fix on top of the base PR for the [BouncyCastle issue](https://confluentinc.atlassian.net/wiki/spaces/OAAC/pages/3814982290/LDAPS+AuthN+Failure+in+FIPS+due+to+Bouncy+Castle+Version+Upgrade+from+1.0.2.5+to+2.0.0): https://github.com/confluentinc/schema-registry/pull/3538
> CPSEC-628: Setting default SSLSocketFactory from HttpsURLConnection in RestService.

- dek-registry/src/test/java/io/confluent/dekregistry/storage/DekRegistryTest.java
- dek-registry/src/test/java/io/confluent/kafka/schemaregistry/rest/client/LocalSchemaRegistryClientTest.java
What
----
Checklist
References
----------
JIRA: DGS-19622
Test & Review
------------
This is to add tests.
> add missing tests for DekRegistry

- client/src/main/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/CustomBearerAuthCredentialProvider.java
What
----
`CustomBearerAuthCredentialProvider` is a wrapper around a `BearerAuthCredentialProvider` that schema registry uses to get authentication credentials for outgoing requests. If you create any resources which need to be closed inside of the wrapped `BearerAuthCredentialProvider`, they need to be closed. 
The `CustomBearerAuthCredentialProvider` was never calling close on the wrapped `BearerAuthCredentialProvider` 
Testing
---------
Test is not required for this change. The interface has a default close function 
https://github.com/confluentinc/schema-registry/blob/8ee8e59415e60330f2cbf24b49ffa0c3527b8594/client/src/main/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/BearerAuthCredentialProvider.java#L50-L52
Therefore this will only add the code path where the …
> USTORAGE-1069: Call close on custom auth provider

- schema-serializer/src/main/java/io/confluent/kafka/formatter/SchemaMessageReader.java
What
----
A previous fix for KIP-641 did not accommodate interactive usage with the console, whereas this one is a minor refactoring that does accommodate such usage.
This affects CP 7.9.0
Checklist
- This is a refactoring covered by existing tests
References
----------
JIRA:
Test & Review
------------
> DGS-19838 Fix message reader to allow for interactive usage

- debian/control
From CP 8.0, JDK 17 is the JDK that will be used to build CP packages. Hence, remove these dependencies.
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
> Remove java-7-jdk dependency from debian build scripts

- client/src/main/java/io/confluent/kafka/schemaregistry/ParsedSchema.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiModeTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/json/RestApiTest.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/protobuf/RestApiTest.java
What
----
Expand semantic check when looking up schemas.  This will handle the case when a schema is registered under two different IDs and subjects.  In this case the initial lookup using MD5 will fail, but the search will succeed.
Checklist
-  Lookups that previously failed with 404 now succeed, and register requests that previously registered a new schema now return the existing schema ID.
- No
- Yes
- No
References
----------
JIRA:
Test & Review
------------
> DGS-19657 Expand semantic check when looking up schemas

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/RequestHeaderHandler.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RequestHeaderHandlerTest.java
What
----
```
/**
* Puts a new header will take precedence over existing header in the HttpServletRequest object.
*/
public void putHeader(String name, String value) {
// Value will also overwrite any existing custom header value.
this.customHeaders.putSingle(name, value);
}
```
putHeader appears to already overrides the header, we just had a null check before
Checklist
References
----------
JIRA:
Test & Review
------------
> DGS-19985 Always override X-Forwarded-For header on follower call

- client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClientFactory.java
- client/src/main/java/io/confluent/kafka/schemaregistry/testutil/MockSchemaRegistry.java
hotfix to 7.8.x for
Support new CachedSchemaRegistryClient in SchemaRegistryClientFactory
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
> [DGS-19987] Support new CachedSchemaRegistryClient in SchemaRegistryClientFactory

- client/src/main/java/io/confluent/kafka/schemaregistry/utils/QualifiedSubject.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ConfigResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ModeResource.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
What
----
Handle default context properly for /config and /mode. Passing the default context (:.:) for the subject should be the same as the top level config/mode.
Checklist
References
----------
JIRA:
Test & Review
------------
> DGS-20411 Handle default context properly for /config and /mode

- avro-converter/src/test/java/io/confluent/connect/avro/AvroConverterTest.java
- client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchemaUtils.java
What
----
Extend `GenericData` with a subclass `NameAwareGenericData` to use field name instead of field position when accessing instances of `GenericRecord`.  In addition, all methods of `NameAwareGenericData` that access logical types should delegate to the singleton `GenericData.get()` for backward compatibility (when users set logical types on `GenericData.get()`).
Checklist
References
----------
JIRA:
Test & Review
------------
> DGS-20498 Ensure AvroConverter does not rely on field order

- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
What
----
Minor change to add a warning log whenever the baseUrl fails.
Checklist
- \[ ] Contains customer facing changes? Including API/behavior changes  N/A
- \[ ] Is this change gated behind config(s)?
- N/A
- \[ ] Did you add sufficient unit test and/or integration test coverage for this PR?
- N/A
- \[ ] Does this change require modifying existing system tests or adding new system tests? 
- N/A
References
----------
JIRA:
Test & Review
------------
> Add warning log whenever baseUrl changes in RestService

- client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClientTest.java
What
----
For CP 8.0, when registering a schema, the version is returned. However, this is not the case for CP 7.x.x. Therefore when looking up a schema, skip the cached entry if it does not have a version.
Cherry-pick of https://github.com/confluentinc/schema-registry/pull/3714 to 8.0.0
Checklist
- \[ ] Contains customer facing changes? Including API/behavior changes 
- \[ ] Is this change gated behind config(s)?
- \[x] Did you add sufficient unit test and/or integration test coverage for this PR?
- \[ ] Does this change require modifying existing system tests or adding new system tests? 
- If so, …
> DGS-20647 Ensure SR client cache for CP 8.0 is backward compat with 7.x.x

- .semaphore/semaphore.yml
What
----
Fix ubuntu image to s1-prod-ubuntu24-04-amd64-1.
Checklist
**NONE OF THIS APPLIES AS THIS IS A SEMAPHORE IMAGE UPGRADE**
> Fix ubuntu24 image in schema registry repo

- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Schema.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SchemasResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/MD5.java
- core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaValue.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
What
----
Ensure correct GUID when requesting a formatted schema via the REST APIs.  To do this, we set the GUID immediately when constructing the schema that will be returned in the REST response (as opposed to setting it lazily after the schema might have been later formatted).
Checklist
- If …
> DGS-20896 Ensure correct GUID when requesting a formatted schema

- client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
- client/src/main/java/io/confluent/kafka/schemaregistry/utils/QualifiedSubject.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SchemasResource.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
- protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java
What
----
Add referenceFormat param to allow qualify references with the parent context.
Checklist
References
----------
JIRA:
Test & Review
------------
> DGS-20884 Add referenceFormat param to qualify references

- dek-registry/src/main/java/io/confluent/dekregistry/storage/DekRegistryConfig.java
What
----
DGS-20984 Bump max DEK registry key default from 10K to 20K
Checklist
- **[N/A]** Does this change require modifying existing system tests or adding new system tests? 
References
----------
JIRA:
Test & Review
------------
> DGS-20984 Bump max DEK registry key default

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryRestApplication.java
What
----
This PR aims to correct the order of close() call between schemaRegistryResourceExtensions and schemaRegistry in the reverse order of initialization (which is schemaRegistry first and schemaRegistryResourceExtensions later)
Checklist
- If so, include tracking information for the system …
> Close Schema registry after closing resource extensions

- core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectsResource.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
What
----
This PR modifies the POST /subjects lookup to handle cases where a client might register a schema with normalize=true while the lookup request is made with normalize=false.
Previously, if a lookup failed with `normalize=false`, the API would immediately return an error. This commit changes that logic. It will now only fail the lookup if it fails with both normalize=false and normalize=true. This ensures that clients, like kSQL, can successfully find schemas that were registered using a different normalization setting.
The new logic is:
1. If a lookup fails with normalize=false, the API will automatically try the lookup again with normalize=true.
2. If the lookup fails with normalize=true, the API will then return an error, as this confirms the schema is genuinely not found under …
> DGS-20986 - Modify POST /subjects lookup to fail only if both normalize=true fails

- avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerializer.java
What
----
I'm the maintainer of Avro4k, a kotlin library allowing (de)serializing kotlin classes to avro bytes, and I'm currently working on integrating it with the confluent schema registry: https://github.com/avro-kotlin/avro4k/issues/218.
There is currently a kind of a mapper implemented to convert kotlin classes to Generic data, then we can use the converted data in the standard apache's library, and vice-versa, to then be used with the `kafka-avro-serializer`. However, doing that is twice less performant, and I would like to directly (de)serialize without this conversion step. Also, this conversion is mainly used to comply with the confluent's serializer, so thanks to this PR, I could remove around 1/3 of the current main codebase.
I would like to make possible providing a custom …
> feat(avro-serializer): Allow providing a custom DatumWriter in AbstractKafkaAvroSerializer

- client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java
- client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClient.java
- client/src/test/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClientTest.java
- core/src/main/java/io/confluent/kafka/schemaregistry/rest/client/LocalSchemaRegistryClient.java
- core/src/main/java/io/confluent/kafka/schemaregistry/utils/Props.java
- core/src/test/java/io/confluent/kafka/schemaregistry/rest/client/LocalSchemaRegistryClientTest.java
What
----
No breaking changes, adding an existing endpoint to the client interface and implementing in local and cached clients.
Checklist
- **[ Y ]** Contains customer facing changes? Including API/behavior changes 
- **[ N ]** Is this change gated behind config(s)?
- **[ Y ]** Did you add sufficient unit test and/or integration test coverage for this PR?
- **[ N ]** Does this change require modifying existing system tests or adding new system tests? 
- **[ N ]** Must this be released together with other change(s), either in this repo …
> add sr-version to sr client API

- client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java
- schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutorTest.java
What
----
Fix IndexOutOfBoundsException when evolving Avro schema w/rules.  Add code to ensure the schema of the message is used when transforming fields of the message.
Checklist
- **[N]** Must this be released together with other …
> DGS-22077  Fix IndexOutOfBoundsException when evolving Avro schema w/rules 

- client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java
- schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutorTest.java
What
----
Ensure tags are used during schema evolution.  This fixes a regression introduced by a partial fix by https://github.com/confluentinc/schema-registry/pull/3880
Checklist
- **[N]** Must this be released together with other …
> DGS-22077 Ensure tags are used during schema evolution

- protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/AbstractKafkaProtobufSerializer.java
What
----
i noted that the destination type for protobuf is byte[] and that the Message.toByteArray() is optimized for this use case. the ByteArrayOutputStream can/would resize its underlying buffer and the resulting byte array was copied out of its internal buffer. this solution should be cleaner and faster since it eliminates possible resizing and intermediate copying.
Checklist
- …
> avoid extra copying in protobuf serializer

- core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
What
----
Add assertions to validate parsed schema cache keys 
Checklist
- **[N/A]** Is this change gated behind config(s)?
- **[N/A]** Does this change require modifying existing system tests or adding new system tests? 
- **[N/A]** Must this be released together with other change(s), either in this repo or another one?
- If so, please include the link(s) to the changes …
> MINOR: Add assertions to validate parsed schema cache keys
