confluentinc/schema-registry

README.md
This way new contributors will know before they start what code style to follow.
I was also wondering if there's anything with regards to licensing that needs adding too?
=> Added point about Google code style to Readme.

README.md, docs/intro.rst
Simple change -- just append the subject's name to the URL.
=> Use correct URL to update compatibility setting of a subject

docs/api.rst
I think this was probably a typo...
=> Correct minor docs error in example response

bin/schema-registry-start, bin/schema-registry-stop, bin/schema-registry-stop-service, core/pom.xml, core/src/main/java/io/confluent/kafka/schemaregistry/rest/Main.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryMain.java, package/pom.xml
@ewencp 
This is my interpretation of your intended solution for #194 
If this makes sense, I can make similar changes for https://github.com/confluentinc/kafka-rest/issues/94
FYI, search with `git grep Main | grep -v SchemaRegistryMain` suggests I found the references that needed updating.
=> Issue 194 rename main

avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java, avro-converter/src/test/java/io/confluent/connect/avro/AvroDataTest.java
This is requred because the catch-all Anything schema cannot be a union since it
cannot be named, so null values cannot be encoded directly. If an entire value
is null we can use null directly, but for internal values (array entries, map
keys or values) we need to encode a null as an Anything struct with no non-null
fields.
=> Encode null values for schemaless array entries and map keys and values as an Anything record.

avro-converter/pom.xml, avro-serializer/pom.xml, json-serializer/pom.xml
Some of the pom files were not using the correct version variable
=> Fixed references to confluent common version

docs/changelog.rst, docs/intro.rst, pom.xml
Commit was cherry-picked from 2.x.
=> Update Kafka version to 0.9.0.1-cp1

avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java, avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDe.java, avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerializer.java, avro-serializer/src/test/java/io/confluent/kafka/serializers/KafkaAvroSerializerTest.java
=> Minor cleanup

config/log4j.properties, core/pom.xml, core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStore.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreReaderThread.java, core/src/main/resources/log4j.properties, core/src/test/java/io/confluent/kafka/schemaregistry/ClusterTestHarness.java, core/src/test/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClientTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/SchemaTopicTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/storage/StoreUtils.java, docs/config.rst
Please review carefully as this is my first schema registry patch. Plus, I'm not intimately familiar with the old consumer and may not have replicated its semantics perfectly. Although, I think I did. Thanks!
=> Using the new 0.9 Kafka consumer.

avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java
Backport for NPE when using optional nested fields.
=> fix for NPE when using optional nested fields

avro-converter/src/test/java/io/confluent/connect/avro/AvroDataTest.java
=> Test case for optional strings in structs

config/schema-registry.properties, core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java, core/src/test/java/io/confluent/kafka/schemaregistry/ClusterTestHarness.java, docs/config.rst, docs/security.rst
Depends on: https://github.com/confluentinc/rest-utils/pull/38
Don't merge until https://github.com/confluentinc/rest-utils/pull/38 is merged.
=> https support.

avro-converter/src/main/java/io/confluent/connect/avro/AvroConverter.java
=> Fix schemas.cache.config can't be overrided

README.md
The old address was wrong, and show 404, so I change to the new one.
=> Update the link to Google Java code Style

avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java, avro-converter/src/test/java/io/confluent/connect/avro/AvroDataTest.java
Fixes [#376](https://github.com/confluentinc/schema-registry/issues/376).
=> Support null namespace for Array of Records

core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStore.java, core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistryTest.java, docs/config.rst
Fixes this issue: https://github.com/confluentinc/schema-registry/issues/366
=> Fixing a bug where the listener port wasn't used in ZooKeeper.

docs/changelog.rst
=> 3.0.1 changelog

checkstyle/checkstyle.xml, pom.xml
First pass at adding checkstyle to this repository. It's enabled in reporting only mode.
=> Maven Checkstyle

avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java, avro-converter/src/test/java/io/confluent/connect/avro/AvroDataTest.java
Added support for Timestamp, Decimal, Time, and Date to and from Avro Logical Types.
=> Logical Type support

docs/api.rst, docs/config.rst
Documentation changes to reflect [pull request 415](https://github.com/confluentinc/schema-registry/pull/415) which added additional schema compatibility settings.
=> 	Documentation changes to reflect pull request 415

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, client/src/test/java/io/confluent/kafka/schemaregistry/client/rest/RestServiceTest.java
Fixes https://github.com/confluentinc/schema-registry/issues/463
=> Improve request URL building in client

core/src/test/java/io/confluent/kafka/schemaregistry/SASLClusterTestHarness.java
I am creating this and other PRs for review before merging https://github.com/apache/kafka/pull/2406.
=> Adapt to KAFKA-4636 changes

docs/intro.rst
show fetch schema by id immediately after registering it and before
introducing the additional concept of versions
=> Docchangefor3.2

docs/config.rst, docs/deployment.rst
@ewencp @rnpridgeon @gwenshap saw a conversation with you guys involved but didn't see the doc PR come out of it. If this is already done please let me know, otherwise I could use a quick review. Thanks!
=> MINOR: Add compact schemas topic doc

bin/schema-registry-run-class, bin/schema-registry-start
Minor restructuring to align handling of -daemon
flag the same way the kafka-run-class does and
support the -loggc and -name options.
=> Fixes for CLIENTS-257

avro-converter/pom.xml, avro-serializer/pom.xml, client/pom.xml, core/pom.xml, core/src/test/java/io/confluent/kafka/schemaregistry/ClusterTestHarness.java, json-serializer/pom.xml, maven-plugin/pom.xml, package-kafka-serde-tools/pom.xml, package-schema-registry/pom.xml, pom.xml
depends on https://github.com/confluentinc/rest-utils/pull/63
=> deps go in our parents

avro-serde/pom.xml
This is a left-over now that https://github.com/confluentinc/schema-registry/pull/519 was merged.
=> Update avro-serde pom.xml to match new setup after commit 331c4ca

client/pom.xml
=> Remove slf4j-log4j dependency from schema-registry-client

README.md
From local testing, this appears to be the form of requests that are required to delete schema versions or entire schema on the latest code base.
It seemed to be in high demand so I thought I'd figure it out and share it.  Up to you guys if you want to merge 😃 
Closes #227.
=> Add README entries for deleting schema / schema versions

core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
When the Master node fails over (especially for Kafka Based election), if the new master has not caught up with the offsets yet then the assigned next schemaid would be an old one. Wait for the offsets to be caught up before assigning in setMaster.
=> Fix potential schemaid overlap during Master failover

avro-converter/src/main/java/io/confluent/connect/avro/AvroConverter.java, avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java, avro-serializer/src/main/java/io/confluent/kafka/formatter/AvroMessageReader.java, avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDe.java, avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDeConfig.java, avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerializer.java, avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroDecoder.java, avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroEncoder.java, avro-serializer/src/test/java/io/confluent/kafka/formatter/KafkaAvroFormatterTest.java, avro-serializer/src/test/java/io/confluent/kafka/serializers/KafkaAvroSerializerTest.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClient.java
CLIENTS-586 
ability to turn off register during serialize
=> CLIENTS-586 : ability to turn off register during serialize

avro-console-scripts/pom.xml, avro-console-scripts/src/assembly/resources.xml, pom.xml
This lets us bring in Schema Registry's avro console scripts as a dependency.
Tested with local install.
=> generate artifact for avro-console-scripts

avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java, avro-converter/src/test/avro/Enum.avsc, avro-converter/src/test/avro/EnumUnion.avsc, avro-converter/src/test/java/io/confluent/connect/avro/AvroDataTest.java
Handle enum in fromConnectData
=> CLIENTS-708 & CLIENTS-720 Fix enum type in fromConnectData

README.md
It is a minor change, but really it gets hard to read the code when both comments and commands are same color
=> Increasing readability on README

pom.xml
=> CC-1333: Moving avro.version variable to confluent common

client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClient.java
Expose getAllVersions in SchemaRegistryClient so it is possible to check
which versions are available.
=> Add getAllVersions to SchemaRegistryClient

docs/README.md
Adds in-repo table of contents for documentation
=> Add docs navigation to GH README

docs/serializer-formatter.rst
https://confluentinc.atlassian.net/browse/DOCS-112
=> DOCS-112 - Typo

core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryRestApplication.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
Set the configured metrics tag on SR metrics
Depends on
https://github.com/confluentinc/common/pull/88
https://github.com/confluentinc/rest-utils/pull/81
=> Set metrics tag for SR metrics

docs/schema-deletion-guidelines.rst
=> DOCS-234 - Wrong link to Schema Registry API

docs/deployment.rst
https://confluent.slack.com/archives/C1A2E40DT/p1516396388000468
=> Broken link

docs/deployment.rst
https://confluentinc.atlassian.net/browse/DOCS-262
=> DOCS-262 - Fix linking

docs/api.rst, docs/changelog.rst, docs/config.rst, docs/deployment.rst, docs/maven-plugin.rst, docs/serializer-formatter.rst
https://confluentinc.atlassian.net/browse/DOCS-317
=> DOCS-317 - typo / missing text on Schema Registry doc

docs/deployment.rst
Added anchors so that I can reference in https://github.com/confluentinc/docs/pull/788
=> Added anchors

docs/deployment.rst
See https://confluent.slack.com/archives/C1A2E40DT/p1523593215000174
=> Remove |zk| from title

docs/deployment.rst
Reverts confluentinc/schema-registry#773
=> Revert "Remove |zk| from title"

docs/connect.rst, docs/serializer-formatter.rst
Realized that the the earlier PR was targeted at master after the merge.
=> Docs for Subject Name Strategy and Basic Auth

avro-converter/src/main/java/io/confluent/connect/avro/AvroConverter.java, avro-converter/src/test/java/io/confluent/connect/avro/AvroConverterTest.java
Fix for CC-1902:Avroconverter does not propagate subjectname strategy. The fix is to pass all the configs automatically.
=> CC-1902 : pass all configs to underlying Serializer/deserializer

docs/config.rst, docs/includes/shared-config.rst, docs/index.rst
https://confluentinc.atlassian.net/browse/DOCS-475
Fixes issue with too much information shown in [SR TOC](https://docs.confluent.io/current/schema-registry/docs/index.html). E.g.,
=> DOCS-475 - Fix SR TOC

config/schema-registry.properties, docs/deployment.rst
This PR modifies the docs and also the SR properties file to address https://github.com/confluentinc/schema-registry/issues/763
=> DOCS-458: Using ZK or Kafka for master election

docs/includes/shared-config.rst
https://confluentinc.atlassian.net/browse/DOCS-529
=> DOCS-529 - Fix includes

docs/serializer-formatter.rst
https://confluentinc.atlassian.net/browse/DOCS-476
- replaces https://github.com/confluentinc/schema-registry/pull/819
=> DOCS-476 - Fix port num and add cleanup

core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/SchemaRegistryCoordinator.java, core/src/test/java/io/confluent/kafka/schemaregistry/masterelector/kafka/SchemaRegistryCoordinatorTest.java
fc5f6b0e46ff81302b3e445fed0cdf454c942792 caused some incompatibility with the code here.
- Also added `CompatibilityResource` to the suppressions of NPathComplexity, as it did not compile for me otherwise (checkstyles failed)
=> MINOR: Add Timer class. Change from Kafka (commit fc5f6b0e46ff81302b3e445fed0cdf454c942792)

docs/index.rst, docs/installation.rst, docs/monitoring.rst, docs/using.rst
- Change `Monitoring` to `Monitoring Schema Registry`
- Add monitoring.rst to table of contents
- Add quickstart to table of contents
- Remove unused file reference to `using.rst` - this isn't added until 5.0.x
- Add using topic back to TOC
=> DOCS-775 - Make title unique and fix TOC

docs/index.rst
=> DOCS-630 - Add CCloud link to nav

docs/using.rst
https://confluentinc.atlassian.net/browse/DOCS-863
=> DOCS-863: How to register an existing schema to a new subject name

docs/serializer-formatter.rst
https://confluentinc.atlassian.net/browse/DOCS-733
=> DOCS-733: use bootstrap-server instead of zookeeper

docs/serializer-formatter.rst
https://confluentinc.atlassian.net/browse/DOCS-898
=> DOCS-898 - Typo in Schema Registry Serializer and Formatter topic

docs/serializer-formatter.rst
https://confluentinc.atlassian.net/browse/DOCS-898
=> DOCS-898 - Fix typo key.deserializer example

docs/config.rst, docs/deployment.rst, docs/index.rst, docs/using.rst
https://confluentinc.atlassian.net/browse/DOCS-851
=> DOCS-851 - Remove in-page navigation

docs/api.rst, docs/changelog.rst, docs/multidc.rst, docs/using.rst
Updated the duplicate headings with unique IDs
=> Duplicate Heading Update

docs/api.rst, docs/changelog.rst, docs/multidc.rst, docs/using.rst
* Updated the duplicate headings with unique IDs
* Removed a typo heading
=> Duplicate Heading Update (#937)

docs/api.rst
https://confluentinc.atlassian.net/browse/DOCS-929
- related https://github.com/confluentinc/docs/pull/1370
=> DOCS-929 - Fix confusing anchor links

docs/api.rst, docs/using.rst
https://confluentinc.atlassian.net/browse/DOCS-989
=> DOCS-989 - Fix legacy SR doc issues

client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, client/src/test/java/io/confluent/kafka/schemaregistry/client/rest/RestServiceTest.java
Provides ability to inject headers while invoking SR directly using CachedSchemaRegistryClient
=> CC-3003 : Ability to inject custom headers to CachedSchemaRegistryClient

docs/avro.rst
Restructure sections
See https://github.com/confluentinc/docs/pull/1498 for staging
=> DOCS-1130: Tweak SR Avro compatibility page

docs/includes/auto-schema-registration.rst, docs/includes/backend.rst, docs/index.rst, docs/schema_registry_tutorial.rst, docs/security.rst
[Staging info](https://github.com/confluentinc/docs/pull/1508)
Overview: add to SR security page, with a focus on governance
=> DOCS-1153: SR and ACLs

docs/using.rst
Reverts confluentinc/schema-registry#1002
=> Revert "DOCS-1202 - Cleanup shared include"

docs/develop/index.rst, docs/index.rst
Follow on PR to https://github.com/confluentinc/schema-registry/pull/1041/files
=> Follow to reorg PR

docs/security.rst
Copy-edit per previous comment from @joel-hamill on PR #1051 
(original Jira ticket: https://confluentinc.atlassian.net/browse/DOCS-1094)
=> DOCS-1094 - Schema Registry ACLs copyedit

docs/installation/index.rst
- fixing things for Schema Migrate topic
- Related PRs #1069 , #1066 
=> (WIP) DOCS-1333 - adding index for schema migrate TOC

docs/installation/index.rst, docs/installation/migrate.rst, docs/schema_registry_tutorial.rst
- Review comments and schema migrate walkthrough with @rayokota 
- PRs #1065 , #1069 , #1070 , and in `docs` repo: [#1737](https://github.com/confluentinc/docs/pull/1737)
- [PR DEVX-760 replicator example](https://github.com/confluentinc/examples/pull/140)
- [Minimal configuration for schema migration](https://github.com/confluentinc/examples/blob/DEVX-760/ccloud/submit_replicator_schema_migration_config.sh#L13-L33)
=> (WIP) DOCS-1333 - schema migrate walkthru-1 w/Rob

avro-converter/src/main/java/io/confluent/connect/avro/AvroDataConfig.java, avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java, avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDe.java, avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDeConfig.java, avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerializer.java, avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroDeserializerConfig.java, avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroSerializerConfig.java, avro-serializer/src/main/java/io/confluent/kafka/serializers/subject/SubjectNameStrategy.java, avro-serializer/src/main/java/io/confluent/kafka/serializers/subject/strategy/SubjectNameStrategy.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/security/basicauth/BasicAuthCredentialProvider.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/security/basicauth/SaslBasicAuthCredentialProvider.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/security/basicauth/UserInfoCredentialProvider.java, client/src/test/java/io/confluent/kafka/schemaregistry/client/security/basicauth/SaslBasicAuthCredentialProviderTest.java, client/src/test/java/io/confluent/kafka/schemaregistry/client/security/basicauth/UserInfoCredentialProviderTest.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/serialization/Serializer.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfigTest.java, json-serializer/src/main/java/io/confluent/kafka/serializers/KafkaJsonDecoderConfig.java, json-serializer/src/main/java/io/confluent/kafka/serializers/KafkaJsonDeserializerConfig.java, json-serializer/src/main/java/io/confluent/kafka/serializers/KafkaJsonSerializerConfig.java
depends on https://github.com/confluentinc/rest-utils/pull/133
tested locally
=> remove cp configdefs

client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java
=> MINOR: fix merge issue with MockSchemaRegistryClient

core/src/test/java/io/confluent/kafka/schemaregistry/masterelector/kafka/SchemaRegistryCoordinatorTest.java
These changes align with the internal AK changes made in https://github.com/apache/kafka/pull/6729.
=> MINOR: Fix compilation errors due to changes in KAFKA-8354

core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/SchemaRegistryCoordinator.java
=> MINOR: fix abstract coordinator usage

core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfigTest.java
See https://github.com/confluentinc/schema-registry/issues/790
=> CC-4604: Infer security protocol for kafka.bootstrap.servers

core/src/main/java/io/confluent/kafka/schemaregistry/rest/JsonErrorHandler.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryRestApplication.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryErrorHandlerTest.java, core/src/test/resources/testauth.properties
JsonErrorHandler for Schema Registry to avoid cryptic error messages in the client during failures like auth failures form Jetty.
=> CC-4099:JsonErrorHandler for Schema Registry 

avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDe.java, avro-serializer/src/test/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializerTest.java
=> Add config for mock registry in avro serdes Part 2

core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/SchemaRegistryCoordinator.java
* fixes the build, since the upstream constructor changed.
=> Use the new AbstractCoordinator interface

avro-serializer/src/main/java/io/confluent/kafka/serializers/subject/RecordNameStrategy.java
Handle nulls in RecordNameStrategy.
=> Fix issue 997.

core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreTest.java
Some minor cleanup to close the admin client in tests.
=> MINOR: close admin client in tests

avro-serializer/src/main/java/io/confluent/kafka/serializers/subject/TopicRecordNameStrategy.java
Handle null in RecordNameStrategy; fixes #1165
=> MINOR: handle null in RecordNameStrategy; fixes #1165

Jenkinsfile
=> MINOR: Update slack channel to #schema-registry-eng

Jenkinsfile
=> MINOR: Update slack channel to #schema-registry-eng (#1182)

avro-serializer/src/main/java/io/confluent/kafka/formatter/AvroMessageFormatter.java, avro-serializer/src/test/java/io/confluent/kafka/formatter/KafkaAvroFormatterTest.java
=> Avro Console Consumer "print.timestamp" prop (#947)

core/generated/swagger-ui/schema-registry-api-spec.yaml, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ConfigResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ModeResource.java
Adding some parameter decorators and the updated (autogenerated) API spec (yaml file).
=> Mark API Params for API Spec

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaString.java, core/generated/swagger-ui/schema-registry-api-spec.yaml, core/src/main/java/io/confluent/kafka/schemaregistry/id/IdGenerator.java, core/src/main/java/io/confluent/kafka/schemaregistry/id/IncrementalIdGenerator.java, core/src/main/java/io/confluent/kafka/schemaregistry/id/ZookeeperIdGenerator.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SchemasResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
This reverts commit 01acb120caac2ca54702eaf1449c853918cb1bd8.
=> Revert "Revert changes in IdGenerator (#1218)"

core/src/main/java/io/confluent/kafka/schemaregistry/id/IncrementalIdGenerator.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreTest.java
During registration, check if the ID is in use and if so, generate a new ID.
=> CC-3759 - Regenerate ID if in use during registration

core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreTest.java
=> MINOR: Add unit tests for #1174

avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java
Add extra logging information to distinguish between key and value in Avro deserialization exceptions
=> Improve Avro SerializationException message

avro-serializer/src/main/java/io/confluent/kafka/serializers/AvroSchemaUtils.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java, core/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroUtils.java, core/src/test/java/io/confluent/kafka/schemaregistry/avro/AvroCompatibilityTest.java
Disable default validation in Avro 1.9 to be compatible with 1.8.
=> DG-157: Disable default validation in Avro 1.9

core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/KafkaGroupMasterElector.java
Fix due to an upstream API change in Kafka clients
=> MINOR: fix createChannelBuilder call

protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufData.java, protobuf-converter/src/test/java/io/confluent/connect/protobuf/ProtobufDataTest.java
This fix distinguishes between null messages and
messages with all default field values
=> Fix handling of null messages in Protobuf converter

protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufConverter.java, protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufData.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/dynamic/DynamicSchema.java
Also preserve syntax during schema to descriptor transformations.
=> Fix default handling in Protobuf converter

checkstyle/suppressions.xml, core/src/main/java/io/confluent/kafka/schemaregistry/storage/InMemoryCache.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStore.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreMessageHandler.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreReaderThread.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/LookupCache.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaIdAndSubjects.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/Store.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/StoreUpdateHandler.java, core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/storage/StringMessageHandler.java
Some redundancy among the cache indexes is removed, and an issue with excessive tombstoning is fixed.
=> Optimize internal cache indexes

package-kafka-serde-tools/pom.xml, pom.xml
Add some missing dependencies for the `kafka-serde-tools` package
=> MINOR: add missing dependencies

client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java, client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchemaUtils.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/InMemoryCache.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchemaUtils.java, json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaDeserializer.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaUtils.java, protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/AbstractKafkaProtobufDeserializer.java, protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/AbstractKafkaProtobufSerializer.java
- More efficient copy constructors
- Cache some fields
- Also an optimization during tombstoning
=> Minor optimizations for schemas

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, core/generated/swagger-ui/schema-registry-api-spec.yaml, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SchemasResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaRegistry.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
=> Add API to retrieve supported schema types

core/src/main/java/io/confluent/kafka/schemaregistry/rest/JsonErrorHandler.java
This reverts commit e69c501103ac2b4fc8e58ecbe2c143cee0fdc473.
=> Revert "API update for Jetty 9.4.26.v20200117 (#1323)"

core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreReaderThread.java
Hi,
We sometimes hit that exception and cannot atm quickly dump the SR schema to investigate which record is causing the deserialization problem, quick log enhancement for future release if possible
Thank you
=> Enhanced serialization exception

pom.xml, protobuf-serializer/src/test/java/com/acme/glup/MetadataProto.java
Upgrade wire and protobuf dependencies
=> MINOR: Update protobuf deps

json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java, json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaDataConfig.java, json-schema-converter/src/test/java/io/confluent/connect/json/JsonSchemaDataTest.java
This is based on similar changes to AK.
=> Add support for both binary and numeric decimals for JSON

avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDeConfig.java, client/src/main/java/io/confluent/kafka/schemaregistry/ParsedSchema.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClient.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SubjectVersion.java, core/generated/swagger-ui/schema-registry-api-spec.yaml, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SchemasResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaIdAndSubjects.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
- Add REST API to get versions for id
- Allow clients to modify schemas during compat checks
- Add back some deprecations
=> Add REST API to get versions for id

avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java, avro-converter/src/test/java/io/confluent/connect/avro/AdditionalAvroDataTest.java
This fixes two issues:
1. A Connect default of type Struct causes "Unknown datum class: class
org.apache.kafka.connect.data.Struct"
2. An Avro default of type record causes "Invalid type for STRUCT: class
java.util.LinkedHashMap"
=> DG-263: Fix Avro defaults of type record

client/src/main/java/io/confluent/kafka/schemaregistry/ParsedSchema.java, client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java, client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchemaUtils.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/json/RestApiTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/protobuf/RestApiTest.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java
- Validate refs before persisting Protobuf schema
- Some refactoring of AvroUtils
- Register custom schema providers last
- Add some unit tests
=> DG-265 - Validate refs before persisting Protobuf schema

avro-data/src/test/java/io/confluent/connect/avro/AvroDataTest.java, json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java, json-schema-converter/src/test/java/io/confluent/connect/json/JsonSchemaDataTest.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java, protobuf-converter/src/test/java/io/confluent/connect/protobuf/ProtobufDataTest.java
Also added more unit tests for null input
=> DG-266: Fix NPE for null input for JsonSchemaData

protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufData.java, protobuf-converter/src/test/java/io/confluent/connect/protobuf/ProtobufDataTest.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java
Fix Protobuf converter enum handling to emit enum properly instead of int32.
=> DG-267 - Fix Protobuf converter enum handling

core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
cherry-picking following commit from master 
commit 710e27fe1860d8cc393e2935f9cb1f12887f26c4
Author: Robert Yokota <ryokota@confluent.io>
Date:   Wed Feb 5 15:40:17 2020 -0800
MINOR: Add initialized method (#1313)
=> MINOR: Add initialized method (#1313)

core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/diff/ObjectSchemaDiff.java, json-schema-provider/src/test/resources/diff-schema-examples.json, protobuf-provider/src/test/java/io/confluent/kafka/schemaregistry/protobuf/diff/SchemaDiffTest.java, protobuf-provider/src/test/resources/diff-schema-examples.json
- Add some more compatibility tests
- Some minor refactoring
=> MINOR: more compatibility tests, minor refactoring

maven-plugin/pom.xml, maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/CustomBasicComponentConfigurator.java, maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/DownloadSchemaRegistryMojo.java, maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/FixedMapConverter.java, maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/Reference.java, maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/RegisterSchemaRegistryMojo.java, maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/TestCompatibilitySchemaRegistryMojo.java, maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/UploadSchemaRegistryMojo.java, maven-plugin/src/main/resources/META-INF/plexus/components.xml, maven-plugin/src/test/java/io/confluent/kafka/schemaregistry/maven/SchemasWithDependenciesTest.java
The fix relies on https://stackoverflow.com/questions/38628399/using-map-of-maps-as-maven-plugin-parameters
=> DG-299 Fix processing of refs in SR maven plugin

json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java, json-schema-converter/src/test/java/io/confluent/connect/json/JsonSchemaDataTest.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/jackson/Jackson.java, json-schema-serializer/src/test/java/io/confluent/kafka/serializers/json/KafkaJsonSchemaSerializerTest.java
This is the same fix as KAFKA-9667.
See https://github.com/apache/kafka/pull/8230
=> DG-295 Fix trailing zeroes being stripped

README.md
- Jira ticket: https://confluentinc.atlassian.net/browse/DOCS-3297
- View rendered [README here](https://github.com/confluentinc/schema-registry/blob/5123ce9d005c31208daa765f3d09fbbeeb05316f/README.md).
- 5.4.0-post to match up to changes on the Docs side per https://github.com/confluentinc/docs/pull/3879, especially [this commit](https://github.com/confluentinc/docs/pull/3879/commits/ebc3105d81af685ba8ed938d5d9b6d757a902c54), and [this follow-on commit](https://github.com/confluentinc/docs/pull/3879/commits/87efd74ac786813ff19f6d3690bf9f84c064acd1).
=> DOCS-3297 Add docs links to SR README

avro-data/src/main/java/io/confluent/connect/avro/AvroData.java, benchmark/README.md, benchmark/pom.xml, benchmark/src/main/java/io/confluent/schemaregistry/benchmark/SerdeBenchmark.java, benchmark/src/main/resources/log4j.properties, benchmark/src/test/java/io/confluent/schemaregistry/benchmark/SerdeBenchmarkTest.java, client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/CompatibilityResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreReaderThread.java, core/src/main/java/io/confluent/kafka/schemaregistry/tools/SchemaRegistryClientPerformance.java, core/src/main/java/io/confluent/kafka/schemaregistry/tools/SchemaRegistryPerformance.java, findbugs/findbugs-exclude.xml, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchemaUtils.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/diff/SchemaDiff.java, json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/KafkaJsonSchemaDeserializer.java, json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/KafkaJsonSchemaSerializer.java, pom.xml, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java, protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/KafkaProtobufDeserializer.java, protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/KafkaProtobufSerializer.java
- Various perf optimizations for serdes
- Add JMH benchmarks
=> DG-308 Perf optimizations; add benchmarks

client/src/main/java/io/confluent/kafka/schemaregistry/ParsedSchema.java, client/src/main/java/io/confluent/kafka/schemaregistry/SchemaProvider.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java
Enhance JavaDocs for pluggable schema types
=> DOCS: Enhance JavaDocs for pluggable schema types

core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaRegistry.java, pom.xml
=> DG-91 Schema permanent delete. 

avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java
would be open to suggestions on how to add a good test for this
Signed-off-by: Lev Zemlyanov <lev@confluent.io>
=> CC-8525: add equals implementation for CyclicSchemaWrapper

core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
This PR is an extra verification testing after a new feature, which customizes HTTP response headers,  added to rest-utils due to SR REST application based on rest-utils.
https://github.com/confluentinc/rest-utils/pull/177
https://confluentinc.atlassian.net/wiki/spaces/CONNECT/pages/1047197302/One+Pager+-+Customize+HTTP+Response+Headers+on+Kafka+Connect+REST+and+CP+REST+Applications
=> SEC-929--Added one testing for verifying a feature added to rest-utils repo.

avro-converter/pom.xml, avro-serializer/pom.xml, avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDeConfig.java, avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroDeserializerConfig.java, avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroSerializerConfig.java, client/pom.xml, client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClientConfig.java, core/pom.xml, core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java, json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaDataConfig.java, json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaDeserializer.java, json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaSerializer.java, json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/KafkaJsonSchemaDeserializerConfig.java, json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/KafkaJsonSchemaSerializerConfig.java, json-serializer/pom.xml, protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufDataConfig.java, protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/AbstractKafkaProtobufDeserializer.java, protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/AbstractKafkaProtobufSerializer.java, protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/KafkaProtobufDeserializerConfig.java, protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/KafkaProtobufSerializerConfig.java, schema-serializer/pom.xml, schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDeConfig.java
Prior to approval/merge I will follow up on the concerns raised here. 
https://github.com/confluentinc/schema-registry/pull/1132#issuecomment-499765938
=> Migrate from Confluent common to AK common

schema-serializer/src/main/java/io/confluent/kafka/formatter/SchemaMessageReader.java
This is a small improvement to allow the schema ID to be passed to console producers.
=> Allow id to be passed to console prod/cons; fixes #160

json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchemaUtils.java, json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/JsonSchemaTest.java, json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaDeserializer.java
Cherry-pick from master to 5.5.x
=> DG-399 Use envelope in JsonSchemaUtils.toObject

core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreMessageHandler.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreReaderThread.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/json/RestApiTest.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java
Fix resolution of relative JSON Schema refs.  Also enhance some error logs with exception info.
=> MINOR: Fix resolution of relative JSON Schema refs

avro-converter/pom.xml, avro-data/pom.xml, avro-serializer/pom.xml, client/pom.xml, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaReference.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaString.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/ServerClusterId.java, core/generated/swagger-ui/schema-registry-api-spec.yaml, core/pom.xml, core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaReference.java, json-schema-provider/pom.xml, pom.xml, protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufData.java
Upgrade swagger dependencies, also remove some dependences from the client
Fixes #1302, fixes #1335, fixes #1418, fixes #1444
=> Upgrade swagger deps

client/pom.xml
This provides the implementation for UriBuilder
=> MINOR: re-add jersey-common after pom refactor

config/schema-registry.properties, core/src/main/java/io/confluent/kafka/schemaregistry/id/ZookeeperIdGenerator.java, core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/zookeeper/ZookeeperMasterElector.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreSASLTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreSSLAuthTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/storage/StoreUtils.java
- Add deprecations
- Add log warnings when using ZK-based coordination
- Replace ZK-based coordination with Kafka in tests
=> DG-268 Deprecate ZK-based coordination

maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/UploadSchemaRegistryMojo.java, maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/ValidateSchemaRegistryMojo.java
This adds a validate action so that errors can be seen locally.
=> Add validate action for SR maven plugin

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, core/generated/swagger-ui/schema-registry-api-spec.yaml, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SchemasResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaRegistry.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
Add batch get schema API.  It can be used to get all schemas or all latest schemas.
=> DG-540 Add batch get schema API

core/src/main/java/io/confluent/kafka/schemaregistry/rest/exceptions/Errors.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/CompatibilityResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
Also return true if the schema is valid, version is latest, and the
subject is empty.
=> DG-534 Enhance compat endpoint to validate schema

protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufData.java
Avoid regenerating default names for Protobuf data
Due to some refactoring and fixes, the sequence of default name generation no longer matches for the schema and data.  
Instead, use the generated names from the Protobuf descriptor.
=> DG-774 Avoid regenerating default names for Protobuf data

json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java, json-schema-converter/src/test/java/io/confluent/connect/json/JsonSchemaDataTest.java
Add support for number with format for JSON Schema
=> DG-780 Add support for number with format for JSON Schema

core/pom.xml, pom.xml
SecurePassConfigProvider class is required for security and monitoring features, and is included in the Kafka Client Plugins jar.
=> CP-644: Include CP jars required for Security and monitoring

core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfigTest.java
Enable mode mutability by default
=> DG-848 Enable mode mutability by default, fixes #1610

avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java, avro-serializer/src/test/java/io/confluent/kafka/serializers/KafkaAvroSerializerTest.java
=> DG-921 Fix Avro specific reader for unions

json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java, json-schema-converter/src/test/java/io/confluent/connect/json/JsonSchemaDataTest.java
=> DG-962 Handle const schemas in JSON Schema converter

client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java
fix for https://confluentinc.atlassian.net/browse/MMA-8608
=> MMA-8608: parse configs before calling restService.configure()

json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchemaUtils.java, json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/JsonSchemaTest.java
If a schema has references, ensure that the references are retained when creating an envelope object.
=> DG-1007 Preserve refs when converting schema to envelope

core/src/main/java/io/confluent/kafka/schemaregistry/id/IncrementalIdGenerator.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreMessageHandler.java
=> DG-1040 Register ids for soft deletes

json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaConverter.java, protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufConverter.java
- add unsupported class type in ProtobufConverter.toConnectData()'s exception messages
- add topic name in JsonConverter's exception messages
=> DG-293: Improve exception messages in JsonSchemaConverter and ProtobufConverter

json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java, json-schema-converter/src/test/java/io/confluent/connect/json/JsonSchemaDataTest.java
=> DG-1236 Improve oneOf handling in JsonSchemaConverter

pom.xml
Use the spotbugs version specified in `common`
=> Fix spotbugs version

protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/KafkaProtobufSerializer.java
Ensure dependencies are resolved before caching
=> DGS-1244 Resolve dependencies before caching

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, core/generated/swagger-ui/schema-registry-api-spec.yaml, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/CompatibilityResource.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
Address https://github.com/confluentinc/schema-registry/issues/1681
**Test**
Done manual test. Updated unit tests as well.
=> DGS-1361 Add API to Test Compatibility against specified subject

client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java
=> DGS-1221 Ensure AvroSchema.hashCode is consistent with equals

Jenkinsfile, avro-data/src/main/java/io/confluent/connect/avro/AvroData.java, avro-data/src/test/java/io/confluent/connect/avro/AvroDataTest.java
**Testing**
Test added. Done manual test.
=> DGS-1391: fix Avro Convertor for GenericData of union with null, string, enum

json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java, json-schema-converter/src/test/java/io/confluent/connect/json/JsonSchemaDataTest.java
Added unit test to cover this case.
Relates to #1800
=> DGS-1396 Fix optionality of ref schemas in JSON Schema converter

core/src/test/java/io/confluent/kafka/schemaregistry/rest/protobuf/RestApiTest.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaUtils.java, protobuf-provider/src/test/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaTest.java
Address #1803
**Testing**
Tests added.
=> DGS-1400 Escape Special Character in Protobuf Option

json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java, json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaDataConfig.java, json-schema-converter/src/test/java/io/confluent/connect/json/JsonSchemaDataTest.java
This adds a flag to make the change in #1745 configurable.
Fixes #1800 
Added a unit test
=> DGS-1402 Flag to set non-required fields to optional in JSON Schema

client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java
Synchronize reset() method in client
Fixes #1809
=> MINOR synchronize reset() method in client

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
Schema registry doesn't respond with messages when there are no problems.
=> Fix NPE when checking compatibility

core/src/main/java/io/confluent/kafka/schemaregistry/leaderelector/kafka/ClientConfig.java, core/src/main/java/io/confluent/kafka/schemaregistry/leaderelector/kafka/KafkaGroupLeaderElector.java, core/src/test/java/io/confluent/kafka/schemaregistry/SASLClusterTestHarness.java, schema-serializer/src/main/java/io/confluent/kafka/formatter/SchemaMessageFormatter.java
init was deprecated in MessageFormatter
=> init was deprecated in MessageFormatter

avro-serializer/src/test/java/io/confluent/kafka/serializers/AvroSchemaTest.java, client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java
Use raw Avro schema to check doc equality.  
Added a unit test.  Verified performance with the internal benchmarks.
=> DGS-1534 Use raw Avro schema to check doc equality

checkstyle/suppressions.xml, core/src/main/java/io/confluent/kafka/schemaregistry/storage/ClearSubjectValue.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/ConfigValue.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/DeleteSubjectValue.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreMessageHandler.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/ModeValue.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaValue.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/SubjectKey.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/SubjectValue.java
Refactor out a SubjectValue class from cached values.  Also set a subject for ModeValue and ConfigValue.
=> DGS-1528 refactor out SubjectValue class 

protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufData.java, protobuf-converter/src/test/java/io/confluent/connect/protobuf/ProtobufConverterTest.java, protobuf-converter/src/test/java/io/confluent/connect/protobuf/ProtobufDataTest.java
**Testing**
Updated existing tests. New tests added.
=> DGS-1522 Preserve sint32, sint64, fixed32, fixed64, sfixed32, sfixed64, uint32, uint64 type in ProtobufConverter

client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchemaUtils.java
Verified perf improvement via micro-benchmark
=> DGS-1550 Add cache for transformed schemas

client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Mode.java, client/src/test/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClientTest.java, core/generated/swagger-ui/schema-registry-api-spec.yaml, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ModeResource.java
Minor refactoring to change GetModeResponse to just Mode, to match the corresponding Config.
=> MINOR fix GetModeResponse to match Config

client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java, maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/UploadSchemaRegistryMojo.java, maven-plugin/src/test/java/io/confluent/kafka/schemaregistry/maven/SchemasWithDependenciesTest.java
=> DGS-1562 Don't require refs be declared with root schema

protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufData.java, protobuf-converter/src/test/java/io/confluent/connect/protobuf/ProtobufConverterTest.java
=> DGS-1569 Ensure recursive types are not built prematurely

json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java, json-schema-converter/src/test/java/io/confluent/connect/json/JsonSchemaDataTest.java
=> DGS-1570 Handle optional integer/number with format in JSON Schema

protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java, protobuf-provider/src/test/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaTest.java
Added a test.  Some refactoring
=> DGS-585 Add struct/empty Protobuf types

avro-data/src/main/java/io/confluent/connect/avro/AvroData.java, avro-data/src/test/java/io/confluent/connect/avro/AvroDataTest.java
=> DGS-1595 Ignore invalid Avro defaults in Avro converter

json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java, json-schema-converter/src/test/java/io/confluent/connect/json/JsonSchemaDataTest.java
=> DGS-1659 Be more lenient with non-string enums

protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java, protobuf-serializer/src/test/java/io/confluent/kafka/serializers/protobuf/KafkaProtobufSerializerTest.java
=> MINOR: fix Mock SR client when using multiple messages

avro-converter/src/main/java/io/confluent/connect/avro/AvroConverter.java, json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaConverter.java, protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufConverter.java, schema-serializer/src/main/java/io/confluent/kafka/formatter/SchemaMessageFormatter.java, schema-serializer/src/main/java/io/confluent/kafka/formatter/SchemaMessageReader.java
address https://github.com/confluentinc/schema-registry/pull/1746#issuecomment-842382603
=> MINOR: fix initialization of ConfigException instance

core/pom.xml, core/src/main/java/io/confluent/kafka/schemaregistry/storage/ClearSubjectValue.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/DeleteSubjectValue.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaKey.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaRegistryKey.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaValue.java
Brings #1770 to older branch to address CVE.
=> DGS-1551 Upgrade hibernate-validator

debian/Makefile
Support new security patch release pattern.
Add new security suffix for packaging name.
=> security patch release support

avro-converter/pom.xml, avro-serde/pom.xml, avro-serializer/pom.xml, client/pom.xml, core/pom.xml, pom.xml
Override `jackson-mapper-asl` according to instructions in https://confluentinc.atlassian.net/browse/DGS-1704
=> DGS-1704: Upgrade jackson-mapper-asl

core/src/main/java/io/confluent/kafka/schemaregistry/rest/exceptions/Errors.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ConfigResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ModeResource.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
JIRA ticket here: https://confluentinc.atlassian.net/browse/DGS-404
Added 40408 for subject level compatibility not set, and 40409 for subject level mode not set.
=> DGS-404: Improving error messages - adding 40408 and 40409 for subject level compatibility and mode error

avro-data/src/main/java/io/confluent/connect/avro/AvroData.java, avro-data/src/test/java/io/confluent/connect/avro/AvroDataTest.java
=> DGS-1758: Allow AvroData take JSON null as default

pom.xml, protobuf-converter/src/test/java/io/confluent/connect/protobuf/test/KeyValueWrapper.java, protobuf-serializer/src/test/java/io/confluent/connect/protobuf/test/DescriptorRef.java, protobuf-serializer/src/test/java/io/confluent/kafka/serializers/protobuf/test/DateValueOuterClass.java, protobuf-serializer/src/test/java/io/confluent/kafka/serializers/protobuf/test/DecimalValueOuterClass.java, protobuf-serializer/src/test/java/io/confluent/kafka/serializers/protobuf/test/Int16ValueOuterClass.java, protobuf-serializer/src/test/java/io/confluent/kafka/serializers/protobuf/test/Int8ValueOuterClass.java, protobuf-serializer/src/test/java/io/confluent/kafka/serializers/protobuf/test/TimeOfDayValueOuterClass.java, protobuf-types/src/main/java/io/confluent/protobuf/MetaProto.java, protobuf-types/src/main/java/io/confluent/protobuf/type/Decimal.java
Some generated files have changed as well
=> MINOR: upgrade protobuf from 3.17.0 to 3.17.3

avro-data/src/main/java/io/confluent/connect/avro/AvroData.java, avro-data/src/test/java/io/confluent/connect/avro/AvroDataTest.java
This is a follow-on PR for https://github.com/confluentinc/schema-registry/pull/1942, but for Avro
=> DGS-1825 Fix DataException when scrubbing invalid names (Avro)

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryRestApplication.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/filters/ContextFilter.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ContextsResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/filters/ContextFilterTest.java
=> DGS-1563 Add contexts resource

maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/UploadSchemaRegistryMojo.java, maven-plugin/src/test/java/io/confluent/kafka/schemaregistry/maven/SchemasWithDependenciesTest.java
Add a unit test.  Fixes #1951.
=> DGS-1853 Fix handling of slashes with refs in maven plugin

avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java, avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerializer.java, avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroDecoder.java, json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaDeserializer.java, protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/AbstractKafkaProtobufDeserializer.java
Fixes https://github.com/confluentinc/schema-registry/issues/553
=> DGS-1872 Remove use of VerifiableProperties from serdes

avro-data/src/main/java/io/confluent/connect/avro/AvroData.java, avro-data/src/main/java/io/confluent/connect/avro/AvroDataConfig.java, avro-data/src/test/java/io/confluent/connect/avro/AvroDataTest.java, checkstyle/suppressions.xml, client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchemaUtils.java, client/src/main/java/io/confluent/kafka/schemaregistry/utils/BoundedConcurrentHashMap.java, findbugs/findbugs-exclude.xml, json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java, json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaDataConfig.java, json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/KafkaJsonSchemaSerializer.java, protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufData.java, protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufDataConfig.java, protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/AbstractKafkaProtobufDeserializer.java, protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/AbstractKafkaProtobufSerializer.java, protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/KafkaProtobufSerializer.java, schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
=> DGS-1878 Remove use of SynchronizedCache

client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java
See https://github.com/confluentinc/schema-registry/issues/1910#issuecomment-884443801
=> Remove use of WrappedParsedSchema in mock client

client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java, client/src/test/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClientTest.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/InMemoryCache.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
Also use bounded caches in CachedSchemaRegistryClient
=> DGS-1869 Clean up mock client to be similar to cached client

core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java
This PR is in response to https://confluent.slack.com/archives/GMTE46A8Z/p1626724945120100?thread_ts=1626724352.119200&cid=GMTE46A8Z where we want to log the schema size for register requests.
=> Logging schema size when register

core/src/test/java/io/confluent/kafka/schemaregistry/rest/protobuf/RestApiTest.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java
=> DGS-1902 Use fully qualified names for Protobuf Map types

avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java, benchmark/src/main/java/io/confluent/schemaregistry/benchmark/SerdeBenchmark.java, client/src/main/java/io/confluent/kafka/schemaregistry/AbstractSchemaProvider.java, client/src/main/java/io/confluent/kafka/schemaregistry/CompatibilityChecker.java, client/src/main/java/io/confluent/kafka/schemaregistry/ParsedSchema.java, client/src/main/java/io/confluent/kafka/schemaregistry/SchemaProvider.java, client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java, client/src/main/java/io/confluent/kafka/schemaregistry/testutil/MockSchemaRegistry.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/jackson/Jackson.java, json-serializer/src/main/java/io/confluent/kafka/serializers/jackson/Jackson.java
this is required to update checkstyle as part of
https://github.com/confluentinc/common/pull/364
=> fix checkstyle violations with newer checkstyle versions

avro-data/src/main/java/io/confluent/connect/avro/AvroData.java, avro-data/src/test/java/io/confluent/connect/avro/AvroDataTest.java
=> DGS-2078 Fix optional Avro schema generation

avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerializer.java, avro-serializer/src/test/java/io/confluent/kafka/serializers/KafkaAvroSerializerTest.java, json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaSerializer.java, protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/AbstractKafkaProtobufSerializer.java, schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java, schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDeConfig.java
* DGS-2293 Add serializer config to specify schema ID
* Minor fix
=> DGS-2293 Add serializer config to specify schema ID (#2048)

json-schema-converter/src/test/java/io/confluent/connect/json/ResourceLoader.java
Fix https://github.com/confluentinc/schema-registry/issues/2092
=> Minor: Close stream in ResourceLoader

protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufData.java, protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufDataConfig.java, protobuf-converter/src/test/java/io/confluent/connect/protobuf/ProtobufConverterTest.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/dynamic/MessageDefinition.java
which does not set the field if the value is the default value.
=> DGS-1753 Add flag to support optional fields in Protobuf converter

avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java, avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerializer.java, avro-serializer/src/main/java/io/confluent/kafka/serializers/AvroData.java
=> DGS-2826 Add Avro UUID conversion; minor optimization

avro-data/src/main/java/io/confluent/connect/avro/AvroData.java, avro-data/src/test/java/io/confluent/connect/avro/AvroDataTest.java
Fixes https://github.com/confluentinc/schema-registry/issues/1606
=> DGS-2937 Use default scale of 0 in Avro converter

core/src/main/java/io/confluent/kafka/schemaregistry/leaderelector/kafka/SchemaRegistryCoordinator.java
follow up of https://github.com/confluentinc/schema-registry/pull/2188
=> DGS-3087: Accommodate upstream change in AbstractCoordinator

core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/CompatibilityResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ConfigResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ContextsResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ModeResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SchemasResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectsResource.java
Adds missing 200 response codes and descriptions to the OpenAPI specs.
=> Specify 200 responses to HTTP requests

core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ConfigResource.java
Adds short summaries for `ConfigResource.updateTopLevelConfig` and `ConfigResource.deleteSubjectConfig`.
=> MINOR: Fix ConfigResource summary and descriptions

client/pom.xml, core/pom.xml, pom.xml
This reverts commit 7b222add9d15eda333e96ba252de6222b1e7619d.
=> Revert "Fix swagger pulling in vulnerable snakeyaml 1.26"

json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaDeserializer.java, json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaSerializer.java, json-serializer/src/main/java/io/confluent/kafka/serializers/KafkaJsonDeserializer.java, json-serializer/src/main/java/io/confluent/kafka/serializers/KafkaJsonSerializer.java
=> DGS-3329 Expose ObjectMapper to allow customizations

core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/KafkaGroupMasterElector.java
=> MINOR: ignore WakeupException on shutdown

maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/SetCompatibilityMojo.java, maven-plugin/src/test/java/io/confluent/kafka/schemaregistry/maven/SetCompatibilityMojoTest.java
Cheer-picked commits from master
=> Cherry pick Set Compatibility Maven goal improvements for 7.2.x

maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/TestLocalCompatibilityMojo.java, maven-plugin/src/test/java/io/confluent/kafka/schemaregistry/maven/TestLocalCompatibilityMojoTest.java
The maven plugin enhancements are targeted for 7.2.x but this commit missed the branch cutoff. So, I am cherry-picking the commit and adding it to 7.2.x
Changes already merged with master - <a href="https://github.com/confluentinc/schema-registry/commit/ab002278c540d16d6e69a82931851dbe83881eaf">Commit</a>
What the changes are -Adding new goal test-local-compatibility for schema registry maven plugin
=> Cherry Picked Maven Plugin Changes for 7.2.x

client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java
Fixes https://github.com/confluentinc/schema-registry/issues/2268
=> MINOR minor mock client fixes

avro-converter/src/main/java/io/confluent/connect/avro/AvroConverter.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClientFactory.java, json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaConverter.java, protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufConverter.java, schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
=> MINOR refactor SR client creation into factory

avro-serializer/pom.xml, core/pom.xml, package-kafka-serde-tools/pom.xml, package-schema-registry/pom.xml
https://confluentinc.atlassian.net/browse/DGS-3582
https://confluentinc.atlassian.net/wiki/spaces/~913794610/pages/2772764716/Backport+reload4j+to+replace+Confluent-log4j+in+7.1.x+7.2.x+and+master#Rest-of-Eng
Test :
```
pushpabaral@C02FQ4UEMD6T schema-registry % mvn dependency:tree -Dincludes=org.slf4j:slf4j-log4j12
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: x86_64
[INFO] os.detected.bitness: 64
[INFO] os.detected.version: 10.16
[INFO] os.detected.version.major: 10
[INFO] os.detected.version.minor: 16
[INFO] os.detected.classifier: …
```
=> Migrate from confluent-log4j to reload4j

client/src/main/java/io/confluent/kafka/schemaregistry/client/security/SslFactory.java, client/src/test/java/io/confluent/kafka/schemaregistry/client/security/SslFactoryTest.java
Port https://issues.apache.org/jira/browse/KAFKA-12703 to SR
=> DGS-3679 Allow unencrypted private keys when using PEM files

core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/CompatibilityResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ConfigResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ContextsResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/DocumentedName.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ModeResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SchemasResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ServerMetadataResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectsResource.java
https://confluentinc.atlassian.net/wiki/spaces/~44042347/pages/2799440124/Documented+Names+for+SR+APIs
=> Added Custom Annotation

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaRegistryServerVersion.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ServerMetadataResource.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
Merging https://github.com/confluentinc/schema-registry/pull/2299 to from 7.0.x to 7.1.x
=> Manual pint merge - PR 2299

core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ServerMetadataResource.java
Adding DocumentedName annot for the new `v1/metadata/version` endpoint
=> Adding DocumentedName annot for v1/metadata/version endpoint

json-schema-converter/pom.xml, json-schema-provider/pom.xml, pom.xml
Fixes #2171
Please have a look at https://github.com/everit-org/json-schema/issues/449 , too.
=> Change everit-json-schema coordinates to reflect artifact published on Central

core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
revert exception change made in https://github.com/confluentinc/schema-registry/pull/2319
=> Revert remove schema in exception

protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufData.java, protobuf-converter/src/test/java/io/confluent/connect/protobuf/ProtobufDataTest.java
Fixes https://github.com/confluentinc/ksql/issues/9324
=> DGS-4358 Fix NPE in Protobuf converter for null map value

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, core/generated/swagger-ui/schema-registry-api-spec.yaml, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SchemasResource.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
Github Issue: https://github.com/confluentinc/schema-registry/issues/2333
=> [DGS-4361] Added "/schemas/ids/{id}/schema" endpoint

json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaSerializer.java
When a ValidationException is thrown during schema validation no information is giving regarding the specific validation errors encountered. The ValidationException toJSON() method  is used on this class to print a report of the errors found. The stack trace would look like: 
```java
Caused by: org.apache.kafka.common.errors.SerializationException: Validation error in JSON io.confluent.kafka.serializers.json.KafkaJsonSchemaSerializerTest$User@637c6a91, Error report:
{
"schemaLocation": "#/properties/firstName",
"pointerToViolation": "#/firstName",
"causingExceptions": [
{
"schemaLocation": "#/properties/firstName/oneOf/0",
"pointerToViolation": "#/firstName",
"causingExceptions": [],
"keyword": "type",
"message": "expected: null, found: String"
},
{
"schemaLocation": …
```
=> DGS-4419: Adding validation error report in json serialization

protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufData.java, protobuf-converter/src/test/java/io/confluent/connect/protobuf/ProtobufDataTest.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java
Handle map types with enhanced.protobuf.schema.support
=> DGS-4971 Handle map types with enhanced.protobuf.schema.support

checkstyle/suppressions.xml, client/src/main/java/io/confluent/kafka/schemaregistry/ParsedSchema.java, client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java, client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchemaProvider.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaMetadata.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClient.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Metadata.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Mode.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Rule.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/RuleKind.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/RuleMode.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/RuleSet.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Schema.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaReference.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaString.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/RegisterSchemaRequest.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/MD5.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/Metadata.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/Rule.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/RuleKind.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/RuleMode.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/RuleSet.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaReference.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaValue.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchemaProvider.java, pom.xml, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaProvider.java
Add new classes and fields to add metadata/rules to schema format
=> Add metadata/rules to schema format

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, core/generated/swagger-ui/schema-registry-api-spec.yaml, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/CompatibilityResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SchemasResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectsResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/LookupFilter.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaRegistry.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
fix https://github.com/confluentinc/schema-registry/issues/2225
=> DGS-3396: Add deletedOnly=true to SR list APIs

maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/DeriveSchemaMojo.java, maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/derive/schema/DeriveAvroSchema.java, maven-plugin/src/test/java/io/confluent/kafka/schemaregistry/maven/DeriveSchemaMojoTest.java
1. Adding DeriveSchemaMojo and DeriveSchemaMojoTest. (Only json and protobuf)
2. Will introduce tests for avro and json, and add derive avro once https://github.com/confluentinc/schema-registry/pull/2418 is merged
Edit:
Added avro and tests.
=> [DGS-5117] Derive Schema Maven Plugin

avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Rule.java, client/src/main/java/io/confluent/kafka/schemaregistry/rules/DlqAction.java, client/src/main/java/io/confluent/kafka/schemaregistry/rules/ErrorAction.java, client/src/main/java/io/confluent/kafka/schemaregistry/rules/NoneAction.java, client/src/main/java/io/confluent/kafka/schemaregistry/rules/RuleAction.java, client/src/main/java/io/confluent/kafka/schemaregistry/rules/RuleBase.java, client/src/main/java/io/confluent/kafka/schemaregistry/rules/RuleContext.java, json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaDeserializer.java, protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/AbstractKafkaProtobufDeserializer.java, schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutorTest.java, schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java, schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDeConfig.java
Add customizable post-rule actions, which includes error handling.  Also add built-in actions "none", "error", and "dlq".
=> DGS-5475 Add error handling for rules

pom.xml
This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall
=> Merge Conflict Resolution (from 7.0.x to 7.1.x)

maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/derive/schema/DeriveAvroSchema.java, maven-plugin/src/test/java/io/confluent/kafka/schemaregistry/maven/derive/schema/DeriveAvroSchemaTest.java, maven-plugin/src/test/java/io/confluent/kafka/schemaregistry/maven/derive/schema/DeriveJsonSchemaTest.java
Fixing bug for merging of union types and non-union type.
=> Bug fix for union types, added test for same and removing unused imports

core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaRegistry.java
Need this here https://github.com/confluentinc/confluent-security-plugins/pull/550
=> Expose function via interface to use in confluent-security-plugins

maven-plugin/pom.xml, maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/DeriveSchemaMojo.java, maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/derive/schema/DeriveAvroSchema.java, maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/derive/schema/DeriveJsonSchema.java, maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/derive/schema/DeriveProtobufSchema.java, maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/derive/schema/DeriveSchema.java, maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/derive/schema/DeriveSchemaUtils.java, maven-plugin/src/test/java/io/confluent/kafka/schemaregistry/maven/DeriveSchemaMojoTest.java, maven-plugin/src/test/java/io/confluent/kafka/schemaregistry/maven/derive/schema/DeriveAvroSchemaTest.java, maven-plugin/src/test/java/io/confluent/kafka/schemaregistry/maven/derive/schema/DeriveJsonSchemaTest.java, maven-plugin/src/test/java/io/confluent/kafka/schemaregistry/maven/derive/schema/DeriveProtoBufSchemaTest.java, maven-plugin/src/test/java/io/confluent/kafka/schemaregistry/maven/derive/schema/DeriveSchemaTest.java, maven-plugin/src/test/java/io/confluent/kafka/schemaregistry/maven/derive/schema/DeriveSchemaUtilsTest.java
Merging maven goal derive schema to 7.3.x. The tool is designed to generate a schema (Avro, JSON or ProtoBuf) from a given set of messages.
The changes are already in master. I've cherry-picked those commits. 
References
------------
1. Ticket - https://confluentinc.atlassian.net/browse/DGS-4764
2.  One-pager - https://confluentinc.atlassian.net/wiki/spaces/~327589041/pages/2738424866/One+Pager+-+Deriving+Schema+from+Messages
=> Derive schema maven plugin 7.3.x

client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Metadata.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Rule.java, client/src/main/java/io/confluent/kafka/schemaregistry/rules/RuleContext.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/Metadata.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/Rule.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/dynamic/DynamicSchema.java, protobuf-types/src/main/java/io/confluent/protobuf/MetaProto.java, protobuf-types/src/main/proto/confluent/meta.proto, schema-rules/src/main/java/io/confluent/kafka/schemaregistry/rules/cel/CelFieldExecutor.java, schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/NewWidgetProto.java, schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/WidgetProto.java, schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutorTest.java, schema-rules/src/test/proto/Widget.proto
Also rename annotations in metadata to paths, since these are annotating field paths
=> MINOR rename annotations to tags

checkstyle/suppressions.xml, config/schema-registry.properties, core/pom.xml, core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/InMemoryCache.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/MD5.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaValue.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/TransformedIterator.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/encoder/KeysetWrapper.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/encoder/KeysetWrapperDeserializer.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/encoder/KeysetWrapperSerde.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/encoder/KeysetWrapperSerializer.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/encoder/MetadataEncoderService.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/serialization/SchemaRegistrySerializer.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiMetadataEncoderTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/storage/encoder/MetadataEncoderServiceTest.java, pom.xml
Also adds a new Kafka cache for the encoder keysets
=> DGS-5335 Encode sensitive metadata properties at rest

avro-serializer/src/main/java/io/confluent/kafka/formatter/AvroMessageFormatter.java, avro-serializer/src/main/java/io/confluent/kafka/formatter/AvroMessageReader.java, avro-serializer/src/test/java/io/confluent/kafka/formatter/AvroMessageFormatterTest.java, avro-serializer/src/test/java/io/confluent/kafka/formatter/KafkaAvroFormatterTest.java, checkstyle/suppressions.xml, json-schema-serializer/src/main/java/io/confluent/kafka/formatter/json/JsonSchemaMessageFormatter.java, json-schema-serializer/src/main/java/io/confluent/kafka/formatter/json/JsonSchemaMessageReader.java, json-schema-serializer/src/test/java/io/confluent/kafka/formatter/json/KafkaJsonSchemaFormatterTest.java, protobuf-serializer/src/main/java/io/confluent/kafka/formatter/protobuf/ProtobufMessageFormatter.java, protobuf-serializer/src/main/java/io/confluent/kafka/formatter/protobuf/ProtobufMessageReader.java, protobuf-serializer/src/test/java/io/confluent/kafka/formatter/protobuf/KafkaProtobufFormatterTest.java, schema-serializer/src/main/java/io/confluent/kafka/formatter/SchemaMessageDeserializer.java, schema-serializer/src/main/java/io/confluent/kafka/formatter/SchemaMessageFormatter.java, schema-serializer/src/main/java/io/confluent/kafka/formatter/SchemaMessageReader.java, schema-serializer/src/main/java/io/confluent/kafka/formatter/SchemaMessageSerializer.java
Add header support to console producer/consumer.  Also add null support.
Fixes https://github.com/confluentinc/schema-registry/issues/1927, fixes https://github.com/confluentinc/schema-registry/issues/2390
=> DGS-5851 Add header support to console producer/consumer

client-encryption/src/main/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutor.java, client-encryption/src/test/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutorTest.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Rule.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/RuleSet.java, client/src/main/java/io/confluent/kafka/schemaregistry/rules/FieldRuleExecutor.java, client/src/main/java/io/confluent/kafka/schemaregistry/rules/FieldTransform.java, client/src/main/java/io/confluent/kafka/schemaregistry/rules/NoneAction.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/exceptions/RestInvalidRuleSetException.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ConfigResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiCompatibilityTest.java, package-kafka-serde-tools/pom.xml, schema-rules/src/main/java/io/confluent/kafka/schemaregistry/rules/cel/CelFieldExecutor.java, schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
Also some refactoring of the CSFLE code
=> DGS-5019 Add error tests for CSFLE

avro-serializer/src/test/java/io/confluent/kafka/serializers/AvroSchemaTest.java, client/src/main/java/io/confluent/kafka/schemaregistry/SchemaProvider.java, client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchemaProvider.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/test/java/io/confluent/kafka/schemaregistry/metrics/CustomSchemaProviderMetricTest.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchemaProvider.java, json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/JsonSchemaTest.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaProvider.java, protobuf-provider/src/test/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaTest.java
When normalizing Avro, ensure defaults are valid.
=> DGS-5909 When normalizing Avro, ensure defaults are valid

pom.xml, schema-rules/src/main/java/io/confluent/kafka/schemaregistry/rules/cel/avro/AvroObjectT.java
Also a minor improvement to a thrown exception type
=> MINOR Upgrade jsonata to 2.2.5

client/src/main/java/io/confluent/kafka/schemaregistry/SchemaProvider.java
Re-add some previous provider APIs for backward compatibility
=> MINOR re-add previous provider apis

avro-data/src/main/java/io/confluent/connect/avro/AvroData.java, avro-data/src/main/java/io/confluent/connect/avro/AvroDataConfig.java, avro-data/src/test/java/io/confluent/connect/avro/AvroDataTest.java
fix https://github.com/confluentinc/schema-registry/issues/2084
=> DGS-5950: Allow optional map key in Avro

maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/UploadSchemaRegistryMojo.java, maven-plugin/src/test/java/io/confluent/kafka/schemaregistry/maven/RegisterSchemaRegistryMojoTest.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java, protobuf-serializer/src/main/java/io/confluent/kafka/schemaregistry/protobuf/utils/MavenConfigGenerator.java
Also some minor cleanup to ProtobufSchema.fullName when used during testing
=> DGS-6014 Make url decoding in Maven plugin more lenient

maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/UploadSchemaRegistryMojo.java, maven-plugin/src/test/java/io/confluent/kafka/schemaregistry/maven/RegisterSchemaRegistryMojoTest.java
Make url decoding in Maven plugin more lenient
=> DGS-6014 cherry pick Maven plugin enhancement to 5.5.x

client/src/main/java/io/confluent/kafka/schemaregistry/SchemaEntity.java
Add utility functions to get EntityType.
=> Minor: Add utility function for SchemaEntity.EntityType

core/src/main/java/io/confluent/kafka/schemaregistry/leaderelector/kafka/KafkaGroupLeaderElector.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java
- Externalize Kafka group configs
=> DGS-6032: Externalize Kafka group configurations

checkstyle/suppressions.xml, client-encryption/src/main/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutor.java, client-encryption/src/test/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutorTest.java, client-encryption/src/test/java/io/confluent/kafka/schemaregistry/encryption/RestApiFieldEncryptionTest.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Rule.java, client/src/main/java/io/confluent/kafka/schemaregistry/rules/RuleContext.java, client/src/test/java/io/confluent/kafka/schemaregistry/client/rest/entities/MergeEntitiesTest.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/Rule.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiCompatibilityTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java, maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/Rule.java, schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutorTest.java, schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/jsonata/JsonataExecutorTest.java
=> Add rule params

core/pom.xml, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreReaderThread.java, core/src/main/java/io/confluent/kafka/schemaregistry/utils/ShutdownableThread.java
Reverting the dependency added due to a KAFKA change https://github.com/confluentinc/schema-registry/pull/2545
=> Remove kafka-server-common dependency

core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
Add a config to restore old behavior before https://github.com/confluentinc/schema-registry/pull/2469
=> Add config whether to delay leader election

json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java, json-schema-converter/src/test/java/io/confluent/connect/json/JsonSchemaDataTest.java
Ensure default values for the JsonSchemaConverter are converted from Jackson objects to org.json objects properly.
=> DGS-6603 Fix default conversions in JsonSchemaConverter

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/exceptions/RestClientException.java
This reverts commit 8c91301f1393fa2fd0b4eba3e408f125f796a6c8.
=> Revert "Update RestClientException.java (#2617)"

core/src/main/java/io/confluent/kafka/schemaregistry/rest/MutableHttpServletRequest.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/RequestIdHandler.java
Make the new classes added in https://github.com/confluentinc/schema-registry/pull/2579 `public`.
=> DGS-6062 MINOR fix: Make classes public

client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java, pom.xml, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java, schema-rules/pom.xml, schema-rules/src/main/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutor.java, schema-rules/src/main/java/io/confluent/kafka/schemaregistry/rules/cel/CelFieldExecutor.java, schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/NewWidgetProto.java, schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/WidgetProto.java, schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/WidgetWithRefProto.java, schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutorTest.java, schema-rules/src/test/proto/NewWidget.proto, schema-rules/src/test/proto/Widget.proto, schema-rules/src/test/proto/WidgetWithRef.proto
Also fixes some issues with null handling in the CEL executor.
=> DGS-7353 Allow message references in CEL_FIELD exprs

json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java, schema-rules/src/main/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutor.java, schema-rules/src/main/java/io/confluent/kafka/schemaregistry/rules/cel/CelFieldExecutor.java, schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutorTest.java
Handle JsonNode objects in CEL executors
=> DGS-7363 Handle JsonNode objects in CEL executors

client-encryption/src/main/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutor.java, client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java, schema-rules/src/main/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutor.java, schema-rules/src/main/java/io/confluent/kafka/schemaregistry/rules/cel/CelFieldExecutor.java, schema-rules/src/main/java/io/confluent/kafka/schemaregistry/rules/jsonata/JsonataExecutor.java
Cache parse trees in CEL, JSONata.
Other minor optimizations.
=> Minor rule optimizations

client-encryption-aws/src/main/java/io/confluent/kafka/schemaregistry/encryption/aws/AwsFieldEncryptionExecutor.java, client-encryption-azure/src/main/java/io/confluent/kafka/schemaregistry/encryption/azure/AzureFieldEncryptionExecutor.java, client-encryption-gcp/src/main/java/io/confluent/kafka/schemaregistry/encryption/gcp/GcpFieldEncryptionExecutor.java, client-encryption-hcvault/src/main/java/io/confluent/kafka/schemaregistry/encryption/hcvault/HcVaultFieldEncryptionExecutor.java, client-encryption/src/main/java/io/confluent/kafka/schemaregistry/encryption/Cryptor.java, client-encryption/src/main/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutor.java, client-encryption/src/main/java/io/confluent/kafka/schemaregistry/encryption/local/LocalFieldEncryptionExecutor.java, client-encryption/src/main/java/io/confluent/kafka/schemaregistry/encryption/noop/NoopAead.java, client-encryption/src/main/java/io/confluent/kafka/schemaregistry/encryption/noop/NoopFieldEncryptionExecutor.java, client-encryption/src/main/java/io/confluent/kafka/schemaregistry/encryption/noop/NoopKmsClient.java, client-encryption/src/test/java/io/confluent/kafka/schemaregistry/encryption/CryptorTest.java, client-encryption/src/test/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutorTest.java
Make DEL algorithm configurable, supported algos:  AES128_GCM, AES256_GCM, AES256_SIV
=> Make DEK algorithm configurable for CSFLE

client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClientConfig.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, client/src/test/java/io/confluent/kafka/schemaregistry/client/rest/RestServiceTest.java, schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDeConfig.java
Make these configurable.
```
http.connect.timeout.ms=<connection time out in milliseconds>
http.read.timeout.ms=<read time out in milliseconds>
```
=> DGS-7450 Making SR client http connect and read timeout configurable.

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
=> Fix duplicate variable httpConnectTimeoutMs definition

client/src/main/java/io/confluent/kafka/schemaregistry/CompatibilityChecker.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java
This is a continuation of a fix for RCCA-12410
=> Ensure compat check returns mutable lists

pom.xml
Update json-schema to bring in update org.json.json to address: CVE-2022-45688
=> CVE-442: Update json-schema

client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java
Only calculate inlineTags if schema is not null
=> MINOR fix NPE for inlineTags

client/src/main/java/io/confluent/kafka/schemaregistry/AbstractSchemaProvider.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClient.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaVersionFetcher.java
Ensure correct tenant is passed when resolving refs
=> DGS-7682 Ensure correct tenant is passed when resolving refs

avro-serializer/src/test/java/io/confluent/kafka/formatter/AvroMessageFormatterTest.java, schema-serializer/src/main/java/io/confluent/kafka/formatter/SchemaMessageFormatter.java
Fix NPE when print.schema.ids=true
=> DGS-7675 Fix NPE when print.schema.ids=true

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/TagSchemaRequest.java, client/src/test/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/TagSchemaRequestTest.java
fix bug introduced in https://github.com/confluentinc/schema-registry/pull/2696
=> Minor: Fix entity order after converting list to map

client-encryption/src/test/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutorTest.java, client/src/main/java/io/confluent/kafka/schemaregistry/rules/FieldRuleExecutor.java, schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutorTest.java
Ignore any later rules that have the same tags
=> Minor change to handling redundant rules for CSFLE

dek-registry/src/main/java/io/confluent/dekregistry/storage/DekRegistryConfig.java
So i can extend `DekRegistryConfig`
=> MINOR Added another constructor to DekRegistryConfig

avro-serializer/src/test/java/io/confluent/kafka/serializers/AvroSchemaTest.java, client/src/main/java/io/confluent/kafka/schemaregistry/ParsedSchema.java, client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java, client/src/main/java/io/confluent/kafka/schemaregistry/avro/Difference.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/diff/Difference.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/diff/SchemaDiff.java, json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/JsonSchemaTest.java, json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/diff/SchemaDiffTest.java, json-schema-provider/src/test/resources/diff-schema-examples.json, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/diff/Difference.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/diff/SchemaDiff.java, protobuf-provider/src/test/java/io/confluent/kafka/schemaregistry/protobuf/diff/SchemaDiffTest.java, protobuf-provider/src/test/resources/diff-schema-examples.json
Changes for reserved fields support for Avro, JSON and Protobuf schema.
https://confluentinc.atlassian.net/browse/DGS-7865
=> DGS-7865: Reserved fields support

client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaMetadata.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Schema.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaString.java, core/generated/swagger-ui/schema-registry-api-spec.yaml, core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaValue.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
Add timestamp to returned schemas.  Fixes https://github.com/confluentinc/schema-registry/issues/1899
=> DGS-8334 Add timestamp to returned schemas

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/RuleSet.java, core/pom.xml, core/src/main/java/io/confluent/kafka/schemaregistry/rest/client/LocalSchemaRegistryClient.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SchemasResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaRegistry.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiCompatibilityTest.java, pom.xml
Add ruleType filter to schemas endpoint.
Also a minor optimization to replace Guava cache with Caffeine for the schema cache.
=> DGS-8336 Add ruleType filter to schemas endpoint

dek-registry/src/main/java/io/confluent/dekregistry/web/rest/resources/DekRegistryResource.java
DocumentedName Changes 
- deleteKek -> deregisterKek
- createKek -> registerKek
- deleteDek -> deregisterDek
- createDek -> registerDek
=> DGS-8553: Updated create and delete DEK Registry API documented names

client/src/main/java/io/confluent/kafka/schemaregistry/rules/DlqAction.java, schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutorTest.java
This will allow the DLQ action to work with the command line tools
=> DGS-8615 Minor change to DlqAction

client-encryption-azure/src/main/java/io/confluent/kafka/schemaregistry/encryption/azure/AzureKmsClient.java, client-encryption-hcvault/pom.xml, client-encryption-hcvault/src/main/java/io/confluent/kafka/schemaregistry/encryption/hcvault/HcVaultKmsAead.java, client-encryption-hcvault/src/main/java/io/confluent/kafka/schemaregistry/encryption/hcvault/HcVaultKmsClient.java, client-encryption-hcvault/src/main/java/io/confluent/kafka/schemaregistry/encryption/hcvault/HcVaultKmsDriver.java, client-encryption-hcvault/src/test/java/io/confluent/kafka/schemaregistry/encryption/hcvault/HcVaultFieldEncryptionProperties.java, pom.xml
Upgrade vault to latest library.  Also add support for Vault namespaces
=> Upgrade vault lib; add namespace support

client-encryption-aws/src/test/java/io/confluent/kafka/schemaregistry/encryption/aws/AwsFieldEncryptionExecutorTest.java, client-encryption-aws/src/test/java/io/confluent/kafka/schemaregistry/encryption/aws/AwsFieldEncryptionProperties.java, client-encryption-aws/src/test/java/io/confluent/kafka/schemaregistry/encryption/aws/AwsFieldEncryptionServiceLoaderTest.java, client-encryption-azure/src/test/java/io/confluent/kafka/schemaregistry/encryption/azure/AzureFieldEncryptionExecutorTest.java, client-encryption-azure/src/test/java/io/confluent/kafka/schemaregistry/encryption/azure/AzureFieldEncryptionProperties.java, client-encryption-azure/src/test/java/io/confluent/kafka/schemaregistry/encryption/azure/AzureFieldEncryptionServiceLoaderTest.java, client-encryption-gcp/src/test/java/io/confluent/kafka/schemaregistry/encryption/gcp/GcpFieldEncryptionExecutorTest.java, client-encryption-gcp/src/test/java/io/confluent/kafka/schemaregistry/encryption/gcp/GcpFieldEncryptionProperties.java, client-encryption-gcp/src/test/java/io/confluent/kafka/schemaregistry/encryption/gcp/GcpFieldEncryptionServiceLoaderTest.java, client-encryption-hcvault/src/test/java/io/confluent/kafka/schemaregistry/encryption/hcvault/HcVaultFieldEncryptionExecutorTest.java, client-encryption-hcvault/src/test/java/io/confluent/kafka/schemaregistry/encryption/hcvault/HcVaultFieldEncryptionProperties.java, client-encryption-hcvault/src/test/java/io/confluent/kafka/schemaregistry/encryption/hcvault/HcVaultFieldEncryptionServiceLoaderTest.java, client-encryption/src/main/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutor.java, client-encryption/src/test/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutorTest.java, client-encryption/src/test/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionProperties.java, client-encryption/src/test/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionServiceLoaderTest.java, client-encryption/src/test/java/io/confluent/kafka/schemaregistry/encryption/local/LocalFieldEncryptionProperties.java, client-encryption/src/test/java/io/confluent/kafka/schemaregistry/encryption/local/LocalFieldEncryptionServiceLoaderTest.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/encoder/MetadataEncoderService.java, dek-registry/src/test/java/io/confluent/dekregistry/testutil/TestKmsClient.java
Add tests for DEK generation.
Also clean up some more deprecated Tink APIs
=> Add tests for DEK generation

core/src/main/java/io/confluent/kafka/schemaregistry/rest/filters/AliasFilter.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/filters/AliasFilterTest.java
Ensure the tenant prefix is used for aliases if appropriate.
=> DGS-8908 Ensure tenant prefix is used for aliases

protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java
=> Cache ProtobufSchema.toDynamicSchema calls (#2818)

maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/DownloadSchemaRegistryMojo.java, maven-plugin/src/test/java/io/confluent/kafka/schemaregistry/maven/DownloadSchemaRegistryMojoTest.java
Fixes https://github.com/confluentinc/schema-registry/issues/2697
=> Encode subject names for Maven download plugin

avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java, avro-serializer/src/test/avro/extended_user.avsc, avro-serializer/src/test/java/io/confluent/kafka/serializers/KafkaAvroSerializerTest.java, client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchemaUtils.java
Fixes https://github.com/confluentinc/schema-registry/issues/2833
=> Revert changes to SpecificData due to DGS-8901

schema-rules/src/main/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutor.java, schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutorTest.java
Add strings extension lib for CEL executor
=> DGS-9031 Add strings extension lib for CEL executor

core/src/main/java/io/confluent/kafka/schemaregistry/leaderelector/kafka/KafkaGroupLeaderElector.java, core/src/main/java/io/confluent/kafka/schemaregistry/leaderelector/kafka/SchemaRegistryCoordinator.java, core/src/test/java/io/confluent/kafka/schemaregistry/leaderelector/kafka/SchemaRegistryCoordinatorTest.java
This reverts commit 3609aefeefcfc7825e85d0e2149f74041d8330ec.
=> Revert "Fix build due to recent AK changes (#2774)"

core/src/main/java/io/confluent/kafka/schemaregistry/metrics/MetricsContainer.java
add back kafkaclusterid label for on prem
=> DGS-9059 enable otel colector by fixing metric labels

sonar-project.properties
Applying service bot changes to version branches
https://github.com/confluentinc/schema-registry/commit/39a27d4b95cd8a5379f5ac2e67163362187baff7
=> Apply service bot changes to version branches

client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java, core/src/test/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClientTest.java
Fixes https://github.com/confluentinc/schema-registry/issues/2813
=> Fix NPE for getAllVersionsById in MockSchemaRegistryClient

json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchemaUtils.java, json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/KafkaJsonSchemaSerializer.java
Fixes https://github.com/confluentinc/schema-registry/issues/2383
=> Minor optimization - cache schemas for json envelopes

client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaMetadata.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Schema.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaString.java, core/generated/swagger-ui/schema-registry-api-spec.yaml, core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaValue.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
This reverts commit a7eb2db2c281ffb232df617d7e57090dffd175fc.
=> Revert "DGS-8334 Add timestamp to returned schemas (#2759)"

checkstyle/suppressions.xml, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/diff/CombinedSchemaDiff.java, json-schema-provider/src/test/resources/diff-combined-schema-examples.json
Also support changing an allOf to a singleton.  Add additional tests
=> DGS-9520 Support allOf to singleton for JSON Schema

avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java, avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroSerializer.java, avro-serializer/src/test/java/io/confluent/kafka/serializers/KafkaAvroSerializerTest.java, client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchemaUtils.java
Ensure logicalType flag is passed to ReflectData.  Add unit tests
=> DGS-8901 Ensure logicalType flag passed to ReflectData

pom.xml
Update common-compress library to address CVE-2024-25710
=> DGS-xxxx: update common-compress

avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java
This was missed during a previous refactor
=> MINOR Ensure correct GenericData is used

json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/schema/SchemaTranslator.java, json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/JsonSchemaTest.java, pom.xml
Add proper handling of nested references for JSON schema reference trees of two or more levels.  This required a fix in the third-party JSON Schema library: https://github.com/erosb/json-sKema/pull/65
=> DGS-10161 Handle nested references for JSON Schema 2020-12

client-encryption/src/main/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutor.java, client-encryption/src/test/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutorTest.java
Add CSFLE test for null field to catch future regressions
=> MINOR add CSFLE test for null field

.semaphore/semaphore.yml
Applying service bot changes that were merged to master (here: https://github.com/confluentinc/schema-registry/pull/2997) to earlier version branches. This PR will be pint merged to master.
=> Minor: Apply service bot changes to earlier branches

checkstyle/suppressions.xml, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Config.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/ConfigUpdateRequest.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/ConfigValue.java
Use of this config will be added in the future
=> Add config to validate rules

avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/ReflectionAvroDeserializer.java
=> Re-add schema parameter that was dropped during refactor

avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroDeserializer.java
=> Ensure specific Avro type is setup during configure

protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java, protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/AbstractKafkaProtobufSerializer.java
=> Optimization: remove known deps from ProtobufSchema

schema-rules/src/main/java/io/confluent/kafka/schemaregistry/rules/jsonata/JsonataExecutor.java
Follow convention that rule params are prefixed with the type of rule
=> Rename Jsonata params

json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java
=> fix: invalid behaviour for stringSchema in allOfToConnectSchema

json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java, json-schema-converter/src/test/java/io/confluent/connect/json/JsonSchemaDataTest.java
Added support for using references inside "allOf"
This kind of structure should function now.
```json
{
"allOf" : [{"$ref": "..."}]
}
```
=> feat: Added ReferenceSchema support to allOf

json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java, json-schema-converter/src/test/java/io/confluent/connect/json/JsonSchemaDataTest.java
feat: Added ReferenceSchema support to allOf
cherry pick of [77f059d](https://github.com/confluentinc/schema-registry/commit/77f059d67ebbf18adfa677876e4f71d0527359cf)
=> Cherry pick ref in allof support from master

json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java, json-schema-converter/src/test/java/io/confluent/connect/json/JsonSchemaDataTest.java
fix: nested schemas were not considered in matching the correct Json Union schema
Cherry-pick pull request #3059 from MaciasMucias/master
=> fix: nested schemas were not considered in matching the correct Json Union schema

pom.xml
=> Update Apache commons-compress to 1.26.1

client-encryption/src/main/java/io/confluent/kafka/schemaregistry/encryption/tools/RegisterDeks.java, client-encryption/src/test/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutorTest.java, client-encryption/src/test/java/io/confluent/kafka/schemaregistry/encryption/local/LocalFieldEncryptionExecutorByTypeTest.java, schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
First look up based on name, then on rule type, then look up defaults
=> Ensure consistent lookup of rule params

json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java, json-schema-converter/src/test/java/io/confluent/connect/json/JsonSchemaDataTest.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/diff/ConstSchemaDiff.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/diff/SchemaDiff.java, json-schema-provider/src/test/resources/diff-schema-examples.json
Also added better support for const in compat checks
=> DGS-10808 Support const in JSONSchemaConverter

json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/jackson/Jackson.java
=> Fix build due to Jackson upgrade to 2.16.2

schema-rules/src/main/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutor.java
To account for possibly  non-deterministic iteration of map
=> MINOR remove map to list conversion in CEL Executor

client-encryption-tink/src/main/java/io/confluent/kafka/schemaregistry/encryption/tink/KmsDriverManager.java, schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
First try using the thread's context classloader, then try using the classloader of the given class.
=> DGS-11826 Add more robust handling of ServiceLoader

avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java, avro-serializer/src/test/java/io/confluent/kafka/serializers/KafkaAvroSerializerTest.java, client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchemaUtils.java
=> DGS-12608 Fix deserialization of Avro unions with logical types

core/src/main/java/io/confluent/kafka/schemaregistry/metrics/MetricsContainer.java
Slack: https://confluent.slack.com/archives/C01CELGMS68/p1719511165368359?thread_ts=1718893083.105419&cid=C01CELGMS68
=> Add back getMetricsTags() method

client/src/main/java/io/confluent/kafka/schemaregistry/utils/QualifiedSubject.java, dek-registry/src/main/java/io/confluent/dekregistry/storage/DataEncryptionKeyId.java, dek-registry/src/main/java/io/confluent/dekregistry/storage/DekRegistry.java
Change DataEncryptionKeyId.compareTo to delegation subject comparison to QualifiedSubject.compareTo
=> Fix comparator for DataEncryptionKeyId

client/src/main/java/io/confluent/kafka/schemaregistry/avro/Difference.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaRegistryServerVersion.java, schema-serializer/src/main/java/io/confluent/kafka/serializers/WrapperKeyDeserializer.java, schema-serializer/src/main/java/io/confluent/kafka/serializers/WrapperKeyDeserializerConfig.java, schema-serializer/src/main/java/io/confluent/kafka/serializers/WrapperKeySerializer.java, schema-serializer/src/main/java/io/confluent/kafka/serializers/WrapperKeySerializerConfig.java
Fixed https://github.com/confluentinc/schema-registry/issues/3042.
=> Fix incorrect license in client/ and schema-serializer/

pom.xml
We target master because of a dependency on protobuf 3.25+
=> Upgrade cel-java dependency to 0.4.4

pom.xml
Reverts confluentinc/schema-registry#3172
=> Revert "Upgrade JSONata dependency to 2.5.0"

schema-serializer/src/main/java/io/confluent/kafka/serializers/WrapperKeyDeserializer.java
=> Fix license typo

avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerializer.java, checkstyle/suppressions.xml, client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClient.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/RegisterSchemaRequest.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/client/LocalSchemaRegistryClient.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaRegistry.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiRegisterSchemaTagsTest.java, json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaSerializer.java, maven-plugin/src/main/java/io/confluent/kafka/schemaregistry/maven/RegisterSchemaRegistryMojo.java, protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/AbstractKafkaProtobufSerializer.java, schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java, schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDeConfig.java
* Add config to propagate schema tags during registration
* Update schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDeConfig.java
---------
=> Add config to propagate schema tags during registration (#1)

schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
* DGS-15318 Convert 429 to a retriable exception (#8)
* DGS-15318 Convert 429 to a retriable exception
* Minor refactor
* Minor enhancement
* Minor enhancement
* Fix checkstyle
* Minor fixes
* Minor cleanup
---------
=> Fix pint merge 5 (#13)

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
Fixing checkstyle on master of schema-registry due to line too long.
=> Fix checkstyle on master

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
Copying this commit to version branches: https://github.com/confluentinc/schema-registry/pull/3214 and https://github.com/confluentinc/schema-registry/pull/3187
=> Pint merge the json processing error string handling

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
Pint merge was started on 7.0.x but failed on 7.4.x due to another PR being merged. This PR fixes that by manually putting changes in 7.4.x. This commit will then be pint merged to master.
=> 7.4.x pint merge of JsonProcessingError String handling

avro-serializer/src/test/java/io/confluent/kafka/formatter/AvroMessageFormatterTest.java, avro-serializer/src/test/java/io/confluent/kafka/formatter/KafkaAvroFormatterTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/SASLClusterTestHarness.java, json-schema-serializer/src/test/java/io/confluent/kafka/formatter/json/KafkaJsonSchemaFormatterTest.java, protobuf-serializer/src/test/java/io/confluent/kafka/formatter/protobuf/KafkaProtobufFormatterTest.java
Fixes master build from JaasTestUtils being converted from Scala to Java in open source Kafka. Verified tests pass now with this commit so this should unblock CP build
=> Fix Build After Migration of JaasTestUtils to Java

client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java, core/src/test/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClientTest.java
* Implement getContexts for Mock SR client
* Minor fix
=> DGS-16357 Implement getContexts for Mock SR client (#30)

client-encryption/src/main/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutor.java, client/src/main/java/io/confluent/kafka/schemaregistry/rules/RuleClientException.java
* Convert DEK registry exceptions to RuleClientException
* Minor refactor
=> Convert DEK registry exceptions to RuleClientException (#28)

core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ConfigResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ModeResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SchemasResource.java
Resolve Pint Merge Conflict on 7.3.x
=> Resolve Pint Merge Conflict on 7.3.x

avro-serializer/src/test/java/io/confluent/kafka/serializers/AvroSchemaTest.java, client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java
* Bound recursion when finding tagged entities
* Minor fix
=> DGS-16677 Bound recursion when finding tagged entities (#40)

protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufData.java, protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufDataConfig.java, protobuf-converter/src/test/java/io/confluent/connect/protobuf/ProtobufDataTest.java
Fixes https://github.com/confluentinc/schema-registry/issues/3247
=> DGS-16603 Allow oneofs to be flattened in Protobuf converter (#41)

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Rule.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
* Ensure register schema request is forwarded correctly
* Add default actions
* Minor reformatting
=> Ensure register schema request is forwarded correctly (#53)

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectsResource.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/protobuf/RestApiTest.java, protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufData.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/diff/Context.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/dynamic/DynamicSchema.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/dynamic/MessageDefinition.java, protobuf-provider/src/test/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaTest.java, protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/AbstractKafkaProtobufDeserializer.java
* DGS-16791 Set field type for enum/message fields
* DGS-16763 Add format query param to APIs that return a schema
=> DGS-16763 Add format query param to APIs that return a schema  (#46)

schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
Fixes https://github.com/confluentinc/schema-registry/issues/3261
=> Use concurrent hash maps in serde members (#61)

json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java, json-schema-provider/src/main/resources/metaschemas/draft/2019-09/meta/applicator, json-schema-provider/src/main/resources/metaschemas/draft/2019-09/meta/content, json-schema-provider/src/main/resources/metaschemas/draft/2019-09/meta/core, json-schema-provider/src/main/resources/metaschemas/draft/2019-09/meta/format, json-schema-provider/src/main/resources/metaschemas/draft/2019-09/meta/meta-data, json-schema-provider/src/main/resources/metaschemas/draft/2019-09/meta/validation, json-schema-provider/src/main/resources/metaschemas/draft/2019-09/schema, json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/JsonSchemaTest.java
* DGS-17852 Prepopulate JSON Schema 2019-09 metaschemas
* Fix findbugs
=> DGS-17852 Prepopulate JSON Schema 2019-09 metaschemas (#63)

client-encryption/src/test/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutorTest.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java
* Add JSON ref test
* Add avro test
=> Add CSFLE test for JSON Schema with references (#69)

pom.xml
* Upgrade tink to 1.14.1
* Minor fix
=> Upgrade tink to 1.14.1 (#71)

pom.xml
Fix CVE for azure-identity - https://confluentinc.atlassian.net/browse/DGS-17981
=> DGS-17981 Fix CVE for azure-identity

core/src/test/java/io/confluent/kafka/schemaregistry/rest/protobuf/RestApiTest.java
Clean up test to make it more clear what is used for metadata/version on each request
=> MINOR test cleanup (#79)

core/src/main/java/io/confluent/kafka/schemaregistry/storage/FilteredIterator.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/encoder/MetadataEncoderService.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiMetadataEncoderTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/storage/encoder/MetadataEncoderServiceTest.java
Add code to ensure encoders are synced when decoding sensitive metadata
=> DGS-18832 Ensure encoders are synced when decoding sensitive metadata

avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java, avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerializer.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/FilteredIterator.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/encoder/MetadataEncoderService.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiMetadataEncoderTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/storage/encoder/MetadataEncoderServiceTest.java, json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaDeserializer.java, json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaSerializer.java, protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/AbstractKafkaProtobufDeserializer.java, protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/AbstractKafkaProtobufSerializer.java, schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall
=> Merge Conflict Resolution (from 7.4.x to 7.5.x)

avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/GenericAvroSerde.java, avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/PrimitiveAvroSerde.java, avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/ReflectionAvroSerde.java, avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/SpecificAvroSerde.java, client-encryption-hcvault/src/main/java/io/confluent/kafka/schemaregistry/encryption/hcvault/HcVaultKmsClient.java, client/src/main/java/io/confluent/kafka/schemaregistry/utils/BoundedConcurrentHashMap.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaIdAndSubjects.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/serialization/Serializer.java, dek-registry-client/src/main/java/io/confluent/dekregistry/client/MockDekRegistryClientFactory.java
cherry pick commit 93db043 to 7.8.x
=> Fix javadoc annotations to have no errors

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe.java
Retry on 500, which can be returned when failing to forward request to leader.
=> DGS-19077 Retry on 500

package-kafka-serde-tools/pom.xml
Add kafka tools dependency to allow avro console consumer to run (missing deps)
=> Added kafka-tools dependency (#3404)

json-schema-provider/pom.xml, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchemaUtils.java, pom.xml
Replace mbknor dependency with one that does not rely on Scala.
=> Remove scala dependency for mbknor library

pom.xml
This reverts commit b678b10f79aa8d76c5178a10494d2c98dee21890.
=> Revert "Upgrade json-schema to 1.14.4 (#3400)"

client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java, schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutorTest.java
This reverts a optimization which caused definitions in a JSON Schema to no longer be visited during field transformations.
=> DGS-19185 Fix transformation of fields in JSON Schema definitions

client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java
What
----
Fix NPE when processing "format" query parameter
Checklist
- No
- No
- Yes
- No
References
----------
JIRA:
Test & Review
------------
=> MINOR fix for NPE

core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> MINOR Fix pint merge issue

client-encryption-aws/pom.xml, client-encryption-aws/src/main/java/io/confluent/kafka/schemaregistry/encryption/aws/AwsKmsAead.java, client-encryption-aws/src/main/java/io/confluent/kafka/schemaregistry/encryption/aws/AwsKmsClient.java, client-encryption-aws/src/main/java/io/confluent/kafka/schemaregistry/encryption/aws/AwsKmsDriver.java, client-encryption-aws/src/test/java/io/confluent/kafka/schemaregistry/encryption/aws/FakeAwsKms.java, pom.xml
AWS SDK v1 will be EOL at end of 2025.
This PR is based on existing code used with Confluent Cloud.
What
----
Checklist
- The following can be specified with CSFLE, `role.arn`, `role.session.name`, and `role.external.id`.  This will be added to docs.
- No
- This refactoring is covered by existing unit and integration tests.
- No
References
----------
JIRA:
Test & Review
------------
=> Port AWS KMS integration code to AWS SDK v2

avro-serializer/src/test/java/io/confluent/kafka/serializers/KafkaAvroSerializerTest.java, pom.xml
What
----
Adds a test that identifies a regression in Avro 1.12.0.  This is similar to the KSQL test that was failing.  This test passes in Avro 1.11.4
Also remove the pin to Avro 1.11.4
Checklist
References
----------
JIRA:
Test & Review
------------
=> Add avro array test

client-encryption-aws/src/main/java/io/confluent/kafka/schemaregistry/encryption/aws/AwsKmsDriver.java
What
----
Minor enhancement to allow AWS profile to be specified.  This was tested manually with profiles in a local AWS credentials file
Checklist
- This will be added to docs
- No
- Tested manually with profiles in a local AWS credentials file
- No
References
----------
JIRA:
Test & Review
------------
=> Minor enhancement to allow AWS profile to be specified

core/src/test/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClientTest.java
What
----
Minor enhancement to CompositeDeserializer test 
Checklist
References
----------
JIRA:
Test & Review
------------
=> Minor enhancement to CompositeDeserializer test

core/src/test/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClientTest.java
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> MINOR remove unneeded imports from test

core/src/test/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClientTest.java, schema-serializer/src/main/java/io/confluent/kafka/serializers/wrapper/CompositeDeserializer.java, schema-serializer/src/main/java/io/confluent/kafka/serializers/wrapper/CompositeDeserializerConfig.java
Change to package name wrapper, since we plan to have a few other serdes that wrap others
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> MINOR rename package from migration to wrapper

json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java, json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/JsonSchemaTest.java
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> Fix pint merge 7.9.x to master

json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/JsonSchemaTest.java
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> Fix pint merge issue

protobuf-provider/src/test/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaTest.java
What
----
Add test to ensure Protobuf map entry option is preserved.
Checklist
References
----------
JIRA:
Test & Review
------------
=> Add test to ensure Protobuf map entry option is preserved

client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClientConfig.java
What
----
Change max retry default from 2 to 3 based on internal review.
Checklist
References
----------
JIRA:
Test & Review
------------
=> Minor change to default for client retries

json-schema-provider/pom.xml, pom.xml
What
----
Fix a performance regression in a 3rd party JSON Schema library.
Checklist
- No
- No
- Covered by existing tests
- No
References
----------
JIRA:
Test & Review
------------
=> Fix JSON Schema dependency

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RetryExecutor.java, client/src/test/java/io/confluent/kafka/schemaregistry/client/rest/RetryExecutorTest.java
What
----
Fix retry logic for callables that return void
Checklist
- No
- No
- Yes
- No
References
----------
JIRA:
Test & Review
------------
=> Fix retry logic for callables that return void

json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java, json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/JsonSchemaTest.java
What
----
git cherry-pick 25ea901 to 7.6.2-cp1
Checklist
References
----------
JIRA:
Test & Review
------------
=> Cherry pick json schema fix to hotfix branch 7.6.2-cp1

core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> DGS-19204: Prioritize the Shutdown of the Leader Elector

client/src/main/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/oauth/SaslOauthCredentialProvider.java
What
----
Update package path (previous package is [deprecated](https://kafka.apache.org/35/javadoc/org/apache/kafka/common/security/oauthbearer/secured/OAuthBearerLoginCallbackHandler.html))
Checklist
- **No code changes**
References
----------
JIRA:
[build-test-release](https://semaphore.ci.confluent.io/workflows/9a45cdf4-e86d-4a44-8aee-6ed037336a54?pipeline_id=37849613-42d8-4338-8c17-e63bf76e558c) failure.
https://confluent.slack.com/archives/CLQ1C50JU/p1734531453879229
Test & Review
------------
=> Fix deprecated OAuthBearerLoginCallbackHandler

core/src/test/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClientTest.java, schema-serializer/src/main/java/io/confluent/kafka/serializers/wrapper/CompositeDeserializer.java, schema-serializer/src/main/java/io/confluent/kafka/serializers/wrapper/CompositeDeserializerConfig.java
What
----
Minor renaming of configs for Composite Deserializer.  (This has not yet been released).
Checklist
References
----------
JIRA:
Test & Review
------------
=> Minor renaming of configs for Composite Deserializer

jacoco-aggregate-schema-registry/pom.xml
What
----
Parent POM version inconsistency caused by pint merging a new module.
Checklist
- **No code change**
References
----------
JIRA:
Test & Review
------------
=> Fix parent POM version in new module

service.yml
This PR modifies service.yml to add cp jar build block in semaphore.yml to trigger cp jar build job on every PR build.
After merging the PR, cc-service-bot (which manages cp projects semaphore.yml) will be invoked on this repo to add [cp-jar-build](https://confluentinc.atlassian.net/browse/CP-jar-build) block in master branch.
Checklist
References
----------
JIRA:
Test & Review
------------
=> CPBR-2064: enabling cp jar build through service.yml

.semaphore/semaphore.yml, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStore.java
What
----
https://github.com/confluentinc/ce-kafka/blame/d6b98098bf5eb5ae17ca3b9afd20b1f9d30fa88c/clients/src/main/java/org/apache/kafka/clients/admin/DescribeTopicsResult.java#L99
This func has been removed (prev deprecated)
Also bump to 17 or compilation failure
Checklist
References
----------
JIRA:
Test & Review
------------
=> Fix compilation

protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java, protobuf-provider/src/test/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaTest.java
What
----
When generating a Protobuf descriptor, properly initialize the context with the package name of the nested type.
Fixes https://github.com/confluentinc/schema-registry/issues/3499
Checklist
- No
- No
- Yes
- No
References
----------
JIRA:
Test & Review
------------
=> DGS-19444 Fix handling of nested Protobuf types when generating descriptor

avro-serializer/src/test/java/io/confluent/kafka/formatter/KafkaAvroFormatterTest.java, schema-serializer/src/main/java/io/confluent/kafka/formatter/SchemaMessageReader.java
What
----
Ensure message reader can return multiple records.  This is to handle changes due to KIP-641 where the new contract allows the RecordReader to return multiple records instead of just a single record.
Checklist
- No
- Yes
References
----------
JIRA:
Test & Review
------------
=> Ensure message reader can return multiple records

avro-serializer/src/test/java/io/confluent/kafka/formatter/KafkaAvroFormatterTest.java
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> MINOR fix build for JDK 17

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
What
----
Making a private method protector for access in a unit test
=> making buildConnectionProtected

pom.xml
What
----
Upgrade kcache.  The latest version uses idempotent writes.
Checklist
References
----------
JIRA:
Test & Review
------------
=> MINOR Upgrade KCache to 5.2.0

core/pom.xml
What
----
Fix CVE-2023-1932 in 7.0.x
Checklist
- If not, please explain why it is not required - This removes a package for CVE. Existing unit and integration tests is sufficient
References
----------
JIRA: https://confluentinc.atlassian.net/browse/DGS-19193
Test & Review
------------
Existing unit and integration should be sufficient.
=> DGS-19193 Fix CVE-2023-1932 in 7.0.x

core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java
What
----
set default pagination values for subjects to INT_MAX
Checklist
References
----------
JIRA:
Test & Review
------------
=> DGS-10785: set pagination limit for subjects to INT_MAX

core/src/test/java/io/confluent/kafka/schemaregistry/LeaderElectorTest.java
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> Attempt to reenable possibly flakey test

.semaphore/semaphore.yml, service.yml
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> Use JDK 17 for 8.0.0

core/src/test/java/io/confluent/kafka/schemaregistry/SASLClusterTestHarness.java
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> Remove use of ZK in SASL cluster tests

json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java, json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/JsonSchemaTest.java
What
----
Fix inline tag retrieval for JSON Schema with null in array (which itself is in a definition).
Checklist
- Yes
References
----------
JIRA:
Test & Review
------------
=> DGS-19669 Fix inline tag retrieval for JSON Schema with null in array

client/src/main/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/oauth/OauthCredentialProvider.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/oauth/SaslOauthCredentialProvider.java
This PR leverages the changes made in https://github.com/confluentinc/schema-registry/pull/3538 and adds the fix in additional flows.
Checklist
References
----------
JIRA:
Test & Review
------------
=> Bouncy Castle and SunJSSE compatibility fix (additional flows)

json-schema-converter/pom.xml, json-schema-provider/pom.xml, pom.xml
What
----
Fixes https://github.com/confluentinc/schema-registry/issues/3536
Checklist
References
----------
JIRA:
Test & Review
------------
=> Upgrade everit json-schema to 1.14.5

pom.xml
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> Fix pint merge 7.3.x to 7.4.x

.gitignore, client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaMetadata.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/ContextId.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/ExtendedSchema.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Schema.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaString.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/RegisterSchemaResponse.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/exceptions/Errors.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SchemasResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectsResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/InMemoryCache.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/LookupCache.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/MD5.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
What
----
Add support for schema guids that are stable across contexts. The guid is a 32 character hex string, such as
`6da336d8-f1d3-0f98-4c47-d03ee8a14a1`.  Internally it is derived from the MD5 hash of the schema.
For CP 8.0, this PR adds two new REST APIs:
`GET /schemas/guids/{guid}` - return the schema with a given guid
`GET /schemas/guids/{guid}/ids` - return all ids (and corresponding contexts) for the given guid
Checklist
- Yes, the APIs mentioned above
- Yes
References
----------
JIRA:
Test & Review
------------
=> DGS-19689 Add support for schema guids that are stable across contexts

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaString.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/RegisterSchemaResponse.java
What
----
Add some copy helper methods for easier maintenance.
Checklist
References
----------
JIRA:
Test & Review
------------
=> MINOR add copy helper methods

checkstyle/suppressions.xml, client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaMetadata.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Schema.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaString.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/RegisterSchemaResponse.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaValue.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
What
----
Return creation time for schemas via REST API.  The creation time appears as a new JSON property `ts`.
Checklist
- Yes
- Yes
References
----------
JIRA:
Test & Review
------------
=> DGS-19702 Return creation time for schemas via REST API

client/src/main/java/io/confluent/kafka/schemaregistry/utils/QualifiedSubject.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/filters/AliasFilter.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/filters/AliasNonDefaultTenantFilterTest.java
What
----
Ensure the subject in DEK urls is replaced by any applicable aliases.  For Confluent Cloud, the DEK subject is not qualified by the tenant.
Checklist
- Yes
References
----------
JIRA:
Test & Review
------------
=> DGS-19729 Ensure that DEK lookups use applicable aliases

client/src/test/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/BearerAuthCredentialProviderFactoryTest.java, client/src/test/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/oauth/SaslOauthCredentialProviderTest.java
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> Fix OAuth tests due to AK changes

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
What
----
Reverts the bouncy castle related changes from 7.9 and above, as they are only needed for jdk8 which has been deprecated.
Checklist
References
----------
JIRA:
Test & Review
------------
=> reverting changes on 7.9 and above

pom.xml
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> Upgrade commons.validator to 1.9.0

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, core/generated/swagger-ui/schema-registry-api-spec.yaml, core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ContextsResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SchemasResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectVersionsResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> DGS-19655: Pagination of SR APIs (Subject and Schema)

pom.xml
Cel 0.5.0+ requires Protobuf 4
Jsonata 2.4.6+ requires JDK 11+
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> Upgrade cel to 0.5.1; jsonata to 2.5.1

pom.xml
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> Upgrade json-skema to 0.20

pom.xml
What
----
Upgrade Tink to 1.16 (requires Protobuf 4)
Checklist
References
----------
JIRA:
Test & Review
------------
=> Upgrade Tink to 1.16

core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> Convert test to JUnit5 to fix build

pom.xml, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtoFileElementDeserializer.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java
What
----
Upgrade to wire 5.3.0 (requires JDK 17)
Checklist
References
----------
JIRA:
Test & Review
------------
=> Upgrade to wire 5.3.0

core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiCompatibilityTest.java
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> DGS-19699 Enhance integration test w/additional lookup

dek-registry/src/test/java/io/confluent/dekregistry/storage/DekRegistryTest.java, dek-registry/src/test/java/io/confluent/kafka/schemaregistry/rest/client/LocalSchemaRegistryClientTest.java
What
----
Checklist
- [N ] Contains customer facing changes? Including API/behavior changes 
- [N] Is this change gated behind feature flag(s)?
- [Y] Did you add sufficient unit test and/or integration test coverage for this PR?
References
----------
JIRA:
[DGS-19622](https://confluentinc.atlassian.net/browse/DGS-19622)
Cherry-pick this commit: https://github.com/confluentinc/schema-registry/pull/3566
Test & Review
------------
[DGS-19622]: …
=> add missing tests for DekRegistry

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RetryExecutor.java, client/src/test/java/io/confluent/kafka/schemaregistry/client/rest/RetryExecutorTest.java
What
----
Checklist
References
----------
JIRA: [DGS-19791](https://confluentinc.atlassian.net/browse/DGS-19791)
Test & Review
------------
[DGS-19791]: https://confluentinc.atlassian.net/browse/DGS-19791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DGS-19791: Add retry for schema exporter upon IOException

core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistryTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/storage/StoreUtils.java
What
----
DGS-19622
Checklist
- [Y] Did you add sufficient unit test and/or integration test coverage for this PR?
References
----------
JIRA: [DGS-19622](https://confluentinc.atlassian.net/browse/DGS-19622)
Test & Review
------------
[DGS-19622]: https://confluentinc.atlassian.net/browse/DGS-19622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …
=> Improve test coverage (no feature change)

bin/kafka-avro-console-producer, bin/kafka-json-schema-console-producer, bin/kafka-protobuf-console-producer, core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistryTest.java
Also port test to JUnit5 to fix master build
What
----
Checklist
- No
- No
- No, just fixing existing tests
- No
References
----------
JIRA:
Test & Review
------------
=> MINOR fix to console producers due to AK changes

client-encryption-gcp/pom.xml, pom.xml
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> Update deps for CSPs

jacoco-aggregate-schema-registry/pom.xml
What
----
DGS-19622
Checklist
- [N/A] Did you add sufficient unit test and/or integration test coverage for this PR?
References
----------
JIRA: DGS-19622
Test & Review
------------
=> add dek-registry module for coverage aggregation

pom.xml
What
----
Exclude javapoet dependency from wire. It is not used and requires Java 17.
Checklist
References
----------
JIRA:
Test & Review
------------
=> Exclude javapoet dependency from wire (requires Java 17)

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Rule.java, dek-registry/src/main/java/io/confluent/dekregistry/web/rest/resources/DekRegistryResource.java
What
----
Increase max length for kek and rule names
Checklist
References
----------
JIRA:
Test & Review
------------
=> DGS-19866 Increase max length for kek and rule names

client-encryption-aws/pom.xml, pom.xml
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> Upgrade to aws sdk 2.30.33

core/src/test/java/io/confluent/kafka/schemaregistry/rest/client/LocalSchemaRegistryClientTest.java
What
----
Checklist
- [N/A] Did you add sufficient unit test and/or integration test coverage for this PR?
References
----------
JIRA: DGS-19622
Test & Review
------------
=> Update test to use qualified subject names and fix a typo

core/src/test/java/io/confluent/kafka/schemaregistry/rest/client/LocalSchemaRegistryClientTest.java
What
----
Manually merge 7.9.x to master due to conflicts
Checklist
- [N/A] Did you add sufficient unit test and/or integration test coverage for this PR?
- [N/A] Does this change require modifying existing system tests or adding new system tests? 
References
----------
JIRA: DGS-19622
Test & Review
------------
=> manually merge 7.9.x to master due to conflicts 

avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/GenericAvroDeserializer.java, avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/GenericAvroSerde.java, avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/GenericAvroSerializer.java, avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/ReflectionAvroDeserializer.java, avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/ReflectionAvroSerde.java, avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/ReflectionAvroSerializer.java, avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/SpecificAvroDeserializer.java, avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/SpecificAvroSerde.java, avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/SpecificAvroSerializer.java
What
----
Remove unstable annotation from Avro serdes
Checklist
References
----------
JIRA:
Test & Review
------------
=> DGS-15309 Remove unstable annotation from Avro serdes

pom.xml
What
----
Upgrade Tink to 1.17.0
Checklist
References
----------
JIRA:
Test & Review
------------
=> Upgrade Tink to 1.17.0

client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaMetadata.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Schema.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaString.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/RegisterSchemaResponse.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaValue.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
What
----
Return deleted flag for schemas via REST API.
Checklist
References
----------
JIRA:
Test & Review
------------
=> DGS-19997 Return deleted flag for schemas via REST API

checkstyle/suppressions.xml, client-encryption/src/main/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutor.java, client/src/main/java/io/confluent/kafka/schemaregistry/rules/DlqAction.java, client/src/main/java/io/confluent/kafka/schemaregistry/rules/FieldRedactionExecutor.java, client/src/test/java/io/confluent/kafka/schemaregistry/rules/FieldRedactionExecutorTest.java
What
----
Ensure sensitive fields are redacted when using the DLQ Action.  Also some minor refactoring of FieldEncryptionExecutor. 
Checklist
References
----------
JIRA:
Test & Review
------------
=> DGS-19566 Redact sensitive fields in the DLQ Action

client-encryption/src/main/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutor.java
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> MINOR refactoring to match other repos

protobuf-types/src/main/proto/confluent/type/decimal.proto
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> MINOR enhance precision comment in decimal.proto

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Metadata.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Schema.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaReference.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaTags.java, client/src/test/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaTest.java
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> DGS-19765: deep copy for Schema

core/src/main/java/io/confluent/kafka/schemaregistry/rest/filters/ContextFilter.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/filters/ContextFilterTest.java
What
----
Handle URL-encode paths in ContextFilter 
Checklist
References
----------
JIRA:
Test & Review
------------
=> DGS-20112 Handle URL-encoded paths in ContextFilter

client/src/test/java/io/confluent/kafka/schemaregistry/client/rest/RestServiceTest.java, json-schema-serializer/src/test/java/io/confluent/kafka/serializers/json/KafkaJsonSchemaSerializerTest.java
What
----
adding unit test against this pr change https://github.com/confluentinc/schema-registry/pull/3201
Checklist
References
----------
JIRA:
Test & Review
------------
=> Dgs 19226 adding retry test for ser/de/restservice

dek-registry-client/pom.xml, dek-registry-client/src/main/java/io/confluent/dekregistry/client/rest/entities/CreateKekRequest.java, dek-registry-client/src/test/java/io/confluent/dekregistry/client/rest/entities/CreateKekRequestTest.java, dek-registry/src/main/java/io/confluent/dekregistry/web/rest/resources/DekRegistryResource.java
Add minimal validation for certain KMS key IDs when creating KEKs in the DEK Registry.
KMS key ids are ultimately validated when used by the KMS client. However, for the KMS types that we support, add some minimal validation (such as ensuring an ARN has a correct prefix).
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> DGS-20245 Add minimal validation for certain KMS key IDs

client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClientFactory.java, client/src/main/java/io/confluent/kafka/schemaregistry/testutil/MockSchemaRegistry.java
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> dgs-19987 add new cache schema registry method

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/RuleSet.java
What
----
Add RuleSet.isEmpty method for use in `schema-registry-plugins`
Checklist
References
----------
JIRA:
Test & Review
------------
=> Add RuleSet.isEmpty method

core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java
What
----
fix merge conflict from 7.7.x caused by https://github.com/confluentinc/schema-registry/pull/3664
Checklist
References
----------
JIRA:
Test & Review
------------
=> Dgs 20029 pint merge fix

avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroDeserializer.java
What
----
Fixes https://github.com/confluentinc/schema-registry/issues/3671
Checklist
References
----------
JIRA:
Test & Review
------------
=> Minor optimization in KafkAvroDeserializer.config

pom.xml
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> Upgrade mbknor library to 1.0.39.3

json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java, schema-rules/src/test/java/io/confluent/kafka/schemaregistry/rules/cel/CelExecutorTest.java
What
----
Ignore JSON schema fields not in the Java class
Checklist
References
----------
JIRA:
Test & Review
------------
=> DGS-20417 Ignore JSON schema fields not in the Java class

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Schema.java
Don't include the guid in equals/hashCode since it is derived from other existing properties
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> Minor optimization to schema entity

schema-serializer/src/main/java/io/confluent/kafka/serializers/schema/id/SchemaId.java
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> Minor fix for NPE during SchemaId constructor

core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryRestApplication.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryExtensionTest.java
What
----
add support for adding custom handler
Checklist
- [ y] Contains customer facing changes? Including API/behavior changes 
References
----------
JIRA:
Test & Review
------------
=> Add support for hybrid handler

pom.xml
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> Downgrade aws sdk v2 to match kafka on 7.7.x

pom.xml
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> Use aws-java-sdk-v2.version from common

client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClientConfig.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClientFactory.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/utils/UrlList.java, client/src/test/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClientTest.java, client/src/test/java/io/confluent/kafka/schemaregistry/client/rest/RestServiceTest.java, client/src/test/java/io/confluent/kafka/schemaregistry/client/rest/utils/UrlListTest.java, schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDeConfig.java
What
----
Added a new SR client config `schema.registry.url.randomize` with default value of false to enable more predictable client behavior to help with analyzing traffic patterns on the server-side.
Checklist
References
----------
JIRA: [DGS-20482](https://confluentinc.atlassian.net/browse/DGS-20482)
Test & Review
------------
Uploaded custom image to the [devel DSKU kafka used for PL SV tests](https://confluentinc.atlassian.net/wiki/spaces/DG/pages/4257874447/PL4SR+Post-GA+-+Validating+Soft-migrate+LA+DSKU+Kafka+SR+API+Key+Endpoint#Synthetic-Testing) and validated using …
=> DGS-20482: Start with first URL in UrlList

core/src/main/java/io/confluent/kafka/schemaregistry/rest/exceptions/RestInvalidModeException.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ModeResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/Mode.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiModeTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java, dek-registry/src/main/java/io/confluent/dekregistry/storage/DekRegistry.java
What
----
Checklist
References
----------
JIRA:
adding forward mode, currently same behavior as import mode, hybrid handler will only forward if the SR is in forward mode
Test & Review
------------
=> add Forward mode

config/log4j2.yaml, core/src/main/resources/log4j2.yaml, core/src/test/resources/log4j2.yaml
What
----
https://confluent.slack.com/archives/C027DGB2EHG/p1745494414388649?thread_ts=1745236041.810879&cid=C027DGB2EHG
8.0.x has no zookeeper
Checklist
References
----------
JIRA:
Test & Review
------------
=> Remove zookeeper references in log4j

client/pom.xml, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/ConfigUpdateRequest.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/ModeUpdateRequest.java, client/src/main/java/io/confluent/kafka/schemaregistry/utils/JacksonMapper.java, client/src/test/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClientTest.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryRestApplication.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/client/LocalSchemaRegistryClient.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ConfigResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ModeResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/ConfigValue.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/RuleSetHandler.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiCompatibilityTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiModeTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistryTest.java, dek-registry-client/src/main/java/io/confluent/dekregistry/client/rest/entities/UpdateKekRequest.java, dek-registry/src/main/java/io/confluent/dekregistry/storage/DekRegistry.java, dek-registry/src/test/java/io/confluent/dekregistry/storage/DekRegistryTest.java, findbugs/findbugs-exclude.xml
What
----
Distinguish between null and missing props for PUT.  We use Optional to do this, which requires Jackson support via the Jdk8Module.
Checklist
References
----------
JIRA:
Test & Review
------------
=> DGS-20545 Distinguish between null and missing props for PUT

core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfig.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ModeResource.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryConfigTest.java
What
----
https://github.com/apache/kafka/commit/1c82b89b4cf 
https://github.com/apache/kafka/commit/ceac4f0a1d1
two kafka class is removed from the latest, i am removing an unused method in SR to pass the build failure
Checklist
References
----------
JIRA:
Test & Review
------------
=> remove unused method to resolve kafka build failure

client-encryption-gcp/pom.xml, pom.xml
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> Bump dependency versions for GCP

core/src/test/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryErrorHandlerTest.java
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> Fix reference to Jetty JAAS class

.github/pull_request_template.md
What
----
For PR checklist, a limitation of the current checkbox style is that an unchecked box doesn't clearly indicate if the item is not applicable or simply not yet done.
The change is to use freeform text (Y, N, N/A) instead of checkbox. It's a small adjustment but brings more clarity.
Checklist
- [N/A] Did you add sufficient unit test and/or integration test coverage for this PR? …
=> Adjust the PR template to use freeform text instead of checkbox

client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java, client/src/test/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClientTest.java
What
----
For CP 8.0, when registering a schema, the version is returned.  However, this is not the case for CP 7.x.x.  Therefore when looking up a schema, skip the cached entry if it does not have a version.
Checklist
- \[] Contains customer facing changes? Including API/behavior changes 
- \[ ] Is this change gated behind config(s)?
- \[x] Did you add sufficient unit test and/or integration test coverage for this PR?
- \[ ] Does this change require modifying existing system tests or adding new system tests? 
References
---------- …
=> DGS-20647 Ensure SR client cache for CP 8.0 is backward compat with 7.x.x

.github/pull_request_template.md
What
----
Adjust the format of the PR template to remove checkbox.
A previous change didn't remove the checkbox due to a formatting issue.
Checklist
- \[N] Contains customer facing changes? Including API/behavior changes 
- \[N/A] Is this change gated behind config(s)?
- \[N/A] Did you add sufficient unit test and/or integration test coverage for this PR?
- \[N] Does this change require modifying existing system tests or adding new system tests? 
References
----------
JIRA:
Test & Review
------------ …
=> Adjust the format of the PR template to remove checkbox

schema-serializer/src/main/java/io/confluent/kafka/serializers/schema/id/PrefixSchemaIdSerializer.java, schema-serializer/src/main/java/io/confluent/kafka/serializers/schema/id/SchemaId.java
What
----
Minor optimization for Protobuf message index serialization 
Checklist
- \[ ] Contains customer facing changes? Including API/behavior changes 
- \[ ] Is this change gated behind config(s)?
- \[ ] Did you add sufficient unit test and/or integration test coverage for this PR?
- Covered by existing test suites
- \[ ] Does this change require modifying existing system tests or adding new system tests? 
References
----------
JIRA:
Test & Review
------------
=> Minor optimization for Protobuf message index serialization

core/src/test/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClientTest.java, schema-serializer/src/main/java/io/confluent/kafka/serializers/wrapper/CompositeDeserializer.java
What
----
Minor enhancement to CompositeDeserializer to handle when the schema ID is in the header.  We use a DualSchemaIdDeserializer, which first checks the header for a schema ID, then the payload prefix.
Checklist
- **[x]** Contains customer facing changes? Including API/behavior changes 
- **[x]** Did you add sufficient unit test and/or integration test coverage for this PR?
References …
=> Minor enhancement to CompositeDeserializer to handle headers

pom.xml
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> Upgrade everit json-schema to 1.14.6

pom.xml
What
----
Checklist
References
----------
JIRA:
Test & Review
------------
=> Fix json-schema versions in pom due to merge conflict

client/src/main/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/oauth/CachedOauthTokenRetriever.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/oauth/OauthCredentialProvider.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/oauth/SaslOauthCredentialProvider.java, client/src/test/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/oauth/CachedOauthTokenRetrieverTest.java
What
----
OAuth Kafka classes are renamed here https://github.com/apache/kafka/pull/19622
Made the following changes:
`AccessTokenRetriever` → `JwtRetriever`
`AccessTokenValidator` → `JwtValidator`
`HttpAccessTokenRetriever` → `HttpJwtRetriever`
`LoginAccessTokenValidator` → `ClientJwtValidator`
Checklist
- **[N]** Does this change require modifying existing system tests or adding new system …
=> Fix build by renaming oauth kafka classes

core/pom.xml
What
----
logredactor library is using log4j 1 APIs, we should add as a dependency
Checklist
References
----------
JIRA:
Test & Review
------------
=> Add log4j-1.2-api dependency to SR

core/pom.xml
What
----
Same log4j dependency is required in 8.0.x.
Checklist
References
----------
JIRA:
Test & Review
------------
=> Add log4j-1.2-api dependency to SR (#3734)

avro-converter/src/main/java/io/confluent/connect/avro/AvroConverter.java, json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaConverter.java, protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufConverter.java
What
----
This PR makes changes to fromConnectData and toConnectData methods in converters, so that they return different types of exceptions based on the underlying cause of SerializationException:
- `java.io.IOException` -> `org.apache.kafka.connect.errors.ConnectException`
- Others caused related to failures in serializing/deserializing data -> `org.apache.kafka.connect.errors.DataException`
Checklist
- If not, please explain why it is …
=> DGS-20716: send ConnectException for IO exceptions in connect converters 

json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaData.java, json-schema-converter/src/test/java/io/confluent/connect/json/JsonSchemaConverterTest.java, json-schema-converter/src/test/java/io/confluent/connect/json/JsonSchemaDataTest.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/diff/SchemaDiff.java, json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/diff/SchemaDiffTest.java
What
----
Generate correct field type for Decimal in JSON converter to be a string unless the decimal.format is NUMERIC.  Also updated the backward compatible check to accommodate this fix.
Also updated some tests to use schema validation.
Checklist
- If so, include tracking information for the …
=> DGS-20917 Generate correct field type for Decimal in JSON converter

.github/pull_request_template.md
What
----
Update PR template to include related changes
Checklist
- **[N/A]** Is this change gated behind config(s)?
References
----------
JIRA:
Test & Review
------------
=> Update PR template to include related changes

client/src/main/java/io/confluent/kafka/schemaregistry/ParsedSchema.java, json-serializer/src/main/java/io/confluent/kafka/serializers/KafkaJsonDeserializerConfig.java
What
----
cherry pick 8.0.x change into master
Checklist
- **[n ]** Contains customer facing changes? Including API/behavior changes 
- **[ n]** Is this change gated behind config(s)?
- **[ n]** Did you add sufficient unit test and/or integration test coverage for this PR?
- **[n ]** Does this change require modifying existing system tests or adding new system tests? 
- **[ n]** Must this be released together with other change(s), either in this repo or another one?
- If so, please include the link(s) to the changes that must be …
=> add javadoc as part of the maven build (#3758)

client/src/main/java/io/confluent/kafka/schemaregistry/ParsedSchema.java
What
----
Checklist
References
----------
JIRA: …
=> javadoc fix in ParsedSchema

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/exceptions/Errors.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/exceptions/RestContextNotEmptyException.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/filters/ContextFilter.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ContextsResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaRegistry.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiContextTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/filters/ContextFilterTest.java
What
----
Add REST API to delete context.  Succeeds only if the context to be deleted is empty.
Checklist
- If so, please include the …
=> DGS-20674 Add REST API to delete context

client-encryption-tink/pom.xml, client-encryption/pom.xml, pom.xml, schema-rules/pom.xml
0.9.16 uses protobuf-java 3.23.3
Also add some explicit dependencies to protobuf-java to ensure the correct version is used
What
----
Checklist
- **[N/A]** Does this change require modifying existing system tests or adding new system tests? 
- **[N]** Must this be released together with other change(s), either in this repo …
=> DGS-21208 Upgrade jackson-datatype-protobuf to 0.9.16

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, client/src/main/java/io/confluent/kafka/schemaregistry/utils/QualifiedSubject.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ConfigResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ModeResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/InMemoryCache.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/Mode.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiCompatibilityTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiModeTest.java
What
----
Support a true global config/mode, using a special global context named `:.__GLOBAL:`.   Now when looking up a config/mode with `defaultToGlobal`, the lookup will proceed from the subject, to the context, and then to global context (`:.__GLOBAL:`).  The global context is only valid for config/mode, it cannot be used to store subjects/schemas.
Checklist
- **[N]** Does this change …
=> DGS-21192 Support a true global config/mode

core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiCompatibilityTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiModeTest.java
What
----
Upgrade test to Junit 5 after merge
Checklist
- If so, please include the link(s) to the changes that must be released …
=> Minor fix to upgrade test to Junit 5 

avro-converter/pom.xml, avro-converter/src/main/java/io/confluent/connect/avro/AvroConverter.java, avro-converter/src/test/java/io/confluent/connect/avro/AvroConverterTest.java, core/generated/swagger-ui/schema-registry-api-spec.yaml, json-schema-converter/src/main/java/io/confluent/connect/json/JsonSchemaConverter.java, json-schema-converter/src/test/java/io/confluent/connect/json/JsonSchemaConverterTest.java, protobuf-converter/src/main/java/io/confluent/connect/protobuf/ProtobufConverter.java, protobuf-converter/src/test/java/io/confluent/connect/protobuf/ProtobufConverterTest.java
What
----
As requested by the Connect team (see discussion in DG-20716), we will throw `NetworkException` instead of `ConnectException` (previous PR: https://github.com/confluentinc/schema-registry/pull/3738) for IO exceptions in converters used by Connect, as `ConnectException` is used frequently by Connect for other scenarios. After this change:
- java.io.IOException -> org.apache.kafka.common.errors.NetworkException
- Others caused related to failures in serializing/deserializing data -> org.apache.kafka.connect.errors.DataException
Checklist
- Change in type of exception thrown for a specific case in Connect converters. See the …
=> DGS-20716: send NetworkException instead of ConnectionException for IO exceptions in Connect converters 

client/pom.xml, client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClientConfig.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, client/src/test/java/io/confluent/kafka/schemaregistry/client/rest/ApacheClientRestServiceTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/RestApp.java, pom.xml
What
----
Added an additional config for clients to run off the Http Apache Client instead of HttpUrlConnection.
Checklist
- **[Y ]** Contains customer facing changes? Including API/behavior changes 
- **[Y]** Is this change gated behind config(s)?
- Add Apache client config to Schema Registry Configs
- **[ Y ]** Did you add sufficient unit test and/or integration test coverage for this PR?
- **[ N]** Does this change require modifying existing system tests or adding new system tests? 
- Needed for when a full migration occurs
- **[ N]** Must this be released together with other change(s), either in …
=> Add additional config for Apache Http Client

client/src/test/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/filters/AliasNonDefaultTenantFilterTest.java
What
----
Fix license headers in 7.6.x
Checklist
- **[NA]** Did you add sufficient unit test and/or integration test coverage for this PR? …
=> DGS-21256: fix license headers

client/src/main/java/io/confluent/kafka/schemaregistry/utils/QualifiedSubject.java, client/src/test/java/io/confluent/kafka/schemaregistry/utils/QualifiedSubjectTest.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/InMemoryCache.java
Also enhance check for the global context ":.__GLOBAL:"
What
----
Checklist
- If so, please include the link(s) to the changes that …
=> Minor refactor to subject in context check

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistryTest.java
What
----
Always add X-Forward header to request forwarded to leader and remove the limitaiton based on whitelist
Checklist
- **[X]** Contains customer facing changes? Including API/behavior changes  `No`
- **[X]** Is this change gated behind config(s)? `NO`
- **[X]** Did you add sufficient unit test and/or integration test coverage for this PR? `YES`
- **[X]** Does this change require modifying existing system tests or adding new system tests?  `NO`
- **[X]** Must this be released together with other change(s), either in this repo or …
=> DGS-21340 Always add X-Forward header to request forwarded to leader

client-encryption/src/test/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutorTest.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java
What
----
Fix field traversals when POJO property is missing
Checklist
- If so, please include the link(s) to the changes that must …
=> DGS-20417 Fix field traversals when POJO property is missing

core/src/main/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryRestApplication.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/SchemaRegistryExtensionTest.java
What
----
Configure customer handlers after security handler to ensure authentication is performed before any customer handlers. 
Checklist
- **[X]** Contains customer facing changes? Including API/behavior changes  NO
- **[X]** Is this change gated behind config(s)? Yes, only enabled with custom handlers
- **[X]** Did you add sufficient unit test and/or integration test coverage for this PR? **YES**
- **[X]** Does this change require modifying existing system tests or adding new system tests?  **YES, Muckrake tests will be enhanced to validate this.**
- If so, include tracking information for the …
=> DGS-21443 Configure customer handlers after security handler

json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchemaUtils.java, json-schema-provider/src/test/java/io/confluent/kafka/schemaregistry/json/JsonSchemaTest.java
What
----
Add support for JSON Schema 2020-12 in JsonSchemaUtils
Checklist
- If so, please include the link(s) to the changes that …
=> Add support for JSON Schema 2020-12 in JsonSchemaUtils

client/src/main/java/io/confluent/kafka/schemaregistry/utils/QualifiedSubject.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ModeResource.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiModeTest.java
What
----
enforce forward mode only support for global context
Checklist
- **[y ]** Contains customer facing changes? Including API/behavior changes 
- **[ y]** Is this change gated behind config(s)?
- **[y ]** Did you add sufficient unit test and/or integration test coverage for this PR?
- **[ n]** Does this change require modifying existing system tests or adding new system tests? 
- **[ n]** Must this be released together with other change(s), either in this repo or another one?
- If so, please include the link(s) to the changes that …
=> enfroce forward mode to global context

core/src/main/java/io/confluent/kafka/schemaregistry/rest/RequestHeaderHandler.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RequestHeaderHandlerTest.java
What
----
This was missed during the migration to log4j2 as part of CP 8.x release. Instead of using SLF4J's "MDC", we should be using ThreadContext ([Apache ref](https://logging.apache.org/log4j/2.x/migrate-from-slf4j.html))
Also fix a bunch of broken/commented out tests
Checklist
- If so, …
=> Replace MDC with ThreadContext for LOG4J2 compatibility

core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/test/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistryTest.java
What
---- 
**Bugfix** : Ensure subject-level mode and config are only deleted upon hard subject delete.
**Description** : Previously, when a subject was soft deleted from Schema Registry, its subject-level mode and compatibility config were also removed. This is incorrect—according to expected behavior, only a hard delete (?permanent=true) should result in deletion of subject-level mode and config.
With this fix, soft delete operations on a subject or individual schema version will preserve all subject-level metadata. Subject-level mode and config will be deleted only when the subject itself is hard deleted, ensuring full compliance with Schema Registry API semantics and customer expectations.
Checklist
- …
=> Fix : Subject config and mode should be deleted on hard delete

LICENSE
What
----
Minor fix to LICENSE
Checklist
- **[N/A]** Contains customer facing changes? Including API/behavior changes 
- **[N/A]** Is this change gated behind config(s)?
- **[N/A]** Does this change require modifying existing system tests or adding new system tests? 
- **[N/A]** Must this be released together with other change(s), either in this repo or another one? …
=> Minor fix to LICENSE

client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClient.java, client/src/test/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClientTest.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/client/LocalSchemaRegistryClient.java
What
----
Adding getGuid method to SchemaRegistryClient, as this method is necessary for schema validation.
Checklist
- **[ N]** Contains customer facing changes? Including API/behavior changes 
- **[N ]** Is this change gated behind config(s)?
- **[N]** Did you add sufficient unit test and/or integration test coverage for this PR?
Adding method to base class for schema validation
- If so, …
=> Add getGuid method to SchemaRegistryClient

client-encryption-aws/src/test/java/io/confluent/kafka/schemaregistry/encryption/aws/AwsFieldEncryptionExecutorTest.java, client-encryption/src/main/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutor.java
What
----
Allow alternate KMS key IDs on a KEK
Checklist
- If so, please include the link(s) to the changes that must be released …
=> DGS-21595 Allow alternate KMS key IDs on a KEK

client-encryption/src/test/java/io/confluent/kafka/schemaregistry/encryption/FieldEncryptionExecutorTest.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchema.java
What
----
Checklist
References
----------
JIRA: …
=> DGS-20417 Fix field traversals when POJO property is missing (#3802)

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
What
----
Adding descriptive debug messages to verify behaviour of Apache Http Client.
Checklist
- **[ N]** Contains customer facing changes? Including API/behavior changes 
- **[ N]** Is this change gated behind config(s)?
- **[ N]** Did you add sufficient unit test and/or integration test coverage for this PR?
- **[ N]** Does this change require modifying existing system tests or adding new system tests? 
- **[ N]** Must this be released together with other change(s), either in this repo or another one?
- If so, please include the …
=> Add descriptive logging for use of apache http client

client-encryption/src/main/java/io/confluent/kafka/schemaregistry/encryption/EncryptionExecutor.java
What
----
Minor refactoring to optimize AeadWrapper initialization
Checklist
- If so, please include the link(s) to the changes …
=> Minor optimization to AeadWrapper initialization

json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/jackson/Jackson.java
What
----
Port https://github.com/confluentinc/schema-registry/commit/fbe1f760ec08fe8de739b2f3f8a26b61c6b3e496 to 7.3.x
Checklist
- **[X]** Contains customer facing changes? Including API/behavior changes 
- **[X]** Is this change gated behind config(s)? No, this is a CVE fix
- **[X]** Did you add sufficient unit test and/or integration test coverage for this PR? CVE fix is covered by existing unit tests
- **[X]** Does this change require modifying existing system tests or adding new system tests? NO
- **[X]** Must this be released …
=> Fix build due to Jackson upgrade to 2.16

dek-registry/src/main/java/io/confluent/dekregistry/web/rest/resources/DekRegistryResource.java
What
----
Minor refactor to ensure path param overrides request param for DEKs.  This allows filters to add contexts to the subject in the path only
Checklist
- Covered by existing tests
- **[N]** Must this be released together with other change(s), either in this repo or …
=> Minor refactor to ensure path param overrides request param for DEKs

dek-registry/src/main/java/io/confluent/dekregistry/storage/DekRegistry.java, dek-registry/src/main/java/io/confluent/dekregistry/web/rest/resources/DekRegistryResource.java, dek-registry/src/test/java/io/confluent/dekregistry/storage/DekRegistryTest.java
What
----
For shared KEKs avoid calling KMS when deleting DEKs
Checklist
- If so, please include the link(s) to the changes that must …
=> DGS-21830 For shared KEKs avoid calling KMS when deleting DEKs

client/src/main/java/io/confluent/kafka/schemaregistry/AbstractSchemaProvider.java, client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchemaProvider.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java, json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/JsonSchemaProvider.java, protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaProvider.java
What
----
Prevent re-registration of schema with dangling reference 
Checklist
- If so, please include the link(s) to the changes …
=> DGS-21829 Prevent re-registration of schema with dangling reference

client/src/main/java/io/confluent/kafka/schemaregistry/AbstractSchemaProvider.java
What
----
Checklist
References
----------
JIRA: …
=> Minor fix for pint merge issue

client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/MockSchemaRegistryClient.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClient.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaRegistryDeployment.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/client/LocalSchemaRegistryClient.java, core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ServerMetadataResource.java, core/src/main/java/io/confluent/kafka/schemaregistry/utils/Props.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiServerDeploymentTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java, core/src/test/java/io/confluent/kafka/schemaregistry/utils/PropsTest.java
https://github.com/confluentinc/schema-registry/pull/3860
=> Add deployment metadata endpoint

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/Schema.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaSchemaRegistry.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreMessageHandler.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/SchemaValue.java
What
----
Refine cache invalidation.  Soft deletes are invalidated per schema.  Hard deletes still cause the entire cache to be cleared as we don't yet prevent hard deleting referenced schemas.
Checklist
- Covered by existing tests
- **[N]** Must this be released together with …
=> Refine cache invalidation

client/src/main/java/io/confluent/kafka/schemaregistry/utils/QualifiedSubject.java
What
----
Checklist
References
----------
JIRA: …
=> MINOR add JavaDoc for QualifiedSubject

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java, client/src/test/java/io/confluent/kafka/schemaregistry/client/rest/ApacheClientRestServiceTest.java
What
----
Fixing bug where raw bytes being sent in the body would be corrupted.
Checklist
- **[ Y]** Contains customer facing changes? Including API/behavior changes 
- **[ N]** Is this change gated behind config(s)?
- **[ Y]** Did you add sufficient unit test and/or integration test coverage for this PR?
- **[ N]** Does this change require modifying existing system tests or adding new system tests? 
- **[ N]** Must this be released together with other change(s), either in this repo or another one?
- If so, please include the link(s) to …
=> Change apache client request body to raw bits

client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java
What
----
Some of the logs look like `Request to URL https://psrc-lg26v.westeurope.azure.confluent.cloud/schemas/ids/0?fetchMaxId=false&subject=fi.procomp.r2sisu.events.mobile.create_package.prod2test-value failed with error: psrc-lg26v.westeurope.azure.confluent.cloud.Failing over to next URL if available...`
Which isn't useful because it doesn't contain the class name of the exception.
Checklist
- If not, please explain why it is not …
=> Update RestService warn log to include error class name

pom.xml
What
----
Checklist
References
----------
JIRA: …
=> Upgrade kcache to 5.2.3

schema-serializer/src/main/java/io/confluent/kafka/serializers/wrapper/CompositeDeserializer.java, schema-serializer/src/test/java/io/confluent/kafka/serializers/wrapper/CompositeDeserializerTest.java
What
----
Support custom configs for the deserializers being wrapped in the CompositeDeserializer.
Checklist
- If so, please include …
=> Support custom configs in CompositeDeserializer

protobuf-provider/src/test/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaTest.java, protobuf-provider/src/test/resources/com/google/protobuf/descriptor-v30.proto, protobuf-provider/src/test/resources/com/google/protobuf/descriptor-v31.proto, protobuf-provider/src/test/resources/com/google/protobuf/descriptor-v32.proto
What
----
Add latest Protobuf descriptor.proto versions (30, 31, 32) to tests
Checklist
- If so, please include the link(s) to the …
=> Add latest Protobuf descriptor.proto versions to tests

bin/schema-compatibility-check, core/pom.xml, core/src/main/java/io/confluent/kafka/schemaregistry/tools/CheckSchemaCompatibility.java, core/src/test/java/io/confluent/kafka/schemaregistry/tools/CheckSchemaCompatibilityTest.java
What
----
this pr check if schema importer is safe to run across 2 context from 2 sr url
if both context contains schema and subjects under these does not match, return false;
Checklist
- **[ n]** Contains customer facing changes? Including API/behavior changes 
- **[n ]** Is this change gated behind config(s)?
- **[ y]** Did you add sufficient unit test and/or integration test coverage for this PR?
- **[ n]** Does this change require modifying existing system tests or adding new system tests? 
- **[ n]** Must this be released together …
=> add compatibility check script

core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/SubjectsResource.java, core/src/test/java/io/confluent/kafka/schemaregistry/rest/RestApiTest.java
What
----
This PR reverts the changes introduced by commit 9ac3e67 (Original PR: DGS-20986 / #3841) which modified the behavior of the POST /subjects/{subject} schema lookup endpoint.
The new behavior in commit 9ac3e67 has been identified as a breaking API change released inadvertently in Confluent Platform (CP) 8.0.1.
The reason it is a breaking change is that clients explicitly requesting normalize=false expect an immediate failure if an exact, non-normalized schema is not found. The automatic, hidden fallback to normalize=true violates this expected contract, leading to incorrect client behavior in production environments.
Checklist
- **[ ]** Contains customer facing changes? Including API/behavior …
=> REVERT: DGS-20986 - (Breaking API Change)

client-encryption-hcvault/src/main/java/io/confluent/kafka/schemaregistry/encryption/hcvault/HcVaultKmsClient.java, client-encryption-hcvault/src/main/java/io/confluent/kafka/schemaregistry/encryption/hcvault/HcVaultKmsDriver.java
What
----
Add AppRole auth for HC Vault.  Tested manually with local HC Vault instance with AppRole auth enabled.
Checklist
- Covered by existing tests plus new manual testing.
- If …
=> DGS-22404 Add AppRole auth for HC Vault

core/src/main/java/io/confluent/kafka/schemaregistry/storage/CompositeSchemaUpdateHandler.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStore.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/KafkaStoreReaderThread.java, core/src/main/java/io/confluent/kafka/schemaregistry/storage/StoreUpdateHandler.java
What
----
Add `StoreUpdateHandler.init()` that is called before the KafkaStoreReaderThread is initialized. Default implementation is empty to ensure backward compatibility.
Checklist
- This change is a no-op (by itself)
- **[N]** …
=> Add StoreUpdateHandler.init() function to call during KafkaStore initialization
